// Generated by GitHub Copilot
const { createRemoteWebpackConfig } = require('../../tools/webpack/remoteConfig');
module.exports = createRemoteWebpackConfig({ name: 'partnerOnboarding', port: 4207, appDir: __dirname });
