// Generated by GitHub Copilot
import { allowedBulkPresets, config } from '../config.js';

/**
 * Parses simple --key=value CLI flags.
 */
function parseFlags(argv) {
    const flags = {};

    for (const rawArg of argv) {
        if (!rawArg.startsWith('--')) {
            continue;
        }

        const [key, ...valueParts] = rawArg.slice(2).split('=');
        flags[key] = valueParts.length > 0 ? valueParts.join('=') : 'true';
    }

    return flags;
}

/**
 * Parses comma-separated domain list.
 */
function parseDomains(rawValue) {
    if (typeof rawValue !== 'string' || rawValue.trim() === '') {
        return undefined;
    }

    return rawValue
        .split(',')
        .map((domain) => domain.trim())
        .filter((domain) => domain.length > 0);
}

/**
 * Parses common boolean flag values.
 */
function parseBoolean(rawValue, fallback) {
    if (typeof rawValue !== 'string') {
        return fallback;
    }

    const normalized = rawValue.trim().toLowerCase();
    if (normalized === 'true' || normalized === '1' || normalized === 'yes') {
        return true;
    }

    if (normalized === 'false' || normalized === '0' || normalized === 'no') {
        return false;
    }

    return fallback;
}

/**
 * Parses integer flags with fallback.
 */
function parseInteger(rawValue, fallback) {
    if (typeof rawValue !== 'string' || rawValue.trim() === '') {
        return fallback;
    }

    const parsed = Number.parseInt(rawValue, 10);
    if (Number.isNaN(parsed)) {
        return fallback;
    }

    return parsed;
}

/**
 * Runs admin bulk-load endpoint with deterministic options.
 */
async function main() {
    const flags = parseFlags(process.argv.slice(2));
    const requestedPreset = (flags.preset ?? config.defaultBulkPreset).toLowerCase();
    const preset = allowedBulkPresets.includes(requestedPreset) ? requestedPreset : config.defaultBulkPreset;
    const seed = parseInteger(flags.seed, config.defaultBulkSeed);
    const truncate = parseBoolean(flags.truncate, true);
    const domains = parseDomains(flags.domains);
    const apiBase = (flags['api-base'] ?? process.env.BULK_LOAD_API_BASE ?? `http://localhost:${config.port}/api`).replace(/\/$/, '');

    const payload = {
        preset,
        seed,
        truncate,
        domains,
    };

    console.log(`[bulk-load] invoking ${apiBase}/admin/bulk-load with preset=${preset} seed=${seed}`);

    const response = await fetch(`${apiBase}/admin/bulk-load`, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            Accept: 'application/json',
        },
        body: JSON.stringify(payload),
    });

    if (!response.ok) {
        const body = await response.text();
        throw new Error(`Bulk load failed (${response.status}): ${body}`);
    }

    const result = await response.json();
    console.log('[bulk-load] completed');
    console.log(JSON.stringify(result, null, 2));
}

main().catch((error) => {
    console.error('[bulk-load] failed', error);
    process.exit(1);
});
