// Generated by GitHub Copilot
import { seedDomains } from '../bootstrap.js';

/**
 * Runs deterministic small preset seeding for local environments.
 */
async function main() {
    const seed = Number.parseInt(process.env.BULK_LOAD_SEED ?? '42', 10) || 42;
    const meta = await seedDomains({ preset: 'small', seed });
    console.log(`[seed-small] completed preset=${meta.preset} seed=${meta.seed}`);
}

main().catch((error) => {
    console.error('[seed-small] failed', error);
    process.exit(1);
});
