// Generated by GitHub Copilot
import React from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import { AuthProvider } from '@shared/auth';
import PartnerOnboardingApp from './remote-entry';

const root = createRoot(document.getElementById('root')!);
root.render(<React.StrictMode><BrowserRouter><AuthProvider><PartnerOnboardingApp /></AuthProvider></BrowserRouter></React.StrictMode>);
