#!/usr/bin/env bash
# Generated by GitHub Copilot
set -euo pipefail

INPUT="$(cat || true)"
if [[ -z "${INPUT//[[:space:]]/}" ]]; then
  exit 0
fi

extract_command() {
  if command -v node >/dev/null 2>&1; then
    node -e 'let d="";process.stdin.on("data",c=>d+=c);process.stdin.on("end",()=>{try{const j=JSON.parse(d);const c=(j.tool_input&&j.tool_input.command)||"";process.stdout.write(c);}catch(_){}});' <<<"$INPUT"
    return 0
  fi

  printf '%s' "$INPUT" | sed -n 's/.*"command"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p'
}

COMMAND="$(extract_command)"
if [[ -z "${COMMAND}" ]]; then
  exit 0
fi

case "$COMMAND" in
  *"git reset --hard"*|*"git clean -fd"*|*"git checkout -- "*|*"rm -rf /"*|*"mkfs"*|*"format "*|*"shutdown "*|*"reboot "*)
    echo "Blocked by .claude/hooks/validate-bash.sh: destructive command detected." >&2
    exit 2
    ;;
esac

if [[ "$COMMAND" =~ (^|[[:space:]])(curl|wget)[[:space:]].*\|[[:space:]]*(sh|bash) ]]; then
  echo "Blocked by .claude/hooks/validate-bash.sh: piping remote scripts to a shell is not allowed." >&2
  exit 2
fi

exit 0
