# Generated by GitHub Copilot
# Partner Portal Microfrontends - Development Makefile

# Configuration
ENV_FILE ?= .env.development
NX_RUNNER := node ./tools/scripts/run-nx.js
PORT_CLEANER := node ./tools/scripts/prepare-dev-ports.js

ALL_APPS := shell,risk-assessment,compliance-dashboard,audit-management,policy-management,incident-reporting,vendor-risk,partner-onboarding
SECURITY_APPS := shell,risk-assessment,compliance-dashboard,audit-management,policy-management,incident-reporting
LIFECYCLE_APPS := shell,vendor-risk,partner-onboarding

# Load .env file into shell environment for a single recipe line.
LOAD_ENV = set -a; [ -f $(ENV_FILE) ] && . $(ENV_FILE); set +a

UNSUPPORTED_TARGETS := dev-worker dev-logs db-check test-api test-sdk test-shared test-web test-migrations test-bruno test-bruno-system lint-fix openapi-generate branch-validate branch build-sdk obs obs-down obs-clean obs-logs dev-api-key

.PHONY: help bootstrap env-check \
	run run-ms-auth all-in-one backend down clean \
	ui-dev ui-build ui-build-local \
	build build-affected lint lint-affected test test-watch test-coverage type ci graph \
	start-shell start-risk start-compliance start-audit start-policy start-incidents start-vendor start-onboarding \
	risk-compliance-stack vendor-lifecycle-stack full-portal-stack \
	$(UNSUPPORTED_TARGETS)

define check_node_modules
	@if [ ! -d node_modules ]; then \
		echo "[$1] node_modules not found. Installing dependencies..."; \
		npm install --legacy-peer-deps; \
	fi
endef

define check_env
	@if [ ! -f $(ENV_FILE) ]; then \
		if [ -f .env.example ]; then \
			echo "[$1] Creating $(ENV_FILE) from .env.example"; \
			cp .env.example $(ENV_FILE); \
		else \
			echo "[$1] ERROR: Missing $(ENV_FILE) and .env.example"; \
			exit 1; \
		fi; \
	fi
endef

define check_ms_auth_env
	@$(LOAD_ENV); \
	if [ -z "$$MSAL_CLIENT_ID" ] || [ "$$MSAL_CLIENT_ID" = "your-app-registration-client-id" ]; then \
		echo "[$1] ERROR: MSAL_CLIENT_ID is not set in $(ENV_FILE)"; \
		exit 1; \
	fi; \
	if [ -z "$$MSAL_TENANT_ID" ] || [ "$$MSAL_TENANT_ID" = "your-azure-ad-tenant-id" ]; then \
		echo "[$1] ERROR: MSAL_TENANT_ID is not set in $(ENV_FILE)"; \
		exit 1; \
	fi
endef

# Default target
help:
	@echo "Partner Portal Microfrontends - Available targets"
	@echo ""
	@echo "Core development:"
	@echo "  bootstrap              - Install dependencies and create $(ENV_FILE) if missing"
	@echo "  env-check              - Verify local tooling and environment files"
	@echo "  run                    - Start shell + all micro-apps (full local portal)"
	@echo "  run-ms-auth            - Start shell + all micro-apps with Azure auth enabled"
	@echo "  all-in-one             - Alias of run"
	@echo "  backend                - Start local backend API (Node/Express on port 5000)"
	@echo "  down                   - Stop repo-owned Nx dev listeners on ports 4200-4207"
	@echo "  clean                  - down + clear build cache artifacts"
	@echo ""
	@echo "Problem statement use-case stacks:"
	@echo "  risk-compliance-stack  - Shell + risk/compliance/audit/policy/incidents"
	@echo "  vendor-lifecycle-stack - Shell + vendor-risk + partner-onboarding"
	@echo "  full-portal-stack      - Alias of run"
	@echo ""
	@echo "Single-app serve targets:"
	@echo "  start-shell            - Serve shell (port 4200)"
	@echo "  start-risk             - Serve risk-assessment (port 4201)"
	@echo "  start-compliance       - Serve compliance-dashboard (port 4202)"
	@echo "  start-audit            - Serve audit-management (port 4203)"
	@echo "  start-policy           - Serve policy-management (port 4204)"
	@echo "  start-incidents        - Serve incident-reporting (port 4205)"
	@echo "  start-vendor           - Serve vendor-risk (port 4206)"
	@echo "  start-onboarding       - Serve partner-onboarding (port 4207)"
	@echo ""
	@echo "Quality and delivery:"
	@echo "  lint                   - Lint all projects"
	@echo "  lint-affected          - Lint only affected projects"
	@echo "  test                   - Run all tests once"
	@echo "  test-watch             - Run tests in watch mode"
	@echo "  test-coverage          - Run tests with coverage"
	@echo "  type                   - Run TypeScript type checking"
	@echo "  build                  - Build all projects"
	@echo "  build-affected         - Build only affected projects"
	@echo "  ui-dev                 - Alias of run"
	@echo "  ui-build               - Alias of build"
	@echo "  ui-build-local         - Build all projects in development mode"
	@echo "  ci                     - Lint + type + test + build"
	@echo "  graph                  - Open Nx dependency graph"
	@echo ""
	@echo "Podman users: pm-* aliases are available via Makefile.podman"

# One-time setup
bootstrap:
	$(call check_node_modules,bootstrap)
	$(call check_env,bootstrap)
	@echo "[bootstrap] Done. Next: make run"

# Verify local prerequisites for this workspace
env-check:
	@command -v node >/dev/null 2>&1 || (echo "[env-check] ERROR: node is required" && exit 1)
	@command -v npm >/dev/null 2>&1 || (echo "[env-check] ERROR: npm is required" && exit 1)
	@node -e "console.log('[env-check] Node ' + process.version)"
	$(call check_env,env-check)
	@echo "[env-check] Checking repo-owned dev listeners on ports 4200-4207"
	@$(PORT_CLEANER)
	@echo "[env-check] Environment looks good"

# Start shell + all remotes (full modernization stack)
run:
	$(call check_node_modules,run)
	$(call check_env,run)
	@echo "[run] Freeing stale local dev ports..."
	@$(PORT_CLEANER)
	@echo "[run] Starting shell + all micro-apps for full portal flow"
	@$(LOAD_ENV); $(NX_RUNNER) run-many --target=serve --projects=$(ALL_APPS) --parallel=8

# Start with Azure auth enabled (mock auth disabled)
run-ms-auth:
	$(call check_node_modules,run-ms-auth)
	$(call check_env,run-ms-auth)
	$(call check_ms_auth_env,run-ms-auth)
	@echo "[run-ms-auth] Freeing stale local dev ports..."
	@$(PORT_CLEANER)
	@echo "[run-ms-auth] Starting shell + remotes with Azure auth"
	@$(LOAD_ENV); USE_MOCK_AUTH=false VITE_USE_MOCKED_AUTH=false $(NX_RUNNER) run-many --target=serve --projects=$(ALL_APPS) --parallel=8

# Keep legacy naming familiar for teams migrating from monolith tooling
all-in-one: run

# Backend API local run (without containers)
backend:
	@echo "[backend] Ensuring backend dependencies"
	@cd backend && if [ ! -d node_modules ]; then npm install; fi
	@echo "[backend] Ensuring backend environment file"
	@cd backend && if [ ! -f .env ]; then cp .env.example .env; fi
	@cd backend && node -e "const fs=require('node:fs');const file='.env';if(fs.existsSync(file)){const raw=fs.readFileSync(file,'utf8');const next=raw.replace(/@localhost:/g,'@127.0.0.1:');if(next!==raw){fs.writeFileSync(file,next);console.log('[backend] Updated DATABASE_URL host localhost -> 127.0.0.1');}}"
	@echo "[backend] Starting backend API on http://localhost:5000"
	@cd backend && npm run dev

# Stop local dev listeners started by this repo
down:
	@echo "[down] Stopping repo-owned Nx dev listeners on 4200-4207"
	@$(PORT_CLEANER)

# Clear common build artifacts and reset Nx state
clean:
	@echo "[clean] Cleaning generated artifacts and Nx state"
	@$(PORT_CLEANER)
	@$(NX_RUNNER) reset
	@rm -rf dist .nx/cache

# Use-case stacks aligned to modernization problem statement
risk-compliance-stack:
	$(call check_node_modules,risk-compliance-stack)
	$(call check_env,risk-compliance-stack)
	@echo "[risk-compliance-stack] Starting security and compliance domain apps"
	@$(PORT_CLEANER)
	@$(LOAD_ENV); $(NX_RUNNER) run-many --target=serve --projects=$(SECURITY_APPS) --parallel=6

vendor-lifecycle-stack:
	$(call check_node_modules,vendor-lifecycle-stack)
	$(call check_env,vendor-lifecycle-stack)
	@echo "[vendor-lifecycle-stack] Starting vendor and onboarding flow"
	@$(PORT_CLEANER)
	@$(LOAD_ENV); $(NX_RUNNER) run-many --target=serve --projects=$(LIFECYCLE_APPS) --parallel=3

full-portal-stack: run

# App-specific serve targets
start-shell:
	$(call check_node_modules,start-shell)
	$(call check_env,start-shell)
	@$(PORT_CLEANER)
	@$(LOAD_ENV); $(NX_RUNNER) serve shell

start-risk:
	$(call check_node_modules,start-risk)
	$(call check_env,start-risk)
	@$(PORT_CLEANER)
	@$(LOAD_ENV); $(NX_RUNNER) serve risk-assessment

start-compliance:
	$(call check_node_modules,start-compliance)
	$(call check_env,start-compliance)
	@$(PORT_CLEANER)
	@$(LOAD_ENV); $(NX_RUNNER) serve compliance-dashboard

start-audit:
	$(call check_node_modules,start-audit)
	$(call check_env,start-audit)
	@$(PORT_CLEANER)
	@$(LOAD_ENV); $(NX_RUNNER) serve audit-management

start-policy:
	$(call check_node_modules,start-policy)
	$(call check_env,start-policy)
	@$(PORT_CLEANER)
	@$(LOAD_ENV); $(NX_RUNNER) serve policy-management

start-incidents:
	$(call check_node_modules,start-incidents)
	$(call check_env,start-incidents)
	@$(PORT_CLEANER)
	@$(LOAD_ENV); $(NX_RUNNER) serve incident-reporting

start-vendor:
	$(call check_node_modules,start-vendor)
	$(call check_env,start-vendor)
	@$(PORT_CLEANER)
	@$(LOAD_ENV); $(NX_RUNNER) serve vendor-risk

start-onboarding:
	$(call check_node_modules,start-onboarding)
	$(call check_env,start-onboarding)
	@$(PORT_CLEANER)
	@$(LOAD_ENV); $(NX_RUNNER) serve partner-onboarding

# Build and quality workflows
ui-dev: run

ui-build: build

ui-build-local:
	$(call check_node_modules,ui-build-local)
	$(call check_env,ui-build-local)
	@echo "[ui-build-local] Building all apps with development configuration"
	@$(LOAD_ENV); $(NX_RUNNER) run-many --target=build --all --configuration=development --parallel=3

build:
	$(call check_node_modules,build)
	@$(NX_RUNNER) run-many --target=build --all --parallel=3

build-affected:
	$(call check_node_modules,build-affected)
	@$(NX_RUNNER) affected --target=build --parallel=3

lint:
	$(call check_node_modules,lint)
	@$(NX_RUNNER) run-many --target=lint --all --parallel=3

lint-affected:
	$(call check_node_modules,lint-affected)
	@$(NX_RUNNER) affected --target=lint --parallel=3

test:
	$(call check_node_modules,test)
	@npm run test

test-watch:
	$(call check_node_modules,test-watch)
	@npm run test:watch

test-coverage:
	$(call check_node_modules,test-coverage)
	@npm run test:coverage

type:
	$(call check_node_modules,type)
	@npx tsc -p tsconfig.base.json --noEmit

ci:
	$(MAKE) lint
	$(MAKE) type
	$(MAKE) test
	$(MAKE) build
	@echo "[ci] All checks passed"

graph:
	$(call check_node_modules,graph)
	@$(NX_RUNNER) graph

# Compatibility placeholders for backend-only targets from the source template.
$(UNSUPPORTED_TARGETS):
	@echo "[$@] Not applicable in this Nx frontend monorepo."
	@echo "[$@] This workspace has no Docker Compose or Python backend stack."
	@echo "[$@] Use 'make help' for supported shell, micro-app, and module federation targets."

# Optional Podman compatibility aliases
-include Makefile.podman
