// Generated by GitHub Copilot
import { defineConfig } from 'vitest/config';

export default defineConfig({
    test: {
        globals: true,
        environment: 'jsdom',
        setupFiles: ['./vitest.setup.ts'],
        bail: 1,
        coverage: {
            provider: 'v8',
            reporter: ['text', 'lcov'],
        },
    },
    resolve: {
        alias: {
            '@shared/ui-components': '/libs/shared/ui-components/src/index.ts',
            '@shared/auth': '/libs/shared/auth/src/index.ts',
            '@shared/types': '/libs/shared/types/src/index.ts',
            '@shared/api-client': '/libs/shared/api-client/src/index.ts',
            '@shared/event-bus': '/libs/shared/event-bus/src/index.ts',
        },
    },
});
