/**
 * Runs Nx commands with plugin isolation disabled.
 * Some Windows environments fail to start isolated plugin workers for nx/js dependencies.
 */
const { spawn } = require('child_process');

const args = process.argv.slice(2);

// Generated by GitHub Copilot
const nxBinPath = require.resolve('nx/bin/nx.js');
const env = {
  ...process.env,
  NX_ISOLATE_PLUGINS: process.env.NX_ISOLATE_PLUGINS ?? 'false',
  NX_DAEMON: process.env.NX_DAEMON ?? 'false',
};

const child = spawn(process.execPath, [nxBinPath, ...args], {
  stdio: 'inherit',
  cwd: process.cwd(),
  env,
});

child.on('error', (error) => {
  console.error('Failed to start Nx process:', error);
  process.exit(1);
});

child.on('exit', (code, signal) => {
  if (signal) {
    process.kill(process.pid, signal);
    return;
  }

  process.exit(code ?? 1);
});
