// Generated by GitHub Copilot
import React from 'react';
import { render, screen, act } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { axe, toHaveNoViolations } from 'jest-axe';
import { vi, describe, it, expect, beforeEach, afterEach } from 'vitest';
import { PortalThemeProvider, useThemeMode } from './ThemeProvider';

expect.extend(toHaveNoViolations);

vi.mock('@mui/material/styles', () => ({
    ThemeProvider: ({ children }: any) => <div data-testid="mui-theme-provider">{children}</div>,
}));
vi.mock('@mui/material/CssBaseline', () => ({ default: () => null }));
vi.mock('./darkTheme', () => ({ darkTheme: { palette: { mode: 'dark' } } }));
vi.mock('./lightTheme', () => ({ lightTheme: { palette: { mode: 'light' } } }));

// Helper consumer component
const ThemeConsumer: React.FC = () => {
    const { themeMode, toggleTheme, setThemeMode } = useThemeMode();
    return (
        <div>
            <span data-testid="mode">{themeMode}</span>
            <button onClick={toggleTheme}>Toggle</button>
            <button onClick={() => setThemeMode('light')}>Set Light</button>
            <button onClick={() => setThemeMode('dark')}>Set Dark</button>
        </div>
    );
};

describe('PortalThemeProvider', () => {
    beforeEach(() => {
        vi.clearAllMocks();
        localStorage.clear();
    });
    afterEach(() => {
        localStorage.clear();
    });

    describe('default theme', () => {
        it('defaults to dark mode when no localStorage value', () => {
            render(<PortalThemeProvider><ThemeConsumer /></PortalThemeProvider>);
            expect(screen.getByTestId('mode')).toHaveTextContent('dark');
        });

        it('restores persisted light mode from localStorage', () => {
            localStorage.setItem('partner-portal-theme-mode', 'light');
            render(<PortalThemeProvider><ThemeConsumer /></PortalThemeProvider>);
            expect(screen.getByTestId('mode')).toHaveTextContent('light');
        });

        it('restores persisted dark mode from localStorage', () => {
            localStorage.setItem('partner-portal-theme-mode', 'dark');
            render(<PortalThemeProvider><ThemeConsumer /></PortalThemeProvider>);
            expect(screen.getByTestId('mode')).toHaveTextContent('dark');
        });

        it('ignores invalid localStorage value and defaults to dark', () => {
            localStorage.setItem('partner-portal-theme-mode', 'purple');
            render(<PortalThemeProvider><ThemeConsumer /></PortalThemeProvider>);
            expect(screen.getByTestId('mode')).toHaveTextContent('dark');
        });
    });

    describe('theme toggling', () => {
        it('toggles from dark to light', async () => {
            render(<PortalThemeProvider><ThemeConsumer /></PortalThemeProvider>);
            expect(screen.getByTestId('mode')).toHaveTextContent('dark');
            await userEvent.click(screen.getByRole('button', { name: 'Toggle' }));
            expect(screen.getByTestId('mode')).toHaveTextContent('light');
        });

        it('toggles from light to dark', async () => {
            localStorage.setItem('partner-portal-theme-mode', 'light');
            render(<PortalThemeProvider><ThemeConsumer /></PortalThemeProvider>);
            await userEvent.click(screen.getByRole('button', { name: 'Toggle' }));
            expect(screen.getByTestId('mode')).toHaveTextContent('dark');
        });

        it('persists mode to localStorage on toggle', async () => {
            render(<PortalThemeProvider><ThemeConsumer /></PortalThemeProvider>);
            await userEvent.click(screen.getByRole('button', { name: 'Toggle' }));
            expect(localStorage.getItem('partner-portal-theme-mode')).toBe('light');
        });
    });

    describe('setThemeMode', () => {
        it('sets light mode directly', async () => {
            render(<PortalThemeProvider><ThemeConsumer /></PortalThemeProvider>);
            await userEvent.click(screen.getByRole('button', { name: 'Set Light' }));
            expect(screen.getByTestId('mode')).toHaveTextContent('light');
        });

        it('persists explicit mode to localStorage', async () => {
            render(<PortalThemeProvider><ThemeConsumer /></PortalThemeProvider>);
            await userEvent.click(screen.getByRole('button', { name: 'Set Light' }));
            expect(localStorage.getItem('partner-portal-theme-mode')).toBe('light');
        });
    });

    describe('useThemeMode hook', () => {
        it('throws when used outside PortalThemeProvider', () => {
            const spy = vi.spyOn(console, 'error').mockImplementation(() => { });
            expect(() => render(<ThemeConsumer />)).toThrow();
            spy.mockRestore();
        });
    });

    describe('accessibility', () => {
        it('has no accessibility violations', async () => {
            const { container } = render(
                <PortalThemeProvider><div>App content</div></PortalThemeProvider>
            );
            expect(await axe(container)).toHaveNoViolations();
        });
    });
});
