// Generated by GitHub Copilot
/**
 * Mock Data — Static data for all 7 micro-app domains.
 * Used for development and standalone remote testing.
 */
import {
  RiskAssessment,
  RiskLevel,
  ComplianceFramework,
  ComplianceControl,
  ComplianceStatus,
  AuditPlan,
  AuditStatus,
  AuditFinding,
  Policy,
  PolicyStatus,
  Incident,
  IncidentSeverity,
  IncidentStatus,
  Vendor,
  VendorRiskRating,
  Partner,
  OnboardingStep,
  OnboardingStatus,
} from '@shared/types';

/* ─── Risk Assessment Data ──────────────────────────────────────── */
const risks: RiskAssessment[] = [
  { id: 'RSK-001', title: 'Unpatched production servers', description: 'Critical servers missing latest security patches', category: 'Infrastructure', likelihood: 4, impact: 5, riskScore: 20, riskLevel: RiskLevel.Critical, owner: 'IT Ops Team', mitigationPlan: 'Schedule emergency patching window', status: 'open', dueDate: '2026-04-30', createdBy: 'admin', createdAt: '2026-03-01' },
  { id: 'RSK-002', title: 'Third-party API key exposure', description: 'API keys stored in plain text config files', category: 'Application Security', likelihood: 3, impact: 4, riskScore: 12, riskLevel: RiskLevel.High, owner: 'DevSecOps', mitigationPlan: 'Migrate to Azure Key Vault', status: 'open', dueDate: '2026-05-15', createdBy: 'admin', createdAt: '2026-03-05' },
  { id: 'RSK-003', title: 'Insufficient access logging', description: 'No centralized audit logging for database access', category: 'Data Security', likelihood: 3, impact: 3, riskScore: 9, riskLevel: RiskLevel.Medium, owner: 'DBA Team', mitigationPlan: 'Implement Azure Monitor log analytics', status: 'mitigated', dueDate: '2026-06-01', createdBy: 'admin', createdAt: '2026-02-20' },
  { id: 'RSK-004', title: 'Weak password policy for partners', description: 'Partner accounts allow passwords under 8 characters', category: 'Identity Management', likelihood: 2, impact: 3, riskScore: 6, riskLevel: RiskLevel.Low, owner: 'IAM Team', mitigationPlan: 'Enforce minimum 12-char passwords with MFA', status: 'open', dueDate: '2026-04-20', createdBy: 'admin', createdAt: '2026-03-10' },
  { id: 'RSK-005', title: 'No disaster recovery test plan', description: 'DR plan not tested in over 18 months', category: 'Business Continuity', likelihood: 2, impact: 5, riskScore: 10, riskLevel: RiskLevel.High, owner: 'Infrastructure', mitigationPlan: 'Schedule quarterly DR drills', status: 'open', dueDate: '2026-05-01', createdBy: 'admin', createdAt: '2026-03-15' },
];

/* ─── Compliance Data ───────────────────────────────────────────── */
const frameworks: ComplianceFramework[] = [
  { id: 'FW-001', name: 'SOC 2 Type II', totalControls: 64, compliantControls: 52, nonCompliantControls: 5, inProgressControls: 7, score: 81 },
  { id: 'FW-002', name: 'ISO 27001', totalControls: 114, compliantControls: 98, nonCompliantControls: 8, inProgressControls: 8, score: 86 },
  { id: 'FW-003', name: 'GDPR', totalControls: 42, compliantControls: 38, nonCompliantControls: 2, inProgressControls: 2, score: 90 },
  { id: 'FW-004', name: 'NIST CSF', totalControls: 108, compliantControls: 82, nonCompliantControls: 12, inProgressControls: 14, score: 76 },
];

const controls: ComplianceControl[] = [
  { id: 'CTL-001', frameworkId: 'FW-001', controlId: 'CC6.1', title: 'Logical and Physical Access Controls', description: 'Access restricted to authorized users', status: ComplianceStatus.Compliant, owner: 'IAM Team', evidenceCount: 3, lastAssessedDate: '2026-03-15', createdBy: 'admin', createdAt: '2025-12-01' },
  { id: 'CTL-002', frameworkId: 'FW-001', controlId: 'CC7.2', title: 'System Monitoring', description: 'Monitor for anomalies and incidents', status: ComplianceStatus.NonCompliant, owner: 'SOC Team', evidenceCount: 1, lastAssessedDate: '2026-03-10', createdBy: 'admin', createdAt: '2025-12-01' },
  { id: 'CTL-003', frameworkId: 'FW-002', controlId: 'A.12.4', title: 'Logging and Monitoring', description: 'Event logs shall be produced, retained', status: ComplianceStatus.InProgress, owner: 'IT Ops', evidenceCount: 2, lastAssessedDate: '2026-03-20', createdBy: 'admin', createdAt: '2025-12-15' },
];

/* ─── Audit Data ────────────────────────────────────────────────── */
const audits: AuditPlan[] = [
  { id: 'AUD-001', title: 'Q1 2026 Internal Security Audit', scope: 'Infrastructure and application security', status: AuditStatus.Completed, startDate: '2026-01-15', endDate: '2026-03-01', leadAuditor: 'Sarah Chen', findingsCount: 8, createdBy: 'admin', createdAt: '2026-01-01' },
  { id: 'AUD-002', title: 'SOC 2 Type II Annual Audit', scope: 'All trust service criteria', status: AuditStatus.InProgress, startDate: '2026-03-01', endDate: '2026-06-30', leadAuditor: 'External - Deloitte', findingsCount: 3, createdBy: 'admin', createdAt: '2026-02-15' },
  { id: 'AUD-003', title: 'Partner Data Handling Review', scope: 'Data processing and storage practices', status: AuditStatus.Planned, startDate: '2026-05-01', endDate: '2026-06-15', leadAuditor: 'Mike Johnson', findingsCount: 0, createdBy: 'admin', createdAt: '2026-03-20' },
];

const findings: AuditFinding[] = [
  { id: 'FND-001', auditPlanId: 'AUD-001', title: 'Excessive admin privileges', description: '12 users have unnecessary admin access', severity: RiskLevel.High, owner: 'IAM Team', remediationStatus: 'in-progress', dueDate: '2026-04-15', createdBy: 'admin', createdAt: '2026-02-20' },
  { id: 'FND-002', auditPlanId: 'AUD-001', title: 'Missing encryption at rest', description: 'Database backups not encrypted', severity: RiskLevel.Critical, owner: 'DBA Team', remediationStatus: 'open', dueDate: '2026-04-01', createdBy: 'admin', createdAt: '2026-02-22' },
  { id: 'FND-003', auditPlanId: 'AUD-002', title: 'Incomplete change management logs', description: 'Some production changes not documented', severity: RiskLevel.Medium, owner: 'DevOps', remediationStatus: 'in-progress', dueDate: '2026-05-01', createdBy: 'admin', createdAt: '2026-03-10' },
];

/* ─── Policy Data ───────────────────────────────────────────────── */
const policies: Policy[] = [
  { id: 'POL-001', title: 'Information Security Policy', category: 'Security', status: PolicyStatus.Published, version: '3.1', owner: 'CISO', approver: 'CTO', effectiveDate: '2026-01-01', reviewDate: '2027-01-01', summary: 'Establishes the overall security framework and responsibilities.', createdBy: 'admin', createdAt: '2025-11-01' },
  { id: 'POL-002', title: 'Acceptable Use Policy', category: 'HR/IT', status: PolicyStatus.Published, version: '2.0', owner: 'HR Director', approver: 'CIO', effectiveDate: '2026-02-01', reviewDate: '2027-02-01', summary: 'Defines acceptable use of company IT resources.', createdBy: 'admin', createdAt: '2025-12-01' },
  { id: 'POL-003', title: 'Data Classification Standard', category: 'Data', status: PolicyStatus.UnderReview, version: '1.2-draft', owner: 'Data Protection Officer', approver: 'CISO', effectiveDate: '', reviewDate: '', summary: 'Defines data classification levels and handling requirements.', createdBy: 'admin', createdAt: '2026-02-15' },
  { id: 'POL-004', title: 'Incident Response Plan', category: 'Security', status: PolicyStatus.Draft, version: '0.9', owner: 'SOC Manager', approver: 'CISO', effectiveDate: '', reviewDate: '', summary: 'Procedures for detecting, responding, and recovering from incidents.', createdBy: 'admin', createdAt: '2026-03-01' },
];

/* ─── Incident Data ─────────────────────────────────────────────── */
const incidents: Incident[] = [
  { id: 'INC-001', title: 'Phishing attack on partner accounts', description: 'Multiple partners reported phishing emails mimicking portal login', severity: IncidentSeverity.High, status: IncidentStatus.Investigating, category: 'Phishing', affectedSystems: ['Partner Portal', 'Email'], reporter: 'SOC Analyst', assignee: 'Security Team', reportedAt: '2026-04-01T09:15:00Z', createdBy: 'admin', createdAt: '2026-04-01' },
  { id: 'INC-002', title: 'Unauthorized data export attempt', description: 'Anomalous bulk data export detected from internal user', severity: IncidentSeverity.Critical, status: IncidentStatus.Mitigated, category: 'Data Exfiltration', affectedSystems: ['CRM', 'Data Warehouse'], reporter: 'SIEM Alert', assignee: 'DLP Team', reportedAt: '2026-03-28T14:30:00Z', createdBy: 'admin', createdAt: '2026-03-28' },
  { id: 'INC-003', title: 'SSL certificate expiry on API gateway', description: 'Certificate for api.portal.com expired causing 503 errors', severity: IncidentSeverity.Medium, status: IncidentStatus.Resolved, category: 'Configuration', affectedSystems: ['API Gateway'], reporter: 'Monitoring', assignee: 'Infrastructure', reportedAt: '2026-03-25T08:00:00Z', resolvedAt: '2026-03-25T10:30:00Z', createdBy: 'admin', createdAt: '2026-03-25' },
];

/* ─── Vendor Data ───────────────────────────────────────────────── */
const vendors: Vendor[] = [
  { id: 'VND-001', name: 'CloudSecure Inc.', category: 'Cloud Infrastructure', riskRating: VendorRiskRating.Low, riskScore: 22, lastAssessmentDate: '2026-03-01', contractExpiry: '2027-06-30', contactEmail: 'security@cloudsecure.com', status: 'active', createdBy: 'admin', createdAt: '2025-06-01' },
  { id: 'VND-002', name: 'DataFlow Analytics', category: 'Data Processing', riskRating: VendorRiskRating.Medium, riskScore: 55, lastAssessmentDate: '2026-02-15', contractExpiry: '2026-12-31', contactEmail: 'compliance@dataflow.io', status: 'active', createdBy: 'admin', createdAt: '2025-08-15' },
  { id: 'VND-003', name: 'QuickPay Solutions', category: 'Payment Processing', riskRating: VendorRiskRating.High, riskScore: 78, lastAssessmentDate: '2026-01-20', contractExpiry: '2026-09-30', contactEmail: 'security@quickpay.com', status: 'under-review', createdBy: 'admin', createdAt: '2025-03-01' },
  { id: 'VND-004', name: 'TalentHub HR', category: 'HR Services', riskRating: VendorRiskRating.Low, riskScore: 18, lastAssessmentDate: '2026-03-10', contractExpiry: '2027-03-31', contactEmail: 'privacy@talenthub.com', status: 'active', createdBy: 'admin', createdAt: '2025-09-01' },
];

/* ─── Partner Onboarding Data ───────────────────────────────────── */
const partners: Partner[] = [
  { id: 'PTR-001', companyName: 'Acme Global Solutions', contactName: 'John Smith', contactEmail: 'john@acmeglobal.com', industry: 'Financial Services', country: 'United States', currentStep: OnboardingStep.Approval, status: OnboardingStatus.PendingApproval, submittedAt: '2026-03-20', createdBy: 'admin', createdAt: '2026-03-15' },
  { id: 'PTR-002', companyName: 'EuroTech GmbH', contactName: 'Hans Mueller', contactEmail: 'hans@eurotech.de', industry: 'Technology', country: 'Germany', currentStep: OnboardingStep.ComplianceAttestation, status: OnboardingStatus.InProgress, createdBy: 'admin', createdAt: '2026-03-22' },
  { id: 'PTR-003', companyName: 'Asia Pacific Trading', contactName: 'Li Wei', contactEmail: 'li.wei@aptrade.com', industry: 'Retail', country: 'Singapore', currentStep: OnboardingStep.KycDocuments, status: OnboardingStatus.InProgress, createdBy: 'admin', createdAt: '2026-04-01' },
  { id: 'PTR-004', companyName: 'Nordic Consulting AB', contactName: 'Erik Svensson', contactEmail: 'erik@nordicconsulting.se', industry: 'Consulting', country: 'Sweden', currentStep: OnboardingStep.CompanyInfo, status: OnboardingStatus.Approved, submittedAt: '2026-02-10', approvedAt: '2026-02-28', createdBy: 'admin', createdAt: '2026-02-01' },
];

/* ─── Export All Mock Data ──────────────────────────────────────── */
export const mockData = {
  risks,
  frameworks,
  controls,
  audits,
  findings,
  policies,
  incidents,
  vendors,
  partners,
};
