// Generated by GitHub Copilot
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const { container } = require('webpack');
const { ModuleFederationPlugin } = container;

/** @type {import('webpack').Configuration} */
module.exports = {
  context: __dirname,
  entry: './src/index.ts',
  mode: 'development',
  devServer: {
    port: 4200,
    historyApiFallback: true,
    headers: { 'Access-Control-Allow-Origin': '*' },
  },
  output: {
    publicPath: 'auto',
    path: path.resolve(__dirname, '../../dist/apps/shell'),
    clean: true,
  },
  resolve: {
    extensions: ['.ts', '.tsx', '.js', '.jsx'],
    alias: {
      '@shared/types': path.resolve(__dirname, '../../libs/shared/types/src/index.ts'),
      '@shared/auth': path.resolve(__dirname, '../../libs/shared/auth/src/index.ts'),
      '@shared/ui-components': path.resolve(__dirname, '../../libs/shared/ui-components/src/index.ts'),
      '@shared/api-client': path.resolve(__dirname, '../../libs/shared/api-client/src/index.ts'),
      '@shared/event-bus': path.resolve(__dirname, '../../libs/shared/event-bus/src/index.ts'),
    },
  },
  module: {
    rules: [
      { test: /\.tsx?$/, use: { loader: 'ts-loader', options: { configFile: 'tsconfig.app.json' } }, exclude: /node_modules/ },
      { test: /\.css$/, use: ['style-loader', 'css-loader'] },
    ],
  },
  plugins: [
    new ModuleFederationPlugin({
      name: 'shell',
      remotes: {
        riskAssessment: 'riskAssessment@http://localhost:4201/remoteEntry.js',
        complianceDashboard: 'complianceDashboard@http://localhost:4202/remoteEntry.js',
        auditManagement: 'auditManagement@http://localhost:4203/remoteEntry.js',
        policyManagement: 'policyManagement@http://localhost:4204/remoteEntry.js',
        incidentReporting: 'incidentReporting@http://localhost:4205/remoteEntry.js',
        vendorRisk: 'vendorRisk@http://localhost:4206/remoteEntry.js',
        partnerOnboarding: 'partnerOnboarding@http://localhost:4207/remoteEntry.js',
      },
      shared: {
        react: { singleton: true, requiredVersion: false, eager: false },
        'react-dom': { singleton: true, requiredVersion: false, eager: false },
        'react-router-dom': { singleton: true, requiredVersion: false, eager: false },
        '@shared/types': { singleton: true, requiredVersion: false, eager: false },
        '@shared/auth': { singleton: true, requiredVersion: false, eager: false },
        '@shared/ui-components': { singleton: true, requiredVersion: false, eager: false },
        '@shared/api-client': { singleton: true, requiredVersion: false, eager: false },
        '@shared/event-bus': { singleton: true, requiredVersion: false, eager: false },
      },
    }),
    new HtmlWebpackPlugin({ template: './src/index.html', title: 'Partner Portal' }),
  ],
};
