// Generated by GitHub Copilot
/**
 * Shared Auth Library — Authentication context, hooks, and RBAC utilities.
 * Wraps MSAL for Azure AD integration; provides useAuth/usePermission hooks.
 * @module @shared/auth
 */
export { AuthProvider, useAuth } from './lib/AuthProvider';
export { ProtectedRoute } from './lib/ProtectedRoute';
export { usePermission } from './lib/usePermission';
export type { AuthContextType } from './lib/AuthProvider';
