
/**
 * Header — MUI AppBar with branding, theme toggle, notifications, and user menu.
 * @accessibility Semantic AppBar as header. All controls are keyboard-navigable with visible focus.
 * Notification count driven by event bus — reacts to cross-MFE events in real time.
 */
import React, { useState } from 'react';
import AppBar from '@mui/material/AppBar';
import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';
import IconButton from '@mui/material/IconButton';
import Box from '@mui/material/Box';
import Tooltip from '@mui/material/Tooltip';
import Badge from '@mui/material/Badge';
import Drawer from '@mui/material/Drawer';
import { useTheme, type Theme } from '@mui/material/styles';
import DarkModeIcon from '@mui/icons-material/DarkMode';
import LightModeIcon from '@mui/icons-material/LightMode';
import NotificationsIcon from '@mui/icons-material/Notifications';
import { useThemeMode, themeTokens } from '@shared/ui-components';
import { AppEvent, useEventBus } from '@shared/event-bus';


interface NotificationEntry {
  id: string;
  message: string;
  type: 'info' | 'success' | 'warning' | 'error';
  createdAt: number;
  read: boolean;
}

// Generated by GitHub Copilot
/**
 * Resolve the semantic brand color for the header logo.
 * Uses the status-brand shade (#673AB7) aligned with the icon color system.
 */
const getBrandLogoColor = (theme: Theme): string => (
  theme.palette.iconColors?.['status-brand'] ?? '#673AB7'
);



const Header: React.FC = () => {
  const { themeMode, toggleTheme } = useThemeMode();
  const theme = useTheme();
  const [notificationDrawerOpen, setNotificationDrawerOpen] = useState(false);
  const [notifications, setNotifications] = useState<NotificationEntry[]>([]);

  const unreadCount = notifications.filter((item) => !item.read).length;

  const markAllRead = () => {
    setNotifications((prev) => prev.map((item) => ({ ...item, read: true })));
  };

  const clearNotifications = () => {
    setNotifications([]);
  };

  const clearNotification = (id: string) => {
    setNotifications((prev) => prev.filter((item) => item.id !== id));
  };

  /**
   * Adds notification events to persistent in-memory history.
   * History is not cleared when opening the bell drawer.
   */
  useEventBus(AppEvent.NotificationReceived, ({ message, type }) => {
    const normalizedMessage = String(message ?? '').trim();
    if (!normalizedMessage) {
      return;
    }

    setNotifications((prev) => ([
      {
        id: `notif-${Date.now()}-${Math.random().toString(16).slice(2, 8)}`,
        message: normalizedMessage,
        type,
        createdAt: Date.now(),
        read: false,
      },
      ...prev,
    ].slice(0, 120)));
  });

  const notificationLabel = unreadCount === 0
    ? 'No new notifications'
    : `${unreadCount} unread notification${unreadCount !== 1 ? 's' : ''}`;

  const openNotificationDrawer = () => {
    setNotificationDrawerOpen(true);
    markAllRead();
  };

  return (
    <AppBar
      component="header"
      position="fixed"
      elevation={0}
      sx={{ zIndex: (theme) => theme.zIndex.drawer + 1, height: `${themeTokens.layout.headerHeight}px`, justifyContent: 'center' }}
    >
      <Toolbar sx={{ minHeight: `${themeTokens.layout.headerHeight}px !important`, px: 2 }}>
        {/* Brand */}
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.5, mr: 'auto' }}>
          {/* Accenture logo — inline SVG with theme fill for solid appearance */}
          <Box
            component="svg"
            width="21"
            height="22"
            viewBox="0 0 21 22"
            aria-hidden="true"
            sx={{ flexShrink: 0, width: 28, height: 28 }}
          >
            <path
              d="M19.368 11.0006L1 20.6086V12.9996L9 10.9996L1 8.79355V1.39355L19.368 11.0006Z"
              fill={getBrandLogoColor(theme)}
            />
          </Box>
          <Typography variant="h6" component="span" sx={{ fontWeight: 700, fontSize: '1rem', letterSpacing: '-0.01em', color: 'text.primary' }}>
            Accenture Risk &amp; Compliance
          </Typography>
        </Box>

        {/* Right Controls */}
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.5 }}>
          <Tooltip title={`Switch to ${themeMode === 'dark' ? 'light' : 'dark'} mode`}>
            <IconButton aria-label={`Switch to ${themeMode === 'dark' ? 'light' : 'dark'} mode`} onClick={toggleTheme} size="small" sx={{ color: 'text.secondary' }}>
              {themeMode === 'dark' ? <LightModeIcon fontSize="small" /> : <DarkModeIcon fontSize="small" />}
            </IconButton>
          </Tooltip>

          <Tooltip title={notificationLabel}>
            <IconButton
              aria-label={notificationLabel}
              size="small"
              sx={{ color: 'text.secondary' }}
              onClick={openNotificationDrawer}
            >
              <Badge badgeContent={unreadCount > 0 ? unreadCount : undefined} color="error" max={99}>
                <NotificationsIcon fontSize="small" />
              </Badge>
            </IconButton>
          </Tooltip>
        </Box>
      </Toolbar>

      <Drawer
        anchor="right"
        open={notificationDrawerOpen}
        onClose={() => setNotificationDrawerOpen(false)}
        sx={{
          '& .MuiDrawer-paper': {
            top: `${themeTokens.layout.headerHeight}px`,
            height: `calc(100% - ${themeTokens.layout.headerHeight}px)`,
            borderTop: '1px solid',
            borderColor: 'divider',
          },
        }}
      >
        <Box
          role="region"
          aria-label="Notification drawer"
          sx={{ width: { xs: '100vw', sm: 420 }, p: 2 }}
        >
          <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 1 }}>
            <Typography variant="h6" component="h2">Notifications</Typography>
            <Box sx={{ display: 'flex', gap: 1 }}>
              {notifications.length > 0 && (
                <button
                  type="button"
                  onClick={clearNotifications}
                  aria-label="Clear all notifications"
                  style={{
                    border: `1px solid ${theme.palette.divider}`,
                    backgroundColor: theme.palette.background.paper,
                    color: theme.palette.text.primary,
                    borderRadius: 8,
                    padding: '0.25rem 0.5rem',
                    cursor: 'pointer',
                  }}
                >
                  Clear all
                </button>
              )}
              <button
                type="button"
                onClick={() => setNotificationDrawerOpen(false)}
                aria-label="Close notifications drawer"
                style={{
                  border: `1px solid ${theme.palette.divider}`,
                  backgroundColor: theme.palette.background.paper,
                  color: theme.palette.text.primary,
                  borderRadius: 8,
                  padding: '0.25rem 0.5rem',
                  cursor: 'pointer',
                }}
              >
                Close
              </button>
            </Box>
          </Box>

          {notifications.length === 0 ? (
            <Typography variant="body2" color="text.secondary">No notifications available.</Typography>
          ) : (
            <Box component="ul" sx={{ listStyle: 'none', p: 0, m: 0, display: 'grid', gap: 1 }}>
              {notifications.map((notification) => (
                <Box
                  component="li"
                  key={notification.id}
                  sx={{ border: '1px solid', borderColor: 'divider', borderRadius: 1.5, p: 1.25, pr: 4, position: 'relative' }}
                >
                  <button
                    type="button"
                    onClick={() => clearNotification(notification.id)}
                    aria-label="Clear notification"
                    style={{
                      position: 'absolute',
                      right: 8,
                      top: 8,
                      border: 'none',
                      background: 'transparent',
                      color: theme.palette.text.secondary,
                      cursor: 'pointer',
                      fontSize: '1rem',
                      lineHeight: 1,
                    }}
                  >
                    ×
                  </button>
                  <Typography variant="body2" sx={{ mb: 0.5 }}>{notification.message}</Typography>
                  <Typography variant="caption" color="text.secondary">
                    {new Date(notification.createdAt).toLocaleString()} - {notification.type}
                  </Typography>
                </Box>
              ))}
            </Box>
          )}
        </Box>
      </Drawer>
    </AppBar>
  );
};

export default Header;
