// Generated by GitHub Copilot
/**
 * SideNav — Collapsible navigation sidebar with role-based menu filtering.
 * @accessibility Uses semantic <nav> with aria-label, aria-current for active link, keyboard navigation.
 */
import React from 'react';
import { NavLink } from 'react-router-dom';
import { useAuth } from '@shared/auth';
import { UserRole } from '@shared/types';
import type { NavItem } from '@shared/types';

// Generated by GitHub Copilot
/** Navigation items with role-based visibility */
const NAV_ITEMS: NavItem[] = [
    { key: 'risk-assessment', label: 'Risk Assessment', path: '/risk-assessment', icon: '🛡️', roles: [UserRole.Admin, UserRole.Auditor, UserRole.ComplianceOfficer, UserRole.Partner, UserRole.Viewer] },
    { key: 'compliance', label: 'Compliance', path: '/compliance', icon: '✅', roles: [UserRole.Admin, UserRole.Auditor, UserRole.ComplianceOfficer, UserRole.Partner, UserRole.Viewer] },
    { key: 'audit', label: 'Audit Management', path: '/audit', icon: '📋', roles: [UserRole.Admin, UserRole.Auditor, UserRole.ComplianceOfficer, UserRole.Viewer] },
    { key: 'policy', label: 'Policy Management', path: '/policy', icon: '📜', roles: [UserRole.Admin, UserRole.ComplianceOfficer, UserRole.Partner, UserRole.Viewer] },
    { key: 'incidents', label: 'Incident Reporting', path: '/incidents', icon: '🚨', roles: [UserRole.Admin, UserRole.ComplianceOfficer, UserRole.Partner, UserRole.Viewer] },
    { key: 'vendor-risk', label: 'Vendor Risk', path: '/vendor-risk', icon: '🏢', roles: [UserRole.Admin, UserRole.ComplianceOfficer, UserRole.Auditor, UserRole.Viewer] },
    { key: 'onboarding', label: 'Partner Onboarding', path: '/onboarding', icon: '🤝', roles: [UserRole.Admin, UserRole.Partner, UserRole.Viewer] },
];

const linkBaseStyles: React.CSSProperties = {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    padding: '0.625rem 1rem',
    borderRadius: '6px',
    textDecoration: 'none',
    fontSize: '0.875rem',
    fontWeight: 500,
    color: '#374151',
    transition: 'background-color 0.15s, color 0.15s',
};

const linkActiveStyles: React.CSSProperties = {
    backgroundColor: '#eff6ff',
    color: '#2563eb',
    fontWeight: 600,
};

const SideNav: React.FC = () => {
    const { user } = useAuth();
    const visibleItems = NAV_ITEMS.filter((item) => user && item.roles.includes(user.role));

    return (
        <nav
            aria-label="Main navigation"
            style={{
                position: 'fixed',
                top: 'var(--header-height, 56px)',
                left: 0,
                bottom: 0,
                width: 'var(--sidebar-width, 260px)',
                backgroundColor: '#ffffff',
                borderRight: '1px solid var(--color-border, #e5e7eb)',
                padding: '1rem 0.75rem',
                overflowY: 'auto',
                zIndex: 90,
            }}
        >
            <ul style={{ listStyle: 'none', margin: 0, padding: 0, display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
                {visibleItems.map((item) => (
                    <li key={item.key}>
                        <NavLink
                            to={item.path}
                            style={({ isActive }) => ({
                                ...linkBaseStyles,
                                ...(isActive ? linkActiveStyles : {}),
                            })}
                            end
                        >
                            <span aria-hidden="true" style={{ fontSize: '1.125rem', width: '1.5rem', textAlign: 'center' }}>{item.icon}</span>
                            <span>{item.label}</span>
                        </NavLink>
                    </li>
                ))}
            </ul>

            {/* Environment indicator */}
            <div
                style={{
                    position: 'absolute',
                    bottom: '1rem',
                    left: '0.75rem',
                    right: '0.75rem',
                    padding: '0.5rem 0.75rem',
                    backgroundColor: '#fef3c7',
                    borderRadius: '6px',
                    fontSize: '0.6875rem',
                    fontWeight: 600,
                    color: '#92400e',
                    textAlign: 'center',
                }}
            >
                ⚠️ DEVELOPMENT ENVIRONMENT
            </div>
        </nav>
    );
};

export default SideNav;
