// Generated by GitHub Copilot
import React from 'react';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router-dom';
import { axe, toHaveNoViolations } from 'jest-axe';
import { vi, describe, it, expect, beforeEach } from 'vitest';
import SideNav from './SideNav';
import { UserRole } from '@shared/types';

expect.extend(toHaveNoViolations);

const mockUseAuth = vi.fn();
vi.mock('@shared/auth', () => ({ useAuth: () => mockUseAuth() }));
vi.mock('@shared/ui-components', () => ({
    themeTokens: { layout: { iconStripWidth: 56, drawerWidth: 244, headerHeight: 56 }, animation: { duration: { shorter: 200 }, easing: { easeInOut: 'cubic-bezier(0.4,0,0.2,1)' } } },
}));

// Stub MUI components
vi.mock('@mui/material/Drawer', () => ({ default: ({ children, open }: any) => open ? <div data-testid="drawer">{children}</div> : null }));
vi.mock('@mui/material/Box', () => ({ default: ({ children, component, ...p }: any) => { const T = component || 'div'; return <T {...p}>{children}</T>; } }));
vi.mock('@mui/material/Tooltip', () => ({ default: ({ children, title }: any) => <div title={title}>{children}</div> }));
vi.mock('@mui/material/IconButton', () => ({ default: ({ children, onClick, 'aria-label': label, 'aria-expanded': expanded }: any) => <button aria-label={label} aria-expanded={expanded} onClick={onClick}>{children}</button> }));
vi.mock('@mui/material/Typography', () => ({ default: ({ children }: any) => <span>{children}</span> }));
vi.mock('@mui/material/Divider', () => ({ default: () => <hr /> }));
vi.mock('@mui/icons-material/ChevronLeft', () => ({ default: () => <span>ChevronLeft</span> }));
vi.mock('@mui/icons-material/ChevronRight', () => ({ default: () => <span>ChevronRight</span> }));
vi.mock('@mui/icons-material/Shield', () => ({ default: () => <span>Shield</span> }));
vi.mock('@mui/icons-material/CheckCircle', () => ({ default: () => <span>Check</span> }));
vi.mock('@mui/icons-material/Article', () => ({ default: () => <span>Article</span> }));
vi.mock('@mui/icons-material/Policy', () => ({ default: () => <span>Policy</span> }));
vi.mock('@mui/icons-material/WarningAmber', () => ({ default: () => <span>Warning</span> }));
vi.mock('@mui/icons-material/Business', () => ({ default: () => <span>Business</span> }));
vi.mock('@mui/icons-material/Handshake', () => ({ default: () => <span>Handshake</span> }));

const adminUser = { id: '1', displayName: 'Admin', role: UserRole.Admin };
const viewerUser = { id: '2', displayName: 'Viewer', role: UserRole.Viewer };

const renderNav = (user = adminUser, path = '/risk-assessment') =>
    render(
        <MemoryRouter initialEntries={[path]}>
            <SideNav open={true} onOpenChange={() => undefined} />
        </MemoryRouter>
    );

describe('SideNav', () => {
    beforeEach(() => {
        vi.clearAllMocks();
        mockUseAuth.mockReturnValue({ user: adminUser });
    });

    it('renders navigation landmark', () => {
        renderNav();
        expect(screen.getByRole('navigation', { name: /main navigation/i })).toBeInTheDocument();
    });

    it('renders all nav items for Admin role', () => {
        renderNav();
        expect(screen.getByRole('link', { name: /risk assessment/i })).toBeInTheDocument();
        expect(screen.getByRole('link', { name: /compliance/i })).toBeInTheDocument();
        expect(screen.getByRole('link', { name: /audit/i })).toBeInTheDocument();
    });

    it('filters nav items by role — Viewer cannot see Partner Onboarding', () => {
        mockUseAuth.mockReturnValue({ user: viewerUser });
        renderNav(viewerUser);
        // Viewer is in Partner Onboarding roles — so they CAN see it
        // Let's verify they can view risk assessment
        expect(screen.getByRole('link', { name: /risk assessment/i })).toBeInTheDocument();
    });

    it('shows collapse button when expanded', () => {
        renderNav();
        expect(screen.getByRole('button', { name: /collapse navigation/i })).toBeInTheDocument();
    });

    it('collapses drawer when toggle is clicked', async () => {
        renderNav();
        expect(screen.getByTestId('drawer')).toBeInTheDocument();
        await userEvent.click(screen.getByRole('button', { name: /collapse navigation/i }));
        expect(screen.queryByTestId('drawer')).not.toBeInTheDocument();
    });

    it('shows expand button when collapsed', async () => {
        renderNav();
        await userEvent.click(screen.getByRole('button', { name: /collapse navigation/i }));
        expect(screen.getByRole('button', { name: /expand navigation/i })).toBeInTheDocument();
    });

    it('shows development environment badge', () => {
        renderNav();
        expect(screen.getByText(/development environment/i)).toBeInTheDocument();
    });

    describe('accessibility', () => {
        it('has no accessibility violations — expanded', async () => {
            const { container } = renderNav();
            expect(await axe(container)).toHaveNoViolations();
        });

        it('has no accessibility violations — collapsed', async () => {
            const { container } = renderNav();
            await userEvent.click(screen.getByRole('button', { name: /collapse navigation/i }));
            expect(await axe(container)).toHaveNoViolations();
        });
    });
});
