#!/usr/bin/env bash
# Generated by GitHub Copilot
set -euo pipefail

# Only scan staged files provided by pre-commit for a narrow secret pattern.
if [ "$#" -eq 0 ]; then
  exit 0
fi

FOUND=0
for file in "$@"; do
  if [ ! -f "$file" ]; then
    continue
  fi

  if grep -nE "POSTGRES_PASSWORD=" "$file" >/dev/null 2>&1; then
    echo "[detect-secrets-basic] Potential secret detected in $file"
    grep -nE "POSTGRES_PASSWORD=" "$file" || true
    FOUND=1
  fi
done

if [ "$FOUND" -ne 0 ]; then
  echo "[detect-secrets-basic] Commit blocked. Move secrets to untracked env files or secret stores."
  exit 1
fi

exit 0
