// Generated by GitHub Copilot
import React from 'react';
import MicroAppCard from '../MicroAppCard';

/**
 * Entry card for the Compliance Dashboard micro app.
 */
const ComplianceDashboardCard: React.FC = () => (
    <MicroAppCard
        title="Compliance Dashboard"
        description="Track controls and compliance health through focused status and trend insights."
        path="/compliance"
    />
);

export default ComplianceDashboardCard;
