// Generated by GitHub Copilot
import React from 'react';
import MicroAppCard from '../MicroAppCard';

/**
 * Entry card for the Incident Reporting micro app.
 */
const IncidentReportingCard: React.FC = () => (
    <MicroAppCard
        title="Incident Reporting"
        description="Log, triage, and coordinate response activities for operational incidents."
        path="/incidents"
    />
);

export default IncidentReportingCard;
