// Generated by GitHub Copilot
import React from 'react';
import MicroAppCard from '../MicroAppCard';

/**
 * Entry card for the Policy Management micro app.
 */
const PolicyManagementCard: React.FC = () => (
    <MicroAppCard
        title="Policy Management"
        description="Create, publish, and maintain policy lifecycle and acknowledgement workflows."
        path="/policy"
    />
);

export default PolicyManagementCard;
