// Generated by GitHub Copilot
import React from 'react';
import MicroAppCard from '../MicroAppCard';

/**
 * Entry card for the Risk Assessment micro app.
 */
const RiskAssessmentCard: React.FC = () => (
    <MicroAppCard
        title="Risk Assessment"
        description="Assess partner risk posture with structured scoring, priorities, and review actions."
        path="/risk-assessment"
    />
);

export default RiskAssessmentCard;
