/**
 * AlertManagerProvider — centralized in-shell notification rendering.
 * Consumes NotificationReceived events and renders dismissible alert stack.
 */
import React, { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState } from 'react';
import Box from '@mui/material/Box';
import { AlertBanner } from '@shared/ui-components';
import { AppEvent, useEventBus } from '@shared/event-bus';

// Generated by GitHub Copilot
const MAX_VISIBLE_ALERTS = 6;
const DEFAULT_AUTO_DISMISS_MS = 6500;

export interface PortalAlert {
    id: string;
    message: string;
    type: 'info' | 'success' | 'warning' | 'error';
    createdAt: number;
}

export interface AlertManagerContextType {
    alerts: PortalAlert[];
    pushAlert: (message: string, type?: PortalAlert['type']) => void;
    dismissAlert: (id: string) => void;
    clearAlerts: () => void;
}

const AlertManagerContext = createContext<AlertManagerContextType | null>(null);

/**
 * Normalizes alert text for safe and concise UI rendering.
 */
function sanitizeAlertMessage(message: string): string {
    return String(message ?? '')
        .replace(/\s+/g, ' ')
        .trim()
        .slice(0, 280);
}

/**
 * AlertManagerProvider — subscribes to event-bus notifications and renders stack.
 */
export const AlertManagerProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [alerts, setAlerts] = useState<PortalAlert[]>([]);
    const timerMapRef = useRef<Map<string, number>>(new Map());

    const dismissAlert = useCallback((id: string) => {
        const timerId = timerMapRef.current.get(id);
        if (typeof timerId === 'number') {
            window.clearTimeout(timerId);
            timerMapRef.current.delete(id);
        }

        setAlerts((prev) => prev.filter((alert) => alert.id !== id));
    }, []);

    const clearAlerts = useCallback(() => {
        timerMapRef.current.forEach((timerId) => window.clearTimeout(timerId));
        timerMapRef.current.clear();
        setAlerts([]);
    }, []);

    const pushAlert = useCallback((message: string, type: PortalAlert['type'] = 'info') => {
        const normalized = sanitizeAlertMessage(message);
        if (!normalized) return;

        const id = `alert-${Date.now()}-${Math.random().toString(16).slice(2, 8)}`;
        const createdAt = Date.now();

        setAlerts((prev) => ([{ id, message: normalized, type, createdAt }, ...prev].slice(0, MAX_VISIBLE_ALERTS)));

        const timeoutMs = type === 'error' ? DEFAULT_AUTO_DISMISS_MS * 2 : DEFAULT_AUTO_DISMISS_MS;
        const timeoutId = window.setTimeout(() => {
            dismissAlert(id);
        }, timeoutMs);

        timerMapRef.current.set(id, timeoutId);
    }, [dismissAlert]);

    useEventBus(AppEvent.NotificationReceived, ({ message, type }) => {
        pushAlert(message, type);
    });

    useEffect(() => {
        return () => {
            timerMapRef.current.forEach((timerId) => window.clearTimeout(timerId));
            timerMapRef.current.clear();
        };
    }, []);

    const contextValue = useMemo<AlertManagerContextType>(
        () => ({ alerts, pushAlert, dismissAlert, clearAlerts }),
        [alerts, pushAlert, dismissAlert, clearAlerts],
    );

    return (
        <AlertManagerContext.Provider value={contextValue}>
            {children}
            <Box
                component="section"
                aria-label="Portal alerts"
                sx={{
                    position: 'fixed',
                    top: 72,
                    right: 16,
                    zIndex: 1700,
                    width: { xs: 'calc(100vw - 32px)', sm: 420 },
                    maxWidth: '100%',
                    pointerEvents: 'none',
                }}
            >
                {alerts.map((alert) => (
                    <Box key={alert.id} sx={{ mb: 1, pointerEvents: 'auto' }}>
                        <AlertBanner
                            type={alert.type}
                            message={alert.message}
                            onDismiss={() => dismissAlert(alert.id)}
                        />
                    </Box>
                ))}
            </Box>
        </AlertManagerContext.Provider>
    );
};

/**
 * useAlertManager — imperative API for custom shell alert flows.
 */
export function useAlertManager(): AlertManagerContextType {
    const context = useContext(AlertManagerContext);

    if (!context) {
        throw new Error('useAlertManager must be used within AlertManagerProvider');
    }

    return context;
}
