/**
 * AppProviders — canonical shell provider hierarchy.
 * Order: Auth -> Tenant -> I18n -> Alerts -> Sidebar.
 */
import React from 'react';
import { AuthProvider } from '@shared/auth';
import { TenantContextProvider } from './TenantContextProvider';
import { I18nProvider } from './I18nProvider';
import { AlertManagerProvider } from './AlertManagerProvider';
import { SidebarProvider } from './SidebarProvider';

// Generated by GitHub Copilot
export const AppProviders: React.FC<{ children: React.ReactNode }> = ({ children }) => (
    <AuthProvider>
        <TenantContextProvider>
            <I18nProvider>
                <AlertManagerProvider>
                    <SidebarProvider>
                        {children}
                    </SidebarProvider>
                </AlertManagerProvider>
            </I18nProvider>
        </TenantContextProvider>
    </AuthProvider>
);
