/**
 * I18nProvider — lightweight locale context for shell-level text rendering.
 * Keeps locale in localStorage and exposes a tiny dictionary-based translator.
 */
import React, { createContext, useCallback, useContext, useMemo, useState } from 'react';

// Generated by GitHub Copilot
const STORAGE_KEY = 'partner-portal-shell-locale';

type Dictionary = Record<string, Record<string, string>>;

const DICTIONARY: Dictionary = {
    en: {
        'shell.title': 'Accenture Risk & Compliance',
        'shell.navigation': 'Security MicroApps',
    },
};

export interface I18nContextType {
    locale: string;
    setLocale: (nextLocale: string) => void;
    t: (key: string, fallback?: string) => string;
}

const I18nContext = createContext<I18nContextType | null>(null);

/**
 * Normalizes locale strings to dictionary-compatible lowercase keys.
 */
function normalizeLocale(value: string): string {
    return value.trim().toLowerCase();
}

/**
 * Reads preferred locale from localStorage or browser settings.
 */
function readInitialLocale(): string {
    try {
        const stored = localStorage.getItem(STORAGE_KEY);
        if (stored && stored.trim() !== '') {
            return normalizeLocale(stored);
        }
    } catch {
        // Ignore storage read failures and use browser locale fallback.
    }

    if (typeof navigator !== 'undefined' && navigator.language) {
        return normalizeLocale(navigator.language.split('-')[0]);
    }

    return 'en';
}

/**
 * I18nProvider — provides locale and dictionary translation helpers.
 */
export const I18nProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [locale, setLocaleState] = useState<string>(readInitialLocale);

    const setLocale = useCallback((nextLocale: string) => {
        const normalized = normalizeLocale(nextLocale || 'en');
        setLocaleState(normalized);

        try {
            localStorage.setItem(STORAGE_KEY, normalized);
        } catch {
            // Ignore storage write failures; in-memory locale remains correct.
        }
    }, []);

    const t = useCallback(
        (key: string, fallback?: string): string => {
            const active = DICTIONARY[locale] ?? DICTIONARY.en;
            return active?.[key] ?? fallback ?? key;
        },
        [locale],
    );

    const contextValue = useMemo<I18nContextType>(
        () => ({ locale, setLocale, t }),
        [locale, setLocale, t],
    );

    return (
        <I18nContext.Provider value={contextValue}>
            {children}
        </I18nContext.Provider>
    );
};

/**
 * useI18n — access shell locale and translation helper.
 */
export function useI18n(): I18nContextType {
    const context = useContext(I18nContext);

    if (!context) {
        throw new Error('useI18n must be used within I18nProvider');
    }

    return context;
}
