/**
 * SidebarProvider — shared sidebar open/collapse state for shell layout.
 * Persists state in localStorage so user preference survives reloads.
 */
import React, { createContext, useCallback, useContext, useMemo, useState } from 'react';

// Generated by GitHub Copilot
const STORAGE_KEY = 'partner-portal-shell-sidebar-open';

export interface SidebarContextType {
    open: boolean;
    setOpen: (nextOpen: boolean) => void;
    toggle: () => void;
}

const SidebarContext = createContext<SidebarContextType | null>(null);

/**
 * Reads persisted sidebar state from localStorage.
 * Defaults to expanded sidebar when no value is stored.
 */
function readPersistedSidebarState(): boolean {
    try {
        const raw = localStorage.getItem(STORAGE_KEY);
        if (raw === 'true') return true;
        if (raw === 'false') return false;
    } catch {
        // Ignore storage access failures and keep default state.
    }

    return true;
}

/**
 * SidebarProvider — keeps shell navigation collapsed/expanded state globally.
 */
export const SidebarProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [open, setOpenState] = useState<boolean>(readPersistedSidebarState);

    const setOpen = useCallback((nextOpen: boolean) => {
        setOpenState(nextOpen);

        try {
            localStorage.setItem(STORAGE_KEY, String(nextOpen));
        } catch {
            // Ignore storage write failures; in-memory state remains correct.
        }
    }, []);

    const toggle = useCallback(() => {
        setOpenState((prev) => {
            const nextOpen = !prev;

            try {
                localStorage.setItem(STORAGE_KEY, String(nextOpen));
            } catch {
                // Ignore storage write failures; in-memory state remains correct.
            }

            return nextOpen;
        });
    }, []);

    const contextValue = useMemo<SidebarContextType>(
        () => ({ open, setOpen, toggle }),
        [open, setOpen, toggle],
    );

    return (
        <SidebarContext.Provider value={contextValue}>
            {children}
        </SidebarContext.Provider>
    );
};

/**
 * useSidebar — access sidebar state from anywhere in shell tree.
 */
export function useSidebar(): SidebarContextType {
    const context = useContext(SidebarContext);

    if (!context) {
        throw new Error('useSidebar must be used within SidebarProvider');
    }

    return context;
}
