/**
 * TenantContextProvider — shell-level tenant/user context and feature flags.
 * Synchronizes tenant metadata to api-client runtime headers.
 */
import React, { createContext, useContext, useEffect, useMemo } from 'react';
import { useAuth } from '@shared/auth';
import { setApiRuntimeContext } from '@shared/api-client';

// Generated by GitHub Copilot
const DEFAULT_TENANT_ID = 'tenant-archaic-search-demo';

export interface TenantContextType {
    tenantId: string;
    userId: string | null;
    featureFlags: string[];
}

const TenantContext = createContext<TenantContextType | null>(null);

/**
 * Reads first non-empty env value from compatible key aliases.
 */
function readEnvValue(keys: string[], fallback = ''): string {
    const env = (typeof process !== 'undefined' && process.env
        ? (process.env as Record<string, string | undefined>)
        : {}) as Record<string, string | undefined>;

    for (const key of keys) {
        const value = env[key];
        if (typeof value === 'string' && value.trim() !== '') {
            return value.trim();
        }
    }

    return fallback;
}

/**
 * Parses comma-separated feature flag env values into a unique list.
 */
function readFeatureFlags(): string[] {
    const raw = readEnvValue(['FEATURE_FLAGS', 'VITE_FEATURE_FLAGS'], '');
    if (!raw) return [];

    return Array.from(new Set(
        raw
            .split(',')
            .map((flag) => flag.trim())
            .filter((flag) => flag.length > 0),
    ));
}

/**
 * TenantContextProvider — publishes tenant metadata and syncs API runtime context.
 */
export const TenantContextProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const { user } = useAuth();

    const tenantId = readEnvValue(['TENANT_ID', 'VITE_TENANT_ID'], DEFAULT_TENANT_ID);
    const featureFlags = useMemo(readFeatureFlags, []);
    const userId = user?.id ?? null;

    const contextValue = useMemo<TenantContextType>(
        () => ({ tenantId, userId, featureFlags }),
        [tenantId, userId, featureFlags],
    );

    useEffect(() => {
        setApiRuntimeContext({ tenantId, userId, featureFlags });

        try {
            sessionStorage.setItem('tenant_id', tenantId);
        } catch {
            // Ignore storage write failures; runtime context already propagated.
        }

        (window as unknown as Record<string, unknown>).__PARTNER_PORTAL_CONTEXT__ = {
            tenantId,
            userId,
            featureFlags,
        };
    }, [tenantId, userId, featureFlags]);

    return (
        <TenantContext.Provider value={contextValue}>
            {children}
        </TenantContext.Provider>
    );
};

/**
 * useTenantContext — access tenant/user metadata in shell components.
 */
export function useTenantContext(): TenantContextType {
    const context = useContext(TenantContext);

    if (!context) {
        throw new Error('useTenantContext must be used within TenantContextProvider');
    }

    return context;
}
