// Generated by GitHub Copilot
import { config, allowedBulkPresets } from './config.js';
import { generateDataset } from './templates.js';
import { ALL_DOMAINS } from './domains.js';
import {
    countDomainRecords,
    ensureSchema,
    isRepositoryEmpty,
    replaceManyDomains,
} from './repository.js';

/**
 * Ensures preset values are constrained to allowed list.
 */
function resolvePreset(preset) {
    if (allowedBulkPresets.includes(preset)) {
        return preset;
    }
    return 'small';
}

/**
 * Seeds all domains with deterministic dataset for the requested preset.
 */
export async function seedDomains({ preset = 'small', seed = config.defaultBulkSeed } = {}) {
    const resolvedPreset = resolvePreset(preset);

    const generated = generateDataset({
        preset: resolvedPreset,
        seed,
        maxRecordsPerDomain: config.maxRecordsPerDomain,
        domains: ALL_DOMAINS,
    });

    await replaceManyDomains(generated.dataset);
    return generated.meta;
}

/**
 * Initializes schema and optionally seeds an empty database.
 */
export async function initializeBackend() {
    await ensureSchema();

    const seeded = {
        didSeed: false,
        preset: null,
        seed: null,
    };

    if (config.autoSeed) {
        const empty = await isRepositoryEmpty();
        if (empty) {
            const meta = await seedDomains({
                preset: config.autoSeedPreset,
                seed: config.defaultBulkSeed,
            });
            seeded.didSeed = true;
            seeded.preset = meta.preset;
            seeded.seed = meta.seed;
        }
    }

    const countsByDomain = {};
    for (const domain of ALL_DOMAINS) {
        countsByDomain[domain] = await countDomainRecords(domain);
    }

    return {
        seeded,
        countsByDomain,
    };
}
