// Generated by GitHub Copilot
import dotenv from 'dotenv';

dotenv.config();

const BULK_PRESETS = ['small', '10k', '100k', '600k', '1m', '2m'];

/**
 * Parses integer environment values with bounded fallback.
 */
function parseInteger(rawValue, fallback, min = Number.MIN_SAFE_INTEGER, max = Number.MAX_SAFE_INTEGER) {
    if (typeof rawValue !== 'string' || rawValue.trim() === '') {
        return fallback;
    }

    const parsed = Number.parseInt(rawValue, 10);
    if (Number.isNaN(parsed)) {
        return fallback;
    }

    return Math.max(min, Math.min(max, parsed));
}

/**
 * Parses boolean environment values with robust defaults.
 */
function parseBoolean(rawValue, fallback) {
    if (typeof rawValue !== 'string') {
        return fallback;
    }

    const normalized = rawValue.trim().toLowerCase();
    if (normalized === 'true') {
        return true;
    }

    if (normalized === 'false') {
        return false;
    }

    return fallback;
}

/**
 * Ensures requested preset belongs to the allowed bulk presets.
 */
function parseBulkPreset(rawValue, fallback) {
    if (typeof rawValue !== 'string') {
        return fallback;
    }

    const normalized = rawValue.trim().toLowerCase();
    if (BULK_PRESETS.includes(normalized)) {
        return normalized;
    }

    return fallback;
}

/**
 * Parses comma-separated CORS origins.
 */
function parseCorsOrigins(rawValue) {
    if (typeof rawValue !== 'string' || rawValue.trim() === '') {
        return ['http://localhost:4200'];
    }

    return rawValue
        .split(',')
        .map((origin) => origin.trim())
        .filter((origin) => origin.length > 0);
}

export const config = {
    port: parseInteger(process.env.PORT, 5000, 1, 65535),
    databaseUrl: process.env.DATABASE_URL ?? 'postgres://partner_portal:partner_portal_dev@db:5432/partner_portal',
    corsOrigins: parseCorsOrigins(process.env.CORS_ORIGIN),
    autoSeed: parseBoolean(process.env.AUTO_SEED, true),
    autoSeedPreset: parseBulkPreset(process.env.AUTO_SEED_PRESET, 'small'),
    realtimeEnabled: parseBoolean(process.env.ENABLE_REALTIME_SIMULATOR, true),
    realtimeTickMs: parseInteger(process.env.REALTIME_TICK_MS, 12_000, 1_000, 120_000),
    maxRecordsPerDomain: parseInteger(process.env.MAX_RECORDS_PER_DOMAIN, 100_000, 100, 2_000_000),
    defaultBulkPreset: parseBulkPreset(process.env.BULK_LOAD_PRESET, '10k'),
    defaultBulkSeed: parseInteger(process.env.BULK_LOAD_SEED, 42, 1, 999_999),
};

export const allowedBulkPresets = Object.freeze(BULK_PRESETS);
