// Generated by GitHub Copilot

export const ALL_DOMAINS = Object.freeze([
    'risks',
    'frameworks',
    'controls',
    'audits',
    'findings',
    'policies',
    'incidents',
    'vendors',
    'partners',
]);

export const MUTABLE_DOMAINS = Object.freeze([
    'risks',
    'controls',
    'audits',
    'findings',
    'policies',
    'incidents',
    'vendors',
    'partners',
]);

export const DOMAIN_ID_PREFIX = Object.freeze({
    risks: 'RSK',
    frameworks: 'FW',
    controls: 'CTL',
    audits: 'AUD',
    findings: 'FND',
    policies: 'POL',
    incidents: 'INC',
    vendors: 'VND',
    partners: 'PTR',
});

/**
 * True when requested domain belongs to the supported API set.
 */
export function isSupportedDomain(domain) {
    return ALL_DOMAINS.includes(domain);
}

/**
 * Builds deterministic IDs using domain prefix and 6-digit counter.
 */
export function buildId(prefix, index) {
    return `${prefix}-${String(index + 1).padStart(6, '0')}`;
}
