// Generated by GitHub Copilot
import { pool } from './db.js';
import { ALL_DOMAINS, isSupportedDomain } from './domains.js';

const UPSERT_SQL = `
INSERT INTO domain_records (domain, id, payload, created_at, updated_at)
VALUES ($1, $2, $3::jsonb, NOW(), NOW())
ON CONFLICT (domain, id)
DO UPDATE SET
    payload = EXCLUDED.payload,
    updated_at = NOW();
`;

const BATCH_UPSERT_SQL = `
INSERT INTO domain_records (domain, id, payload, created_at, updated_at)
SELECT $1, data.id, data.payload::jsonb, NOW(), NOW()
FROM unnest($2::text[], $3::text[]) AS data(id, payload)
ON CONFLICT (domain, id)
DO UPDATE SET
    payload = EXCLUDED.payload,
    updated_at = NOW();
`;

/**
 * Creates storage schema used by all domain resources.
 */
export async function ensureSchema() {
    await pool.query(`
        CREATE TABLE IF NOT EXISTS domain_records (
            domain TEXT NOT NULL,
            id TEXT NOT NULL,
            payload JSONB NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            PRIMARY KEY (domain, id)
        );
    `);

    await pool.query('CREATE INDEX IF NOT EXISTS idx_domain_records_domain ON domain_records (domain);');
    await pool.query('CREATE INDEX IF NOT EXISTS idx_domain_records_updated_at ON domain_records (updated_at DESC);');
}

/**
 * Replaces all records for one domain with provided records.
 */
export async function replaceDomainRecords(domain, records) {
    if (!isSupportedDomain(domain)) {
        throw new Error(`Unsupported domain: ${domain}`);
    }

    const client = await pool.connect();
    try {
        await client.query('BEGIN');
        await client.query('DELETE FROM domain_records WHERE domain = $1', [domain]);

        await batchUpsertRecords(client, domain, records);

        await client.query('COMMIT');
    } catch (error) {
        await client.query('ROLLBACK');
        throw error;
    } finally {
        client.release();
    }
}

/**
 * Replaces selected domains with generated records.
 */
export async function replaceManyDomains(datasetByDomain) {
    for (const [domain, records] of Object.entries(datasetByDomain)) {
        await replaceDomainRecords(domain, records);
    }
}

/**
 * Upserts selected domains without deleting existing records first.
 */
export async function upsertManyDomains(datasetByDomain) {
    const client = await pool.connect();
    try {
        await client.query('BEGIN');

        for (const [domain, records] of Object.entries(datasetByDomain)) {
            if (!isSupportedDomain(domain)) {
                throw new Error(`Unsupported domain: ${domain}`);
            }

            await batchUpsertRecords(client, domain, records);
        }

        await client.query('COMMIT');
    } catch (error) {
        await client.query('ROLLBACK');
        throw error;
    } finally {
        client.release();
    }
}

/**
 * Returns domain records using deterministic sort and pagination options.
 */
export async function listDomainRecords(domain, { limit = 5_000, offset = 0 } = {}) {
    if (!isSupportedDomain(domain)) {
        throw new Error(`Unsupported domain: ${domain}`);
    }

    const result = await pool.query(
        `
        SELECT payload
        FROM domain_records
        WHERE domain = $1
        ORDER BY id ASC
        LIMIT $2 OFFSET $3
        `,
        [domain, limit, offset],
    );

    return result.rows.map((row) => row.payload);
}

/**
 * Returns total count for a domain.
 */
export async function countDomainRecords(domain) {
    if (!isSupportedDomain(domain)) {
        throw new Error(`Unsupported domain: ${domain}`);
    }

    const result = await pool.query(
        'SELECT COUNT(*)::int AS count FROM domain_records WHERE domain = $1',
        [domain],
    );

    return result.rows[0]?.count ?? 0;
}

/**
 * Returns true when no records exist in any domain.
 */
export async function isRepositoryEmpty() {
    const result = await pool.query('SELECT COUNT(*)::int AS count FROM domain_records');
    return (result.rows[0]?.count ?? 0) === 0;
}

/**
 * Inserts or updates one domain record.
 */
export async function upsertDomainRecord(domain, id, payload) {
    if (!isSupportedDomain(domain)) {
        throw new Error(`Unsupported domain: ${domain}`);
    }

    await pool.query(UPSERT_SQL, [domain, id, JSON.stringify(payload)]);
    return payload;
}

/**
 * Reads one domain record by ID.
 */
export async function getDomainRecord(domain, id) {
    if (!isSupportedDomain(domain)) {
        throw new Error(`Unsupported domain: ${domain}`);
    }

    const result = await pool.query(
        'SELECT payload FROM domain_records WHERE domain = $1 AND id = $2 LIMIT 1',
        [domain, id],
    );

    return result.rows[0]?.payload ?? null;
}

/**
 * Patches one domain record and persists the merged payload.
 */
export async function patchDomainRecord(domain, id, partialPayload) {
    const current = await getDomainRecord(domain, id);
    if (!current) {
        return null;
    }

    const merged = {
        ...current,
        ...partialPayload,
        id,
    };

    await upsertDomainRecord(domain, id, merged);
    return merged;
}

/**
 * Deletes one domain record by ID and returns deleted payload.
 */
export async function deleteDomainRecord(domain, id) {
    if (!isSupportedDomain(domain)) {
        throw new Error(`Unsupported domain: ${domain}`);
    }

    const result = await pool.query(
        'DELETE FROM domain_records WHERE domain = $1 AND id = $2 RETURNING payload',
        [domain, id],
    );

    return result.rows[0]?.payload ?? null;
}

/**
 * Returns one random record from a domain for realtime simulation.
 */
export async function getRandomDomainRecord(domain) {
    if (!isSupportedDomain(domain)) {
        throw new Error(`Unsupported domain: ${domain}`);
    }

    const result = await pool.query(
        `
        SELECT payload
        FROM domain_records
        WHERE domain = $1
        ORDER BY RANDOM()
        LIMIT 1
        `,
        [domain],
    );

    return result.rows[0]?.payload ?? null;
}

/**
 * Truncates all supported domains.
 */
export async function truncateAllDomains() {
    await pool.query('DELETE FROM domain_records WHERE domain = ANY($1::text[])', [ALL_DOMAINS]);
}

/**
 * Performs batched upserts for records in a single domain.
 */
async function batchUpsertRecords(client, domain, records) {
    const batchSize = 500;

    for (let index = 0; index < records.length; index += batchSize) {
        const batch = records.slice(index, index + batchSize);
        const ids = batch.map((record) => String(record.id));
        const payloads = batch.map((record) => JSON.stringify(record));

        await client.query(BATCH_UPSERT_SQL, [domain, ids, payloads]);
    }
}
