// Generated by GitHub Copilot
import request from 'supertest';
import { beforeEach, describe, expect, it, vi } from 'vitest';

const deleteDomainRecordMock = vi.fn();
const broadcastEventMock = vi.fn();

vi.mock('./repository.js', () => ({
    countDomainRecords: vi.fn(),
    deleteDomainRecord: deleteDomainRecordMock,
    getDomainRecord: vi.fn(),
    listDomainRecords: vi.fn(),
    patchDomainRecord: vi.fn(),
    replaceManyDomains: vi.fn(),
    truncateAllDomains: vi.fn(),
    upsertDomainRecord: vi.fn(),
    upsertManyDomains: vi.fn(),
}));

vi.mock('./sseBroker.js', () => ({
    broadcastEvent: broadcastEventMock,
    emitKeepalive: vi.fn(),
    getConnectedClientCount: vi.fn(() => 0),
    subscribeToEvents: vi.fn(() => () => undefined),
}));

process.env.NODE_ENV = 'test';

/**
 * Imports a fresh server module so each test gets clean route state and mocks.
 */
async function loadServerApp() {
    vi.resetModules();
    const module = await import('./server.js');
    return module.app;
}

describe('DELETE /api/:domain/:id', () => {
    beforeEach(() => {
        vi.clearAllMocks();
    });

    it('returns 204 and emits domain.deleted for mutable domains', async () => {
        const app = await loadServerApp();
        deleteDomainRecordMock.mockResolvedValueOnce({ id: 'INC-001' });

        const response = await request(app).delete('/api/incidents/INC-001');

        expect(response.status).toBe(204);
        expect(deleteDomainRecordMock).toHaveBeenCalledWith('incidents', 'INC-001');
        expect(broadcastEventMock).toHaveBeenCalledWith('domain.deleted', {
            domain: 'incidents',
            id: 'INC-001',
            source: 'api',
        });
    });

    it('returns 404 when the record does not exist', async () => {
        const app = await loadServerApp();
        deleteDomainRecordMock.mockResolvedValueOnce(null);

        const response = await request(app).delete('/api/incidents/INC-404');

        expect(response.status).toBe(404);
        expect(response.body).toEqual({
            message: 'incidents record not found',
            id: 'INC-404',
        });
        expect(broadcastEventMock).not.toHaveBeenCalled();
    });

    it('returns 405 for read-only domains and skips repository deletion', async () => {
        const app = await loadServerApp();

        const response = await request(app).delete('/api/frameworks/FW-001');

        expect(response.status).toBe(405);
        expect(response.body).toEqual({
            message: 'frameworks is read-only in this API',
        });
        expect(deleteDomainRecordMock).not.toHaveBeenCalled();
        expect(broadcastEventMock).not.toHaveBeenCalled();
    });
});
