// Generated by GitHub Copilot

const sseClients = new Map();
let nextClientId = 1;

/**
 * Sends one SSE event payload to a specific response stream.
 */
function writeEvent(response, eventType, payload) {
    const message = [
        `event: ${eventType}`,
        `data: ${JSON.stringify(payload)}`,
        '',
    ].join('\n');

    response.write(`${message}\n`);
}

/**
 * Registers a client connection and returns an unsubscribe callback.
 */
export function subscribeToEvents(response) {
    const clientId = String(nextClientId);
    nextClientId += 1;

    sseClients.set(clientId, response);
    writeEvent(response, 'connected', {
        clientId,
        connectedAt: new Date().toISOString(),
    });

    return () => {
        sseClients.delete(clientId);
    };
}

/**
 * Broadcasts one event to every active SSE client.
 */
export function broadcastEvent(eventType, payload) {
    const eventPayload = {
        ...payload,
        emittedAt: new Date().toISOString(),
    };

    for (const [clientId, response] of sseClients.entries()) {
        try {
            writeEvent(response, eventType, eventPayload);
        } catch {
            sseClients.delete(clientId);
        }
    }
}

/**
 * Emits keepalive comments to keep idle proxies from closing streams.
 */
export function emitKeepalive() {
    for (const [clientId, response] of sseClients.entries()) {
        try {
            response.write(': keepalive\n\n');
        } catch {
            sseClients.delete(clientId);
        }
    }
}

/**
 * Returns current number of connected SSE clients.
 */
export function getConnectedClientCount() {
    return sseClients.size;
}
