
import React from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import { AuthProvider } from '@shared/auth';
import { PortalThemeProvider } from '@shared/ui-components';
import IncidentReportingApp from './remote-entry';

const root = createRoot(document.getElementById('root')!);
// Generated by GitHub Copilot
root.render(
	<React.StrictMode>
		<PortalThemeProvider>
			<BrowserRouter>
				<AuthProvider>
					<IncidentReportingApp />
				</AuthProvider>
			</BrowserRouter>
		</PortalThemeProvider>
	</React.StrictMode>
);
