// Generated by GitHub Copilot
/**
 * Incident Reporting — Remote entry point.
 * Provides incident submission, tracking, timeline, and escalation UI.
 */
import React, { useState } from 'react';
import { mockData } from '@shared/api-client';
import { usePermission } from '@shared/auth';
import { PageHeader, Card, StatCard, DataTable, StatusBadge, Button, FormField, Modal } from '@shared/ui-components';
import type { Incident } from '@shared/types';
import type { Column } from '@shared/ui-components';

const IncidentReportingApp: React.FC = () => {
  const [showForm, setShowForm] = useState(false);
  const [formData, setFormData] = useState({ title: '', description: '', severity: '', category: '', affectedSystems: '' });
  const canReport = usePermission('report', 'incident');

  const columns: Column<Incident>[] = [
    { key: 'id', header: 'ID', sortable: true, width: '90px' },
    { key: 'title', header: 'Incident', sortable: true },
    { key: 'severity', header: 'Severity', sortable: true, width: '110px', render: (r: Incident) => <StatusBadge status={r.severity} /> },
    { key: 'status', header: 'Status', sortable: true, width: '130px', render: (r: Incident) => <StatusBadge status={r.status} /> },
    { key: 'category', header: 'Category', sortable: true, width: '140px' },
    { key: 'assignee', header: 'Assignee', sortable: true, width: '130px' },
    { key: 'reportedAt', header: 'Reported', sortable: true, width: '160px', render: (r: Incident) => <span>{new Date(r.reportedAt).toLocaleDateString()}</span> },
  ];

  const stats = {
    total: mockData.incidents.length,
    open: mockData.incidents.filter((i: Incident) => i.status === 'open' || i.status === 'investigating').length,
    critical: mockData.incidents.filter((i: Incident) => i.severity === 'critical').length,
    resolved: mockData.incidents.filter((i: Incident) => i.status === 'resolved' || i.status === 'closed').length,
  };

  const handleField = (field: string) => (value: string) => setFormData((prev) => ({ ...prev, [field]: value }));

  return (
    <section aria-label="Incident Reporting">
      <PageHeader
        title="Incident Reporting"
        subtitle="Report, track, and respond to security incidents"
        actions={canReport ? <Button onClick={() => setShowForm(true)}>🚨 Report Incident</Button> : undefined}
      />

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '1rem', marginBottom: '1.5rem' }}>
        <StatCard label="Total Incidents" value={stats.total} icon="📊" />
        <StatCard label="Active" value={stats.open} icon="🔴" changeType="negative" change="Requires attention" />
        <StatCard label="Critical" value={stats.critical} icon="🚨" changeType="negative" />
        <StatCard label="Resolved" value={stats.resolved} icon="✅" changeType="positive" />
      </div>

      {/* Incident Timeline */}
      <Card title="Recent Activity Timeline" style={{ marginBottom: '1.5rem' }}>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem', paddingLeft: '1.5rem', borderLeft: '2px solid var(--color-border)' }}>
          {mockData.incidents.map((inc: Incident) => (
            <div key={inc.id} style={{ position: 'relative', paddingLeft: '1rem' }}>
              <div style={{
                position: 'absolute', left: '-1.75rem', top: '0.25rem',
                width: 12, height: 12, borderRadius: '50%',
                backgroundColor: inc.severity === 'critical' ? '#dc2626' : inc.severity === 'high' ? '#f59e0b' : '#3b82f6',
                border: '2px solid #fff',
              }} />
              <div style={{ fontSize: '0.8125rem', fontWeight: 600 }}>{inc.title}</div>
              <div style={{ fontSize: '0.75rem', color: 'var(--color-text-secondary)' }}>
                {new Date(inc.reportedAt).toLocaleString()} · <StatusBadge status={inc.status} /> · {inc.assignee}
              </div>
            </div>
          ))}
        </div>
      </Card>

      <Card title="Incident Register">
        <DataTable columns={columns} data={mockData.incidents} rowKey="id" />
      </Card>

      {/* Report Incident Modal */}
      <Modal isOpen={showForm} onClose={() => setShowForm(false)} title="Report New Incident" size="lg">
        <form onSubmit={(e) => { e.preventDefault(); alert('Incident submitted!'); setShowForm(false); }}>
          <FormField label="Incident Title" name="title" value={formData.title} onChange={handleField('title')} required placeholder="Brief description of the incident" />
          <FormField label="Description" name="description" type="textarea" value={formData.description} onChange={handleField('description')} required placeholder="Detailed description..." />
          <FormField label="Severity" name="severity" type="select" value={formData.severity} onChange={handleField('severity')} required options={[
            { value: 'low', label: 'Low' }, { value: 'medium', label: 'Medium' }, { value: 'high', label: 'High' }, { value: 'critical', label: 'Critical' },
          ]} />
          <FormField label="Category" name="category" type="select" value={formData.category} onChange={handleField('category')} required options={[
            { value: 'phishing', label: 'Phishing' }, { value: 'data-exfiltration', label: 'Data Exfiltration' }, { value: 'malware', label: 'Malware' }, { value: 'configuration', label: 'Configuration' }, { value: 'other', label: 'Other' },
          ]} />
          <FormField label="Affected Systems" name="affectedSystems" value={formData.affectedSystems} onChange={handleField('affectedSystems')} placeholder="Comma-separated list" />
          <div style={{ display: 'flex', gap: '0.75rem', justifyContent: 'flex-end', marginTop: '1rem' }}>
            <Button variant="secondary" type="button" onClick={() => setShowForm(false)}>Cancel</Button>
            <Button type="submit">Submit Incident</Button>
          </div>
        </form>
      </Modal>
    </section>
  );
};

export default IncidentReportingApp;
