// Generated by GitHub Copilot
const { createRemoteWebpackConfig } = require('../../tools/webpack/remoteConfig');
module.exports = createRemoteWebpackConfig({ name: 'riskAssessment', port: 4201, appDir: __dirname });
