// Generated by GitHub Copilot
import React from 'react';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { axe, toHaveNoViolations } from 'jest-axe';
import { vi, describe, it, expect, beforeEach } from 'vitest';
import { Button } from './Button';

expect.extend(toHaveNoViolations);

vi.mock('@mui/material/Button', () => ({
    default: ({ children, disabled, onClick, type, 'aria-label': ariaLabel, 'aria-busy': ariaBusy, startIcon, ...props }: any) => (
        <button disabled={disabled} onClick={onClick} type={type} aria-label={ariaLabel} aria-busy={ariaBusy} {...props}>
            {startIcon}{children}
        </button>
    ),
}));
vi.mock('@mui/material/CircularProgress', () => ({
    default: ({ size }: any) => <span data-testid="spinner" data-size={size} />,
}));

describe('Button', () => {
    beforeEach(() => { vi.clearAllMocks(); });

    describe('rendering', () => {
        it('renders children', () => {
            render(<Button>Click me</Button>);
            expect(screen.getByRole('button', { name: 'Click me' })).toBeInTheDocument();
        });

        it('renders with aria-label when no visible text', () => {
            render(<Button aria-label="Submit form">→</Button>);
            expect(screen.getByRole('button', { name: 'Submit form' })).toBeInTheDocument();
        });

        it('is not disabled by default', () => {
            render(<Button>Go</Button>);
            expect(screen.getByRole('button')).not.toBeDisabled();
        });
    });

    describe('disabled state', () => {
        it('is disabled when disabled prop is true', () => {
            render(<Button disabled>Disabled</Button>);
            expect(screen.getByRole('button')).toBeDisabled();
        });

        it('is disabled and shows spinner when loading', () => {
            render(<Button loading>Saving</Button>);
            const btn = screen.getByRole('button');
            expect(btn).toBeDisabled();
            expect(btn).toHaveAttribute('aria-busy', 'true');
            expect(screen.getByTestId('spinner')).toBeInTheDocument();
        });
    });

    describe('interaction', () => {
        it('calls onClick when clicked', async () => {
            const handleClick = vi.fn();
            render(<Button onClick={handleClick}>Click</Button>);
            await userEvent.click(screen.getByRole('button'));
            expect(handleClick).toHaveBeenCalledTimes(1);
        });

        it('does not call onClick when disabled', async () => {
            const handleClick = vi.fn();
            render(<Button disabled onClick={handleClick}>Disabled</Button>);
            const btn = screen.getByRole('button');
            expect(btn).toBeDisabled();
            // Do not click a disabled button per testing rules
        });
    });

    describe('accessibility', () => {
        it('has no accessibility violations — primary variant', async () => {
            const { container } = render(<Button>Submit</Button>);
            expect(await axe(container)).toHaveNoViolations();
        });

        it('has no accessibility violations — loading state', async () => {
            const { container } = render(<Button loading>Saving</Button>);
            expect(await axe(container)).toHaveNoViolations();
        });
    });
});
