// Generated by GitHub Copilot
/**
 * Card — Container component for content sections.
 * @accessibility Uses semantic article element with proper heading hierarchy.
 */
import React from 'react';

interface CardProps {
    title?: string;
    children: React.ReactNode;
    className?: string;
    style?: React.CSSProperties;
}

export const Card: React.FC<CardProps> = ({ title, children, className = '', style }) => {
    const cardStyles: React.CSSProperties = {
        backgroundColor: 'var(--color-surface, #ffffff)',
        borderRadius: '8px',
        border: '1px solid var(--color-border, #e5e7eb)',
        padding: '1.5rem',
        boxShadow: '0 1px 3px rgba(0,0,0,0.08)',
        ...style,
    };

    return (
        <article className={`pp-card ${className}`} style={cardStyles}>
            {title && (
                <h3 style={{ margin: '0 0 1rem 0', fontSize: '1.125rem', fontWeight: 600, color: 'var(--color-text, #1f2937)' }}>
                    {title}
                </h3>
            )}
            {children}
        </article>
    );
};
