
/**
 * DataTable — Accessible data table with sorting and row selection.
 * @accessibility Uses semantic <table> with proper th scope, aria-sort, and keyboard navigation.
 */
import React, { useEffect, useId, useMemo, useRef, useState } from 'react';
import { useTheme, alpha } from '@mui/material/styles';
import FilterListIcon from '@mui/icons-material/FilterList';
import ViewColumnIcon from '@mui/icons-material/ViewColumn';
import DownloadIcon from '@mui/icons-material/Download';
import PushPinIcon from '@mui/icons-material/PushPin';
import PushPinOutlinedIcon from '@mui/icons-material/PushPinOutlined';
import DragIndicatorIcon from '@mui/icons-material/DragIndicator';
import Skeleton from '@mui/material/Skeleton';
import { PREFS_STORAGE_PREFIX } from './useUserPreferences';

export interface Column<T> {
    key: string;
    header: string;
    render?: (row: T) => React.ReactNode;
    sortable?: boolean;
    width?: string;
}

interface DataTableProps<T> {
    columns: Column<T>[];
    data: T[];
    rowKey: keyof T;
    selectable?: boolean;
    selectedRows?: Set<string>;
    onSelectionChange?: (selected: Set<string>) => void;
    emptyMessage?: string;
    preferenceKey?: string;
    loading?: boolean;
    skeletonRowCount?: number;
    pagination?: boolean;
    defaultPageSize?: number;
    pageSizeOptions?: number[];
    enableHeaderActions?: boolean;
}

interface PersistedTablePreferences {
    sortColumn: string | null;
    sortDir: 'asc' | 'desc';
    pageSize: number;
    searchTerm: string;
    columnFilters: Record<string, string>;
    showFilterPanel: boolean;
    hiddenColumns: string[];
    columnOrder: string[];
    pinnedColumns: string[];
}

// Generated by GitHub Copilot
const DEFAULT_PAGE_SIZE = 10;
const DEFAULT_PAGE_SIZE_OPTIONS = [10, 25, 50, 100];

function sanitizeColumnFilters(input: unknown): Record<string, string> {
    if (!input || typeof input !== 'object') {
        return {};
    }

    const parsed = input as Record<string, unknown>;
    const next: Record<string, string> = {};
    Object.keys(parsed).forEach((key) => {
        const value = parsed[key];
        if (typeof value === 'string') {
            next[key] = value;
        }
    });

    return next;
}

// Generated by GitHub Copilot
function sanitizeStringArray(input: unknown): string[] {
    if (!Array.isArray(input)) {
        return [];
    }

    return input.filter((value): value is string => typeof value === 'string');
}

// Generated by GitHub Copilot
function normalizeColumnOrder(candidate: string[], available: string[]): string[] {
    const seen = new Set<string>();
    const ordered = candidate.filter((key) => {
        if (!available.includes(key) || seen.has(key)) {
            return false;
        }
        seen.add(key);
        return true;
    });

    available.forEach((key) => {
        if (!seen.has(key)) {
            ordered.push(key);
        }
    });

    return ordered;
}

// Generated by GitHub Copilot
function normalizePinnedColumns(candidate: string[], available: string[]): string[] {
    const availableSet = new Set(available);
    const seen = new Set<string>();
    return candidate.filter((key) => {
        if (!availableSet.has(key) || seen.has(key)) {
            return false;
        }
        seen.add(key);
        return true;
    });
}

// Generated by GitHub Copilot
function normalizeHiddenColumns(candidate: string[], available: string[], pinnedColumns: string[] = []): string[] {
    const availableSet = new Set(available);
    const pinnedSet = new Set(pinnedColumns);
    const seen = new Set<string>();
    const normalized = candidate.filter((key) => {
        if (!availableSet.has(key) || pinnedSet.has(key) || seen.has(key)) {
            return false;
        }
        seen.add(key);
        return true;
    });

    if (available.length > 0 && normalized.length >= available.length) {
        return normalized.slice(0, available.length - 1);
    }

    return normalized;
}

// Generated by GitHub Copilot
function removeDisallowedFilterKeys(filters: Record<string, string>, allowedKeys: Set<string>): Record<string, string> {
    let changed = false;
    const next: Record<string, string> = {};

    Object.entries(filters).forEach(([key, value]) => {
        if (allowedKeys.has(key)) {
            next[key] = value;
        } else {
            changed = true;
        }
    });

    return changed ? next : filters;
}

function normalizePageSize(candidate: unknown, fallback: number): number {
    if (typeof candidate === 'number' && Number.isFinite(candidate) && candidate > 0) {
        return Math.max(1, Math.floor(candidate));
    }
    return fallback;
}

function getPreferenceStorageKey(preferenceKey?: string): string | null {
    if (!preferenceKey || !preferenceKey.trim()) {
        return null;
    }

    return `${PREFS_STORAGE_PREFIX}${preferenceKey}`;
}

function readPersistedPreferences(storageKey: string | null, fallbackPageSize: number): PersistedTablePreferences {
    if (!storageKey) {
        return {
            sortColumn: null,
            sortDir: 'asc',
            pageSize: fallbackPageSize,
            searchTerm: '',
            columnFilters: {},
            showFilterPanel: false,
            hiddenColumns: [],
            columnOrder: [],
            pinnedColumns: [],
        };
    }

    try {
        const raw = localStorage.getItem(storageKey);
        if (!raw) {
            return {
                sortColumn: null,
                sortDir: 'asc',
                pageSize: fallbackPageSize,
                searchTerm: '',
                columnFilters: {},
                showFilterPanel: false,
                hiddenColumns: [],
                columnOrder: [],
                pinnedColumns: [],
            };
        }

        const parsed = JSON.parse(raw) as Partial<PersistedTablePreferences>;
        return {
            sortColumn: typeof parsed.sortColumn === 'string' || parsed.sortColumn === null ? parsed.sortColumn : null,
            sortDir: parsed.sortDir === 'desc' ? 'desc' : 'asc',
            pageSize: normalizePageSize(parsed.pageSize, fallbackPageSize),
            searchTerm: typeof parsed.searchTerm === 'string' ? parsed.searchTerm : '',
            columnFilters: sanitizeColumnFilters(parsed.columnFilters),
            showFilterPanel: parsed.showFilterPanel === true,
            hiddenColumns: sanitizeStringArray(parsed.hiddenColumns),
            columnOrder: sanitizeStringArray(parsed.columnOrder),
            pinnedColumns: sanitizeStringArray(parsed.pinnedColumns),
        };
    } catch {
        return {
            sortColumn: null,
            sortDir: 'asc',
            pageSize: fallbackPageSize,
            searchTerm: '',
            columnFilters: {},
            showFilterPanel: false,
            hiddenColumns: [],
            columnOrder: [],
            pinnedColumns: [],
        };
    }
}

function csvEscape(value: unknown): string {
    return `"${String(value ?? '').replace(/"/g, '""')}"`;
}

export function DataTable<T extends object>({
    columns,
    data,
    rowKey,
    selectable = false,
    selectedRows,
    onSelectionChange,
    emptyMessage = 'No data available',
    preferenceKey,
    loading = false,
    skeletonRowCount = 10,
    pagination = true,
    defaultPageSize = DEFAULT_PAGE_SIZE,
    pageSizeOptions = DEFAULT_PAGE_SIZE_OPTIONS,
    enableHeaderActions = true,
}: DataTableProps<T>) {
    const storageKey = getPreferenceStorageKey(preferenceKey);
    const allColumnKeys = useMemo(() => columns.map((column) => column.key), [columns]);
    const allColumnKeySignature = useMemo(() => allColumnKeys.join('|'), [allColumnKeys]);
    const normalizedDefaultPageSize = Number.isFinite(defaultPageSize)
        ? Math.max(1, Math.floor(defaultPageSize))
        : DEFAULT_PAGE_SIZE;
    const [sortColumn, setSortColumn] = useState<string | null>(() => readPersistedPreferences(storageKey, normalizedDefaultPageSize).sortColumn);
    const [sortDir, setSortDir] = useState<'asc' | 'desc'>(() => readPersistedPreferences(storageKey, normalizedDefaultPageSize).sortDir);
    const normalizedPageSizeOptions = useMemo(() => {
        const sanitized = pageSizeOptions
            .map((option) => Math.floor(option))
            .filter((option) => Number.isFinite(option) && option > 0);
        const fallback = sanitized.length > 0 ? sanitized : DEFAULT_PAGE_SIZE_OPTIONS;
        return Array.from(new Set([...fallback, normalizedDefaultPageSize])).sort((a, b) => a - b);
    }, [pageSizeOptions, normalizedDefaultPageSize]);
    const [pageSize, setPageSize] = useState<number>(() => readPersistedPreferences(storageKey, normalizedDefaultPageSize).pageSize);
    const [currentPage, setCurrentPage] = useState<number>(1);
    const [appliedSearchTerm, setAppliedSearchTerm] = useState<string>(() => readPersistedPreferences(storageKey, normalizedDefaultPageSize).searchTerm);
    const [appliedColumnFilters, setAppliedColumnFilters] = useState<Record<string, string>>(() => readPersistedPreferences(storageKey, normalizedDefaultPageSize).columnFilters);
    const [draftSearchTerm, setDraftSearchTerm] = useState<string>(() => readPersistedPreferences(storageKey, normalizedDefaultPageSize).searchTerm);
    const [draftColumnFilters, setDraftColumnFilters] = useState<Record<string, string>>(() => readPersistedPreferences(storageKey, normalizedDefaultPageSize).columnFilters);
    const [showFilterPanel, setShowFilterPanel] = useState<boolean>(() => readPersistedPreferences(storageKey, normalizedDefaultPageSize).showFilterPanel);
    const [columnOrder, setColumnOrder] = useState<string[]>(() => readPersistedPreferences(storageKey, normalizedDefaultPageSize).columnOrder);
    const [hiddenColumnKeys, setHiddenColumnKeys] = useState<string[]>(() => readPersistedPreferences(storageKey, normalizedDefaultPageSize).hiddenColumns);
    const [pinnedColumnKeys, setPinnedColumnKeys] = useState<string[]>(() => readPersistedPreferences(storageKey, normalizedDefaultPageSize).pinnedColumns);
    const [draggedColumnKey, setDraggedColumnKey] = useState<string | null>(null);
    const [dragOverColumnKey, setDragOverColumnKey] = useState<string | null>(null);
    const [showColumnPanel, setShowColumnPanel] = useState(false);
    const componentId = useId();
    const pageSizeSelectId = `${componentId}-page-size`;
    const columnPanelId = `${componentId}-column-panel`;
    const columnButtonRef = useRef<HTMLButtonElement | null>(null);
    const columnPanelRef = useRef<HTMLDivElement | null>(null);
    const theme = useTheme();
    const normalizedSkeletonRowCount = Number.isFinite(skeletonRowCount)
        ? Math.max(1, Math.floor(skeletonRowCount))
        : 10;

    const pinnedColumnKeySet = useMemo(() => new Set(pinnedColumnKeys), [pinnedColumnKeys]);
    const hiddenColumnKeySet = useMemo(() => new Set(hiddenColumnKeys), [hiddenColumnKeys]);
    const orderedColumns = useMemo(() => {
        const byKey = new Map(columns.map((column) => [column.key, column]));
        return normalizeColumnOrder(columnOrder, allColumnKeys)
            .map((key) => byKey.get(key))
            .filter((column): column is Column<T> => !!column);
    }, [columns, columnOrder, allColumnKeys]);
    const visibleColumns = useMemo(
        () => orderedColumns.filter((column) => !hiddenColumnKeySet.has(column.key)),
        [orderedColumns, hiddenColumnKeySet],
    );
    const visibleColumnKeySignature = useMemo(
        () => visibleColumns.map((column) => column.key).join('|'),
        [visibleColumns],
    );

    useEffect(() => {
        const preferences = readPersistedPreferences(storageKey, normalizedDefaultPageSize);
        const availableSet = new Set(allColumnKeys);
        const normalizedOrder = normalizeColumnOrder(preferences.columnOrder, allColumnKeys);
        const normalizedPinned = normalizePinnedColumns(preferences.pinnedColumns, normalizedOrder);
        const normalizedHidden = normalizeHiddenColumns(preferences.hiddenColumns, normalizedOrder, normalizedPinned);
        const normalizedFilters = removeDisallowedFilterKeys(preferences.columnFilters, availableSet);
        setSortColumn(preferences.sortColumn && availableSet.has(preferences.sortColumn) ? preferences.sortColumn : null);
        setSortDir(preferences.sortDir);
        setPageSize(preferences.pageSize);
        setAppliedSearchTerm(preferences.searchTerm);
        setAppliedColumnFilters(normalizedFilters);
        setDraftSearchTerm(preferences.searchTerm);
        setDraftColumnFilters(normalizedFilters);
        setShowFilterPanel(preferences.showFilterPanel);
        setColumnOrder(normalizedOrder);
        setPinnedColumnKeys(normalizedPinned);
        setHiddenColumnKeys(normalizedHidden);
        setDraggedColumnKey(null);
        setDragOverColumnKey(null);
        setShowColumnPanel(false);
        setCurrentPage(1);
    }, [storageKey, normalizedDefaultPageSize, allColumnKeySignature]);

    useEffect(() => {
        const availableSet = new Set(allColumnKeys);

        setColumnOrder((previous) => {
            const normalized = normalizeColumnOrder(previous, allColumnKeys);
            const unchanged = normalized.length === previous.length
                && normalized.every((value, index) => value === previous[index]);
            return unchanged ? previous : normalized;
        });

        setPinnedColumnKeys((previous) => {
            const normalized = normalizePinnedColumns(previous, allColumnKeys);
            const unchanged = normalized.length === previous.length
                && normalized.every((value, index) => value === previous[index]);
            return unchanged ? previous : normalized;
        });

        setHiddenColumnKeys((previous) => {
            const normalized = normalizeHiddenColumns(previous, allColumnKeys, pinnedColumnKeys);
            const unchanged = normalized.length === previous.length
                && normalized.every((value, index) => value === previous[index]);
            return unchanged ? previous : normalized;
        });

        setAppliedColumnFilters((previous) => removeDisallowedFilterKeys(previous, availableSet));
        setDraftColumnFilters((previous) => removeDisallowedFilterKeys(previous, availableSet));

        if (sortColumn && !availableSet.has(sortColumn)) {
            setSortColumn(null);
        }
    }, [allColumnKeySignature, pinnedColumnKeys, sortColumn]);

    useEffect(() => {
        const visibleSet = new Set(visibleColumns.map((column) => column.key));
        setAppliedColumnFilters((previous) => removeDisallowedFilterKeys(previous, visibleSet));
        setDraftColumnFilters((previous) => removeDisallowedFilterKeys(previous, visibleSet));
        if (sortColumn && !visibleSet.has(sortColumn)) {
            setSortColumn(null);
        }
    }, [visibleColumnKeySignature, sortColumn]);

    useEffect(() => {
        if (!storageKey) {
            return;
        }

        const payload: PersistedTablePreferences = {
            sortColumn,
            sortDir,
            pageSize,
            searchTerm: appliedSearchTerm,
            columnFilters: appliedColumnFilters,
            showFilterPanel,
            hiddenColumns: hiddenColumnKeys,
            columnOrder,
            pinnedColumns: pinnedColumnKeys,
        };

        try {
            localStorage.setItem(storageKey, JSON.stringify(payload));
        } catch {
            // Silently ignore localStorage write failures.
        }
    }, [storageKey, sortColumn, sortDir, pageSize, appliedSearchTerm, appliedColumnFilters, showFilterPanel, hiddenColumnKeys, columnOrder, pinnedColumnKeys]);

    const handleSort = (col: string) => {
        setCurrentPage(1);
        if (sortColumn === col) {
            setSortDir(sortDir === 'asc' ? 'desc' : 'asc');
        } else {
            setSortColumn(col);
            setSortDir('asc');
        }
    };

    useEffect(() => {
        if (!normalizedPageSizeOptions.includes(pageSize)) {
            setPageSize(normalizedPageSizeOptions[0]);
            setCurrentPage(1);
        }
    }, [normalizedPageSizeOptions, pageSize]);

    const filterOptionsByColumn = useMemo(() => {
        const options: Record<string, string[]> = {};

        visibleColumns.forEach((col) => {
            if (col.key === String(rowKey) || col.key === 'actions') {
                return;
            }

            const values = new Set<string>();
            data.forEach((row) => {
                const raw = (row as Record<string, unknown>)[col.key];
                if (typeof raw === 'string' || typeof raw === 'number' || typeof raw === 'boolean') {
                    const normalized = String(raw).trim();
                    if (normalized.length > 0) {
                        values.add(normalized);
                    }
                }
            });

            if (values.size > 1 && values.size <= 25) {
                options[col.key] = Array.from(values).sort((a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' }));
            }
        });

        return options;
    }, [visibleColumns, data, rowKey]);

    const filterableColumns = useMemo(
        () => visibleColumns.filter((column) => Object.prototype.hasOwnProperty.call(filterOptionsByColumn, column.key)).slice(0, 4),
        [visibleColumns, filterOptionsByColumn],
    );

    const filteredData = useMemo(() => {
        const normalizedSearch = appliedSearchTerm.trim().toLowerCase();
        const allowedFilterKeys = new Set(visibleColumns.map((column) => column.key));
        const hasActiveFilters = Object.values(appliedColumnFilters).some((value) => value.trim().length > 0);

        if (!normalizedSearch && !hasActiveFilters) {
            return data;
        }

        return data.filter((row) => {
            const record = row as Record<string, unknown>;
            const matchesSearch = !normalizedSearch || visibleColumns.some((column) => {
                const raw = record[column.key];
                return raw !== null && raw !== undefined && String(raw).toLowerCase().includes(normalizedSearch);
            });

            if (!matchesSearch) {
                return false;
            }

            return Object.entries(appliedColumnFilters).every(([key, expected]) => {
                if (!expected || !allowedFilterKeys.has(key)) {
                    return true;
                }

                return String(record[key] ?? '') === expected;
            });
        });
    }, [data, visibleColumns, appliedSearchTerm, appliedColumnFilters]);

    const sortedData = useMemo(() => {
        if (!sortColumn) {
            return filteredData;
        }

        const sorted = [...filteredData];
        sorted.sort((a, b) => {
            const aVal = String((a as Record<string, unknown>)[sortColumn] ?? '');
            const bVal = String((b as Record<string, unknown>)[sortColumn] ?? '');
            return sortDir === 'asc' ? aVal.localeCompare(bVal) : bVal.localeCompare(aVal);
        });

        return sorted;
    }, [filteredData, sortColumn, sortDir]);

    const totalPages = pagination ? Math.max(1, Math.ceil(sortedData.length / pageSize)) : 1;
    const totalRows = sortedData.length;
    const startRow = totalRows === 0 || !pagination ? (totalRows === 0 ? 0 : 1) : ((currentPage - 1) * pageSize) + 1;
    const endRow = totalRows === 0 || !pagination ? totalRows : Math.min(currentPage * pageSize, totalRows);

    useEffect(() => {
        if (currentPage > totalPages) {
            setCurrentPage(totalPages);
        }
    }, [currentPage, totalPages]);

    const visibleRows = useMemo(() => {
        if (!pagination) {
            return sortedData;
        }

        const start = (currentPage - 1) * pageSize;
        return sortedData.slice(start, start + pageSize);
    }, [sortedData, pagination, currentPage, pageSize]);

    const allVisibleRowsSelected = !!selectedRows
        && visibleRows.length > 0
        && visibleRows.every((row) => selectedRows.has(String((row as Record<string, unknown>)[rowKey as string])));

    const toggleRow = (id: string) => {
        if (!onSelectionChange || !selectedRows) return;
        const next = new Set(selectedRows);
        if (next.has(id)) next.delete(id);
        else next.add(id);
        onSelectionChange(next);
    };

    const toggleAll = () => {
        if (!onSelectionChange || !selectedRows) return;

        const pageIds = visibleRows.map((row) => String((row as Record<string, unknown>)[rowKey as string]));
        const next = new Set(selectedRows);
        const clearCurrentPage = pageIds.length > 0 && pageIds.every((id) => next.has(id));

        if (clearCurrentPage) {
            pageIds.forEach((id) => next.delete(id));
        } else {
            pageIds.forEach((id) => next.add(id));
        }

        onSelectionChange(next);
    };

    const handlePageSizeChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
        const nextPageSize = Number.parseInt(event.target.value, 10);
        if (!Number.isFinite(nextPageSize) || nextPageSize <= 0) {
            return;
        }

        const firstVisibleIndex = (currentPage - 1) * pageSize;
        const recalculatedPage = Math.floor(firstVisibleIndex / nextPageSize) + 1;
        setPageSize(nextPageSize);
        setCurrentPage(recalculatedPage);
    };

    const goToPage = (page: number) => {
        const boundedPage = Math.min(Math.max(page, 1), totalPages);
        setCurrentPage(boundedPage);
    };

    const handleDraftFilterChange = (key: string, value: string) => {
        setDraftColumnFilters((previous) => ({ ...previous, [key]: value }));
    };

    const clearDraftFilters = () => {
        setDraftSearchTerm('');
        setDraftColumnFilters({});
    };

    const applyFilters = () => {
        setAppliedSearchTerm(draftSearchTerm.trim());
        setAppliedColumnFilters({ ...draftColumnFilters });
        setCurrentPage(1);
    };

    const toggleFilterPanel = () => {
        setShowFilterPanel((previous) => !previous);
    };

    const toggleColumnPanel = () => {
        setShowColumnPanel((previous) => !previous);
    };

    const toggleColumnVisibility = (key: string) => {
        setHiddenColumnKeys((previous) => {
            if (pinnedColumnKeySet.has(key)) {
                return previous;
            }

            const hidden = new Set(previous);
            if (hidden.has(key)) {
                hidden.delete(key);
                return Array.from(hidden);
            }

            if ((allColumnKeys.length - hidden.size) <= 1) {
                return previous;
            }

            hidden.add(key);
            return Array.from(hidden);
        });
    };

    const toggleColumnPin = (key: string) => {
        const alreadyPinned = pinnedColumnKeySet.has(key);

        setPinnedColumnKeys((previous) => {
            const next = new Set(previous);
            if (alreadyPinned) {
                next.delete(key);
            } else {
                next.add(key);
            }

            return normalizePinnedColumns(Array.from(next), allColumnKeys);
        });

        if (!alreadyPinned) {
            setHiddenColumnKeys((previous) => previous.filter((hiddenKey) => hiddenKey !== key));
        }
    };

    const reorderColumns = (dragKey: string, dropKey: string) => {
        setColumnOrder((previous) => {
            const normalized = normalizeColumnOrder(previous, allColumnKeys);
            const fromIndex = normalized.indexOf(dragKey);
            const toIndex = normalized.indexOf(dropKey);
            if (fromIndex < 0 || toIndex < 0 || fromIndex === toIndex) {
                return previous;
            }

            const next = [...normalized];
            const [moved] = next.splice(fromIndex, 1);
            next.splice(toIndex, 0, moved);
            return next;
        });
    };

    const handleColumnDragStart = (event: React.DragEvent<HTMLButtonElement>, key: string) => {
        event.dataTransfer.effectAllowed = 'move';
        event.dataTransfer.setData('text/plain', key);
        setDraggedColumnKey(key);
        setDragOverColumnKey(key);
    };

    const handleColumnDragOver = (event: React.DragEvent<HTMLDivElement>, key: string) => {
        event.preventDefault();
        if (draggedColumnKey && draggedColumnKey !== key) {
            setDragOverColumnKey(key);
        }
    };

    const handleColumnDrop = (dropKey: string) => {
        if (!draggedColumnKey) {
            return;
        }

        reorderColumns(draggedColumnKey, dropKey);
        setDraggedColumnKey(null);
        setDragOverColumnKey(null);
    };

    const handleColumnDragEnd = () => {
        setDraggedColumnKey(null);
        setDragOverColumnKey(null);
    };

    const showAllColumns = () => {
        setHiddenColumnKeys([]);
    };

    const resetColumns = () => {
        setColumnOrder(allColumnKeys);
        setPinnedColumnKeys([]);
        setHiddenColumnKeys([]);
    };

    useEffect(() => {
        if (!showColumnPanel) {
            return;
        }

        const handleDocumentMouseDown = (event: MouseEvent) => {
            const target = event.target as Node | null;
            if (!target) {
                return;
            }

            if (columnPanelRef.current?.contains(target) || columnButtonRef.current?.contains(target)) {
                return;
            }

            setShowColumnPanel(false);
        };

        const handleDocumentKeyDown = (event: KeyboardEvent) => {
            if (event.key === 'Escape') {
                setShowColumnPanel(false);
            }
        };

        document.addEventListener('mousedown', handleDocumentMouseDown);
        document.addEventListener('keydown', handleDocumentKeyDown);

        return () => {
            document.removeEventListener('mousedown', handleDocumentMouseDown);
            document.removeEventListener('keydown', handleDocumentKeyDown);
        };
    }, [showColumnPanel]);

    const hasPendingFilterChanges = useMemo(() => {
        const normalizedDraftSearch = draftSearchTerm.trim();
        if (normalizedDraftSearch !== appliedSearchTerm) {
            return true;
        }

        const keys = new Set([...Object.keys(draftColumnFilters), ...Object.keys(appliedColumnFilters)]);
        return Array.from(keys).some((key) => (draftColumnFilters[key] ?? '') !== (appliedColumnFilters[key] ?? ''));
    }, [draftSearchTerm, appliedSearchTerm, draftColumnFilters, appliedColumnFilters]);

    const exportColumns = useMemo(
        () => visibleColumns.filter((column) => column.key !== 'actions'),
        [visibleColumns],
    );

    const exportAsCsv = () => {
        if (sortedData.length === 0) {
            return;
        }

        const headers = exportColumns.map((column) => csvEscape(column.header)).join(',');
        const rows = sortedData.map((row) => exportColumns.map((column) => csvEscape((row as Record<string, unknown>)[column.key])).join(','));
        const csv = [headers, ...rows].join('\n');
        const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');

        link.href = url;
        link.download = `table-export-${new Date().toISOString().slice(0, 10)}.csv`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

    const sendEmailSummary = () => {
        const selectableRows = selectable && selectedRows
            ? sortedData.filter((row) => selectedRows.has(String((row as Record<string, unknown>)[rowKey as string])))
            : [];
        const rowsToSummarize = selectableRows.length > 0 ? selectableRows : sortedData.slice(0, 25);

        if (rowsToSummarize.length === 0) {
            return;
        }

        const summaryColumns = exportColumns.slice(0, 5);
        const lines = rowsToSummarize.map((row, index) => {
            const record = row as Record<string, unknown>;
            const content = summaryColumns.map((column) => `${column.header}: ${String(record[column.key] ?? '')}`).join(' | ');
            return `${index + 1}. ${content}`;
        });

        const subject = `Table Summary (${rowsToSummarize.length})`;
        const body = ['Table Summary', '', ...lines].join('\n');
        window.location.href = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    };

    const actionButtonStyles: React.CSSProperties = {
        minWidth: '36px',
        height: '32px',
        border: `1px solid ${theme.palette.divider}`,
        borderRadius: '6px',
        backgroundColor: theme.palette.background.paper,
        color: theme.palette.text.primary,
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        cursor: 'pointer',
    };

    const tableStyles: React.CSSProperties = {
        width: '100%',
        borderCollapse: 'collapse',
        fontSize: '0.875rem',
    };

    const thStyles: React.CSSProperties = {
        textAlign: 'left',
        padding: '0.75rem 1rem',
        borderBottom: `2px solid ${theme.palette.divider}`,
        fontWeight: 600,
        color: theme.palette.text.secondary,
        fontSize: '0.75rem',
        textTransform: 'uppercase',
        letterSpacing: '0.05em',
        whiteSpace: 'nowrap',
    };

    const tdStyles: React.CSSProperties = {
        padding: '0.75rem 1rem',
        borderBottom: `1px solid ${theme.palette.divider}`,
        color: theme.palette.text.primary,
    };

    return (
        <div role="region" aria-label="Data table" aria-busy={loading || undefined}>
            {enableHeaderActions && (
                <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '0.5rem', marginBottom: '0.5rem', position: 'relative' }}>
                    <button
                        type="button"
                        aria-label={showFilterPanel ? 'Hide table filters' : 'Show table filters'}
                        onClick={toggleFilterPanel}
                        style={{
                            ...actionButtonStyles,
                            borderColor: showFilterPanel ? theme.palette.primary.main : theme.palette.divider,
                        }}
                    >
                        <FilterListIcon fontSize="small" />
                    </button>

                    <div style={{ position: 'relative' }}>
                        <button
                            ref={columnButtonRef}
                            type="button"
                            aria-label="Select and reorder columns"
                            aria-haspopup="dialog"
                            aria-expanded={showColumnPanel}
                            aria-controls={showColumnPanel ? columnPanelId : undefined}
                            title="Select and reorder columns to customize table display"
                            onClick={toggleColumnPanel}
                            style={{
                                ...actionButtonStyles,
                                borderColor: showColumnPanel ? theme.palette.primary.main : theme.palette.divider,
                            }}
                        >
                            <ViewColumnIcon fontSize="small" />
                        </button>

                        {showColumnPanel && (
                            <div
                                ref={columnPanelRef}
                                id={columnPanelId}
                                role="dialog"
                                aria-label="Select visible table columns"
                                style={{
                                    position: 'absolute',
                                    top: 'calc(100% + 0.4rem)',
                                    right: 0,
                                    width: '280px',
                                    maxWidth: '90vw',
                                    padding: '0.65rem',
                                    border: `1px solid ${theme.palette.divider}`,
                                    borderRadius: '8px',
                                    backgroundColor: theme.palette.background.paper,
                                    boxShadow: theme.shadows[8],
                                    zIndex: 120,
                                }}
                            >
                                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.5rem' }}>
                                    <strong style={{ fontSize: '0.8125rem' }}>Columns</strong>
                                    <span style={{ fontSize: '0.75rem', color: theme.palette.text.secondary }}>
                                        {visibleColumns.length} of {orderedColumns.length}
                                    </span>
                                </div>

                                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.5rem', marginBottom: '0.5rem' }}>
                                    <button
                                        type="button"
                                        onClick={showAllColumns}
                                        disabled={hiddenColumnKeys.length === 0}
                                        style={{
                                            padding: '0.35rem 0.55rem',
                                            border: `1px solid ${theme.palette.divider}`,
                                            borderRadius: '6px',
                                            backgroundColor: theme.palette.background.paper,
                                            color: theme.palette.text.primary,
                                            cursor: hiddenColumnKeys.length === 0 ? 'not-allowed' : 'pointer',
                                            fontSize: '0.75rem',
                                            fontWeight: 600,
                                        }}
                                    >
                                        Show All
                                    </button>
                                    <button
                                        type="button"
                                        onClick={resetColumns}
                                        style={{
                                            padding: '0.35rem 0.55rem',
                                            border: `1px solid ${theme.palette.divider}`,
                                            borderRadius: '6px',
                                            backgroundColor: theme.palette.background.paper,
                                            color: theme.palette.text.primary,
                                            cursor: 'pointer',
                                            fontSize: '0.75rem',
                                            fontWeight: 600,
                                        }}
                                    >
                                        Reset
                                    </button>
                                </div>

                                <div style={{ maxHeight: '240px', overflowY: 'auto', borderTop: `1px solid ${theme.palette.divider}`, paddingTop: '0.35rem' }}>
                                    {orderedColumns.map((column) => {
                                        const visible = !hiddenColumnKeySet.has(column.key);
                                        const pinned = pinnedColumnKeySet.has(column.key);
                                        const disableHide = pinned || (visible && visibleColumns.length <= 1);
                                        const isDragTarget = dragOverColumnKey === column.key && draggedColumnKey !== column.key;

                                        return (
                                            <div
                                                key={column.key}
                                                onDragOver={(event) => handleColumnDragOver(event, column.key)}
                                                onDrop={() => handleColumnDrop(column.key)}
                                                style={{
                                                    display: 'grid',
                                                    gridTemplateColumns: '22px 22px 1fr',
                                                    alignItems: 'center',
                                                    gap: '0.4rem',
                                                    padding: '0.2rem 0',
                                                    backgroundColor: isDragTarget ? alpha(theme.palette.primary.main, 0.14) : 'transparent',
                                                    borderRadius: '6px',
                                                }}
                                            >
                                                <button
                                                    type="button"
                                                    draggable
                                                    onDragStart={(event) => handleColumnDragStart(event, column.key)}
                                                    onDragEnd={handleColumnDragEnd}
                                                    aria-label={`Grab ${column.header} and move to reorder`}
                                                    style={{
                                                        width: '22px',
                                                        height: '22px',
                                                        border: 'none',
                                                        borderRadius: '4px',
                                                        backgroundColor: 'transparent',
                                                        color: theme.palette.text.secondary,
                                                        cursor: 'grab',
                                                        display: 'inline-flex',
                                                        alignItems: 'center',
                                                        justifyContent: 'center',
                                                        padding: 0,
                                                    }}
                                                >
                                                    <DragIndicatorIcon fontSize="inherit" />
                                                </button>
                                                <button
                                                    type="button"
                                                    onClick={() => toggleColumnPin(column.key)}
                                                    aria-label={pinned ? `Unpin column ${column.header}` : `Pin column ${column.header}`}
                                                    style={{
                                                        width: '22px',
                                                        height: '22px',
                                                        border: 'none',
                                                        borderRadius: '4px',
                                                        backgroundColor: 'transparent',
                                                        color: pinned ? theme.palette.primary.main : theme.palette.text.secondary,
                                                        cursor: 'pointer',
                                                        display: 'inline-flex',
                                                        alignItems: 'center',
                                                        justifyContent: 'center',
                                                        padding: 0,
                                                    }}
                                                >
                                                    {pinned ? <PushPinIcon fontSize="inherit" /> : <PushPinOutlinedIcon fontSize="inherit" />}
                                                </button>
                                                <label style={{ display: 'inline-flex', alignItems: 'center', gap: '0.4rem', fontSize: '0.8125rem', color: theme.palette.text.primary, minWidth: 0 }}>
                                                    <input
                                                        type="checkbox"
                                                        checked={visible}
                                                        disabled={disableHide}
                                                        onChange={() => toggleColumnVisibility(column.key)}
                                                        aria-label={`Toggle column ${column.header}`}
                                                    />
                                                    <span style={{ overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{column.header}</span>
                                                </label>
                                            </div>
                                        );
                                    })}
                                </div>
                            </div>
                        )}
                    </div>

                    <button
                        type="button"
                        aria-label="Download table as CSV"
                        onClick={exportAsCsv}
                        style={actionButtonStyles}
                    >
                        <DownloadIcon fontSize="small" />
                    </button>
                    <button
                        type="button"
                        aria-label="Send table summary email"
                        onClick={sendEmailSummary}
                        style={{
                            ...actionButtonStyles,
                            minWidth: '92px',
                            padding: '0 0.65rem',
                            fontSize: '0.75rem',
                            fontWeight: 600,
                        }}
                    >
                        Send Email
                    </button>
                </div>
            )}

            {showFilterPanel && (
                <div
                    style={{
                        display: 'grid',
                        gridTemplateColumns: 'repeat(auto-fit, minmax(170px, 1fr))',
                        gap: '0.75rem',
                        marginBottom: '0.75rem',
                        paddingBottom: '0.75rem',
                        borderBottom: `1px solid ${theme.palette.divider}`,
                    }}
                >
                    <label style={{ display: 'flex', flexDirection: 'column', gap: '0.25rem', fontSize: '0.75rem', color: theme.palette.text.secondary }}>
                        Search
                        <input
                            value={draftSearchTerm}
                            onChange={(event) => setDraftSearchTerm(event.target.value)}
                            placeholder="Search records"
                            aria-label="Search records"
                            style={{
                                padding: '0.45rem 0.55rem',
                                border: `1px solid ${theme.palette.divider}`,
                                borderRadius: '6px',
                                backgroundColor: theme.palette.background.paper,
                                color: theme.palette.text.primary,
                            }}
                        />
                    </label>

                    {filterableColumns.map((column) => (
                        <label
                            key={column.key}
                            style={{ display: 'flex', flexDirection: 'column', gap: '0.25rem', fontSize: '0.75rem', color: theme.palette.text.secondary }}
                        >
                            {column.header}
                            <select
                                value={draftColumnFilters[column.key] ?? ''}
                                onChange={(event) => handleDraftFilterChange(column.key, event.target.value)}
                                aria-label={`Filter by ${column.header}`}
                                style={{
                                    padding: '0.45rem 0.55rem',
                                    border: `1px solid ${theme.palette.divider}`,
                                    borderRadius: '6px',
                                    backgroundColor: theme.palette.background.paper,
                                    color: theme.palette.text.primary,
                                }}
                            >
                                <option value="">All</option>
                                {(filterOptionsByColumn[column.key] ?? []).map((option) => (
                                    <option key={option} value={option}>{option}</option>
                                ))}
                            </select>
                        </label>
                    ))}

                    <div style={{ display: 'flex', alignItems: 'end', gap: '0.5rem' }}>
                        <button
                            type="button"
                            onClick={clearDraftFilters}
                            aria-label="Clear draft filters"
                            style={{
                                padding: '0.45rem 0.75rem',
                                border: `1px solid ${theme.palette.divider}`,
                                borderRadius: '6px',
                                backgroundColor: theme.palette.background.paper,
                                color: theme.palette.text.primary,
                                cursor: 'pointer',
                                fontSize: '0.75rem',
                                fontWeight: 600,
                            }}
                        >
                            Clear
                        </button>
                        <button
                            type="button"
                            onClick={applyFilters}
                            aria-label="Apply filters"
                            disabled={!hasPendingFilterChanges}
                            style={{
                                padding: '0.45rem 0.85rem',
                                border: `1px solid ${theme.palette.primary.main}`,
                                borderRadius: '6px',
                                backgroundColor: hasPendingFilterChanges ? theme.palette.primary.main : theme.palette.action.disabledBackground,
                                color: hasPendingFilterChanges ? theme.palette.primary.contrastText : theme.palette.text.disabled,
                                cursor: hasPendingFilterChanges ? 'pointer' : 'not-allowed',
                                fontSize: '0.75rem',
                                fontWeight: 700,
                            }}
                        >
                            Apply
                        </button>
                    </div>
                </div>
            )}

            <div style={{ overflowX: 'auto' }}>
                <table style={tableStyles}>
                <thead>
                    <tr>
                        {selectable && (
                            <th style={{ ...thStyles, width: '40px' }}>
                                <input
                                    type="checkbox"
                                    aria-label="Select all rows on current page"
                                    checked={allVisibleRowsSelected}
                                    onChange={toggleAll}
                                />
                            </th>
                        )}
                        {visibleColumns.map((col) => (
                            <th
                                key={col.key}
                                style={{ ...thStyles, width: col.width, cursor: col.sortable ? 'pointer' : 'default' }}
                                scope="col"
                                aria-sort={sortColumn === col.key ? (sortDir === 'asc' ? 'ascending' : 'descending') : undefined}
                                onClick={() => col.sortable && handleSort(col.key)}
                                onKeyDown={(e) => e.key === 'Enter' && col.sortable && handleSort(col.key)}
                                tabIndex={col.sortable ? 0 : undefined}
                            >
                                {col.header}
                                {col.sortable && sortColumn === col.key && (
                                    <span aria-hidden="true" style={{ marginLeft: '0.25rem' }}>{sortDir === 'asc' ? '▲' : '▼'}</span>
                                )}
                            </th>
                        ))}
                    </tr>
                </thead>
                <tbody>
                    {loading ? (
                        Array.from({ length: normalizedSkeletonRowCount }).map((_, rowIndex) => (
                            <tr key={`skeleton-row-${rowIndex}`} aria-hidden="true">
                                {selectable && (
                                    <td style={tdStyles}>
                                        <Skeleton variant="rounded" width={16} height={16} />
                                    </td>
                                )}
                                {visibleColumns.map((col) => (
                                    <td key={`${col.key}-skeleton-${rowIndex}`} style={tdStyles}>
                                        <Skeleton
                                            variant="text"
                                            width={col.width ?? `${Math.max(45, 88 - rowIndex * 3)}%`}
                                            height={22}
                                        />
                                    </td>
                                ))}
                            </tr>
                        ))
                    ) : sortedData.length === 0 ? (
                        <tr>
                            <td colSpan={visibleColumns.length + (selectable ? 1 : 0)} style={{ ...tdStyles, textAlign: 'center', padding: '2rem' }}>
                                {emptyMessage}
                            </td>
                        </tr>
                    ) : (
                        visibleRows.map((row) => {
                            const id = String((row as Record<string, unknown>)[rowKey as string]);
                            const isSelected = selectedRows?.has(id);
                            return (
                                <tr
                                    key={id}
                                    style={{ backgroundColor: isSelected ? alpha(theme.palette.primary.main, 0.12) : 'transparent' }}
                                >
                                    {selectable && (
                                        <td style={tdStyles}>
                                            <input
                                                type="checkbox"
                                                aria-label={`Select row ${id}`}
                                                checked={!!isSelected}
                                                onChange={() => toggleRow(id)}
                                            />
                                        </td>
                                    )}
                                    {visibleColumns.map((col) => (
                                        <td key={col.key} style={tdStyles}>
                                            {col.render ? col.render(row) : String((row as Record<string, unknown>)[col.key] ?? '')}
                                        </td>
                                    ))}
                                </tr>
                            );
                        })
                    )}
                </tbody>
                </table>
            </div>

            {pagination && !loading && sortedData.length > 0 && (
                <nav
                    aria-label="Table pagination"
                    style={{
                        display: 'flex',
                        flexWrap: 'wrap',
                        alignItems: 'center',
                        justifyContent: 'space-between',
                        gap: '0.75rem',
                        padding: '0.75rem 0',
                        marginTop: '0.25rem',
                        color: theme.palette.text.secondary,
                        fontSize: '0.8125rem',
                    }}
                >
                    <span aria-live="polite" style={{ whiteSpace: 'nowrap' }}>
                        {startRow}-{endRow} of {totalRows}
                    </span>

                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginLeft: 'auto' }}>
                        <select
                            id={pageSizeSelectId}
                            value={pageSize}
                            onChange={handlePageSizeChange}
                            aria-label="Rows per page"
                            style={{
                                padding: '0.25rem 0.5rem',
                                border: `1px solid ${theme.palette.divider}`,
                                borderRadius: '0.375rem',
                                backgroundColor: theme.palette.background.paper,
                                color: theme.palette.text.primary,
                            }}
                        >
                            {normalizedPageSizeOptions.map((option) => (
                                <option key={option} value={option}>
                                    {option}
                                </option>
                            ))}
                        </select>

                        <button
                            type="button"
                            onClick={() => goToPage(currentPage - 1)}
                            disabled={currentPage === 1}
                            aria-label="Previous page"
                            style={{
                                width: '28px',
                                height: '28px',
                                border: `1px solid ${theme.palette.divider}`,
                                borderRadius: '6px',
                                backgroundColor: theme.palette.background.paper,
                                color: theme.palette.text.primary,
                                cursor: currentPage === 1 ? 'not-allowed' : 'pointer',
                            }}
                        >
                            ‹
                        </button>

                        <span
                            aria-live="polite"
                            aria-label={`Page ${currentPage} of ${totalPages}`}
                            style={{
                                minWidth: '28px',
                                height: '28px',
                                display: 'inline-flex',
                                alignItems: 'center',
                                justifyContent: 'center',
                                border: `1px solid ${theme.palette.divider}`,
                                borderRadius: '6px',
                                backgroundColor: theme.palette.background.paper,
                                color: theme.palette.text.primary,
                                fontWeight: 600,
                            }}
                        >
                            {currentPage}
                        </span>

                        <button
                            type="button"
                            onClick={() => goToPage(currentPage + 1)}
                            disabled={currentPage >= totalPages}
                            aria-label="Next page"
                            style={{
                                width: '28px',
                                height: '28px',
                                border: `1px solid ${theme.palette.divider}`,
                                borderRadius: '6px',
                                backgroundColor: theme.palette.background.paper,
                                color: theme.palette.text.primary,
                                cursor: currentPage >= totalPages ? 'not-allowed' : 'pointer',
                            }}
                        >
                            ›
                        </button>
                    </div>
                </nav>
            )}
        </div>
    );
}
