// Generated by GitHub Copilot
/**
 * DataTable — Accessible data table with sorting and row selection.
 * @accessibility Uses semantic <table> with proper th scope, aria-sort, and keyboard navigation.
 */
import React, { useState } from 'react';

export interface Column<T> {
  key: string;
  header: string;
  render?: (row: T) => React.ReactNode;
  sortable?: boolean;
  width?: string;
}

interface DataTableProps<T> {
  columns: Column<T>[];
  data: T[];
  rowKey: keyof T;
  selectable?: boolean;
  selectedRows?: Set<string>;
  onSelectionChange?: (selected: Set<string>) => void;
  emptyMessage?: string;
}

export function DataTable<T extends object>({
  columns,
  data,
  rowKey,
  selectable = false,
  selectedRows,
  onSelectionChange,
  emptyMessage = 'No data available',
}: DataTableProps<T>) {
  const [sortColumn, setSortColumn] = useState<string | null>(null);
  const [sortDir, setSortDir] = useState<'asc' | 'desc'>('asc');

  const handleSort = (col: string) => {
    if (sortColumn === col) {
      setSortDir(sortDir === 'asc' ? 'desc' : 'asc');
    } else {
      setSortColumn(col);
      setSortDir('asc');
    }
  };

  const sorted = [...data].sort((a, b) => {
    if (!sortColumn) return 0;
    const aVal = String((a as Record<string, unknown>)[sortColumn] ?? '');
    const bVal = String((b as Record<string, unknown>)[sortColumn] ?? '');
    return sortDir === 'asc' ? aVal.localeCompare(bVal) : bVal.localeCompare(aVal);
  });

  const toggleRow = (id: string) => {
    if (!onSelectionChange || !selectedRows) return;
    const next = new Set(selectedRows);
    if (next.has(id)) next.delete(id);
    else next.add(id);
    onSelectionChange(next);
  };

  const toggleAll = () => {
    if (!onSelectionChange) return;
    if (selectedRows?.size === data.length) {
      onSelectionChange(new Set());
    } else {
      onSelectionChange(new Set(data.map((r) => String((r as Record<string, unknown>)[rowKey as string]))));
    }
  };

  const tableStyles: React.CSSProperties = {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: '0.875rem',
  };

  const thStyles: React.CSSProperties = {
    textAlign: 'left',
    padding: '0.75rem 1rem',
    borderBottom: '2px solid var(--color-border, #e5e7eb)',
    fontWeight: 600,
    color: 'var(--color-text-secondary, #6b7280)',
    fontSize: '0.75rem',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    whiteSpace: 'nowrap',
  };

  const tdStyles: React.CSSProperties = {
    padding: '0.75rem 1rem',
    borderBottom: '1px solid var(--color-border, #e5e7eb)',
    color: 'var(--color-text, #1f2937)',
  };

  return (
    <div style={{ overflowX: 'auto' }} role="region" aria-label="Data table">
      <table style={tableStyles}>
        <thead>
          <tr>
            {selectable && (
              <th style={{ ...thStyles, width: '40px' }}>
                <input
                  type="checkbox"
                  aria-label="Select all rows"
                  checked={selectedRows?.size === data.length && data.length > 0}
                  onChange={toggleAll}
                />
              </th>
            )}
            {columns.map((col) => (
              <th
                key={col.key}
                style={{ ...thStyles, width: col.width, cursor: col.sortable ? 'pointer' : 'default' }}
                scope="col"
                aria-sort={sortColumn === col.key ? (sortDir === 'asc' ? 'ascending' : 'descending') : undefined}
                onClick={() => col.sortable && handleSort(col.key)}
                onKeyDown={(e) => e.key === 'Enter' && col.sortable && handleSort(col.key)}
                tabIndex={col.sortable ? 0 : undefined}
              >
                {col.header}
                {col.sortable && sortColumn === col.key && (
                  <span aria-hidden="true" style={{ marginLeft: '0.25rem' }}>{sortDir === 'asc' ? '▲' : '▼'}</span>
                )}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {sorted.length === 0 ? (
            <tr>
              <td colSpan={columns.length + (selectable ? 1 : 0)} style={{ ...tdStyles, textAlign: 'center', padding: '2rem' }}>
                {emptyMessage}
              </td>
            </tr>
          ) : (
            sorted.map((row) => {
              const id = String((row as Record<string, unknown>)[rowKey as string]);
              const isSelected = selectedRows?.has(id);
              return (
                <tr
                  key={id}
                  style={{ backgroundColor: isSelected ? 'var(--color-selected, #eff6ff)' : 'transparent' }}
                >
                  {selectable && (
                    <td style={tdStyles}>
                      <input
                        type="checkbox"
                        aria-label={`Select row ${id}`}
                        checked={!!isSelected}
                        onChange={() => toggleRow(id)}
                      />
                    </td>
                  )}
                  {columns.map((col) => (
                    <td key={col.key} style={tdStyles}>
                      {col.render ? col.render(row) : String((row as Record<string, unknown>)[col.key] ?? '')}
                    </td>
                  ))}
                </tr>
              );
            })
          )}
        </tbody>
      </table>
    </div>
  );
}
