
/**
 * Modal — Accessible dialog overlay.
 * @accessibility Uses role="dialog", aria-modal, aria-labelledby, focus trap, Escape to close.
 */
import React, { useEffect, useRef } from 'react';
import { useTheme } from '@mui/material/styles';

interface ModalProps {
    isOpen: boolean;
    onClose: () => void;
    title: string;
    children: React.ReactNode;
    size?: 'sm' | 'md' | 'lg';
}

export const Modal: React.FC<ModalProps> = ({ isOpen, onClose, title, children, size = 'md' }) => {
    const dialogRef = useRef<HTMLDivElement>(null);
    const theme = useTheme();

    useEffect(() => {
        if (isOpen) {
            dialogRef.current?.focus();
        }
    }, [isOpen]);

    useEffect(() => {
        const handleEscape = (e: KeyboardEvent) => {
            if (e.key === 'Escape' && isOpen) onClose();
        };
        document.addEventListener('keydown', handleEscape);
        return () => document.removeEventListener('keydown', handleEscape);
    }, [isOpen, onClose]);

    if (!isOpen) return null;

    const widths: Record<string, string> = { sm: '400px', md: '560px', lg: '720px' };
    const isDarkMode = theme.palette.mode === 'dark';

    // Generated by GitHub Copilot
    const overlayColor = isDarkMode ? 'rgba(0, 0, 0, 0.72)' : 'rgba(0, 0, 0, 0.5)';
    const dialogShadow = isDarkMode
        ? '0 24px 72px rgba(0, 0, 0, 0.62)'
        : '0 20px 60px rgba(0, 0, 0, 0.15)';

    return (
        <div
            style={{
                position: 'fixed', inset: 0, zIndex: 1000,
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                backgroundColor: overlayColor,
            }}
            onClick={onClose}
            aria-hidden="true"
        >
            <div
                ref={dialogRef}
                role="dialog"
                aria-modal="true"
                aria-labelledby="modal-title"
                tabIndex={-1}
                onClick={(e) => e.stopPropagation()}
                style={{
                    backgroundColor: theme.palette.background.paper,
                    color: theme.palette.text.primary,
                    border: `1px solid ${theme.palette.divider}`,
                    borderRadius: '12px',
                    padding: '1.5rem',
                    maxWidth: widths[size],
                    width: '90%',
                    maxHeight: '80vh',
                    overflowY: 'auto',
                    boxShadow: dialogShadow,
                }}
            >
                <header
                    style={{
                        display: 'flex',
                        justifyContent: 'space-between',
                        alignItems: 'center',
                        marginBottom: '1rem',
                        paddingBottom: '0.625rem',
                        borderBottom: `1px solid ${theme.palette.divider}`,
                    }}
                >
                    <h2 id="modal-title" style={{ margin: 0, fontSize: '1.25rem', fontWeight: 600 }}>{title}</h2>
                    <button
                        onClick={onClose}
                        aria-label="Close dialog"
                        style={{
                            background: 'none', border: 'none', fontSize: '1.5rem', cursor: 'pointer',
                            color: theme.palette.text.secondary,
                            lineHeight: 1,
                            padding: '0.25rem',
                            borderRadius: '6px',
                        }}
                    >
                        ×
                    </button>
                </header>
                {children}
            </div>
        </div>
    );
};
