
/**
 * StatCard — MUI-based metric display card for dashboards.
 * @accessibility aria-label provides full context for screen readers.
 */
import React from 'react';
import MuiCard from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import Typography from '@mui/material/Typography';
import Box from '@mui/material/Box';
import SecurityIcon from '@mui/icons-material/Security';
import SpeedIcon from '@mui/icons-material/Speed';
import CheckCircleIcon from '@mui/icons-material/CheckCircle';
import WarningIcon from '@mui/icons-material/Warning';
import TrendingUpIcon from '@mui/icons-material/TrendingUp';
import PeopleIcon from '@mui/icons-material/People';

type TrendDirection = 'up' | 'down' | 'neutral';
type ChangeType = 'positive' | 'negative' | 'neutral';

interface StatCardProps {
    label: string;
    value: string | number;
    change?: string;
    changeType?: ChangeType;
    trend?: TrendDirection | string;
    trendValue?: string | number;
    icon?: string;
}

const CHANGE_COLORS = {
    positive: 'success.main',
    negative: 'error.main',
    neutral: 'text.secondary',
} as const;

const CHANGE_PREFIX = { positive: '↑', negative: '↓', neutral: '→' } as const;

const KPI_ICON_COMPONENTS: Record<string, React.ElementType> = {
    Security: SecurityIcon,
    SecurityIcon,
    Speed: SpeedIcon,
    SpeedIcon,
    CheckCircle: CheckCircleIcon,
    CheckCircleIcon,
    Warning: WarningIcon,
    WarningIcon,
    TrendingUp: TrendingUpIcon,
    TrendingUpIcon,
    People: PeopleIcon,
    PeopleIcon,
};

// Generated by GitHub Copilot
/**
 * Normalizes trend values from config/runtime payloads into canonical direction.
 */
function normalizeTrend(trend?: TrendDirection | string): TrendDirection | undefined {
    if (!trend) {
        return undefined;
    }

    const normalized = trend.toLowerCase();
    if (normalized === 'up') return 'up';
    if (normalized === 'down') return 'down';
    if (normalized === 'neutral') return 'neutral';
    return undefined;
}

// Generated by GitHub Copilot
/**
 * Resolves UI color/arrow semantics from either legacy `changeType` or new `trend`.
 */
function resolveChangeType(changeType?: ChangeType, trend?: TrendDirection | string): ChangeType {
    if (changeType) {
        return changeType;
    }

    const normalizedTrend = normalizeTrend(trend);
    if (normalizedTrend === 'up') return 'positive';
    if (normalizedTrend === 'down') return 'negative';
    return 'neutral';
}

// Generated by GitHub Copilot
/**
 * Creates a human-readable trend/change label with backward compatibility.
 */
function resolveChangeLabel(
    change?: string,
    trend?: TrendDirection | string,
    trendValue?: string | number,
): string | undefined {
    if (typeof change === 'string' && change.trim().length > 0) {
        return change;
    }

    if (trendValue !== undefined && trendValue !== null && String(trendValue).trim().length > 0) {
        return String(trendValue);
    }

    const normalizedTrend = normalizeTrend(trend);
    if (normalizedTrend === 'up') return 'Up';
    if (normalizedTrend === 'down') return 'Down';
    return undefined;
}

// Generated by GitHub Copilot
/**
 * Renders a named KPI icon from the allowlist or falls back to raw text/icon glyph.
 */
function renderKpiIcon(icon?: string): React.ReactNode {
    if (!icon) {
        return null;
    }

    const IconComponent = KPI_ICON_COMPONENTS[icon];
    if (IconComponent) {
        return <IconComponent fontSize="small" aria-hidden="true" />;
    }

    return (
        <Box component="span" aria-hidden="true" sx={{ fontSize: '1.25rem', lineHeight: 1 }}>
            {icon}
        </Box>
    );
}

export const StatCard: React.FC<StatCardProps> = ({
    label,
    value,
    change,
    changeType,
    trend,
    trendValue,
    icon,
}) => {
    const resolvedChangeType = resolveChangeType(changeType, trend);
    const resolvedChangeLabel = resolveChangeLabel(change, trend, trendValue);
    const showTrend = Boolean(resolvedChangeLabel);

    return (
        <MuiCard
            component="article"
            role="article"
            aria-label={`${label}: ${value}`}
            elevation={1}
            sx={{ p: 0 }}
        >
            <CardContent sx={{ '&:last-child': { pb: 2 } }}>
                <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 0.5 }}>
                    <Typography variant="body2" color="text.secondary" fontWeight={500}>{label}</Typography>
                    {renderKpiIcon(icon)}
                </Box>
                <Typography variant="h4" fontWeight={700} sx={{ lineHeight: 1.1, mb: showTrend ? 0.5 : 0 }}>
                    {value}
                </Typography>
                {showTrend && (
                    <Typography variant="caption" fontWeight={500} color={CHANGE_COLORS[resolvedChangeType]}>
                        {CHANGE_PREFIX[resolvedChangeType]} {resolvedChangeLabel}
                    </Typography>
                )}
            </CardContent>
        </MuiCard>
    );
};
