// Generated by GitHub Copilot
/**
 * StatCard — MUI-based metric display card for dashboards.
 * @accessibility aria-label provides full context for screen readers.
 */
import React from 'react';
import MuiCard from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import Typography from '@mui/material/Typography';
import Box from '@mui/material/Box';

interface StatCardProps {
    label: string;
    value: string | number;
    change?: string;
    changeType?: 'positive' | 'negative' | 'neutral';
    icon?: string;
}

const CHANGE_COLORS = {
    positive: 'success.main',
    negative: 'error.main',
    neutral: 'text.secondary',
} as const;

const CHANGE_PREFIX = { positive: '↑', negative: '↓', neutral: '→' } as const;

export const StatCard: React.FC<StatCardProps> = ({ label, value, change, changeType = 'neutral', icon }) => (
    <MuiCard
        component="article"
        aria-label={`${label}: ${value}`}
        elevation={1}
        sx={{ p: 0 }}
    >
        <CardContent sx={{ '&:last-child': { pb: 2 } }}>
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 0.5 }}>
                <Typography variant="body2" color="text.secondary" fontWeight={500}>{label}</Typography>
                {icon && <Box component="span" aria-hidden="true" sx={{ fontSize: '1.25rem', lineHeight: 1 }}>{icon}</Box>}
            </Box>
            <Typography variant="h4" fontWeight={700} sx={{ lineHeight: 1.1, mb: change ? 0.5 : 0 }}>
                {value}
            </Typography>
            {change && (
                <Typography variant="caption" fontWeight={500} color={CHANGE_COLORS[changeType]}>
                    {CHANGE_PREFIX[changeType]} {change}
                </Typography>
            )}
        </CardContent>
    </MuiCard>
);
