// Generated by GitHub Copilot
import React from 'react';
import { render, screen } from '@testing-library/react';
import { axe, toHaveNoViolations } from 'jest-axe';
import { vi, describe, it, expect, beforeEach } from 'vitest';
import { StatCard } from './StatCard';

expect.extend(toHaveNoViolations);

vi.mock('@mui/material/Card', () => ({ default: ({ children, ...p }: any) => <div {...p}>{children}</div> }));
vi.mock('@mui/material/CardContent', () => ({ default: ({ children }: any) => <div>{children}</div> }));
vi.mock('@mui/material/Typography', () => ({ default: ({ children, variant, color }: any) => <span data-variant={variant} data-color={color}>{children}</span> }));
vi.mock('@mui/material/Box', () => ({ default: ({ children, ...p }: any) => <div {...p}>{children}</div> }));

describe('StatCard', () => {
    beforeEach(() => { vi.clearAllMocks(); });

    it('renders label and value', () => {
        render(<StatCard label="Total Risks" value={42} />);
        expect(screen.getByText('Total Risks')).toBeInTheDocument();
        expect(screen.getByText('42')).toBeInTheDocument();
    });

    it('sets aria-label with label and value', () => {
        render(<StatCard label="Open Incidents" value={7} />);
        expect(screen.getByRole('article')).toHaveAttribute('aria-label', 'Open Incidents: 7');
    });

    it('renders icon when provided', () => {
        render(<StatCard label="Risks" value={5} icon="🛡️" />);
        expect(screen.getByText('🛡️')).toBeInTheDocument();
    });

    it('renders change indicator for positive trend', () => {
        render(<StatCard label="Score" value={90} change="+5%" changeType="positive" />);
        expect(screen.getByText(/↑.*\+5%/)).toBeInTheDocument();
    });

    it('renders change indicator for negative trend', () => {
        render(<StatCard label="Score" value={80} change="-3%" changeType="negative" />);
        expect(screen.getByText(/↓.*-3%/)).toBeInTheDocument();
    });

    it('does not render change when not provided', () => {
        render(<StatCard label="Count" value={10} />);
        expect(screen.queryByText('↑')).not.toBeInTheDocument();
        expect(screen.queryByText('↓')).not.toBeInTheDocument();
    });

    describe('accessibility', () => {
        it('has no accessibility violations', async () => {
            const { container } = render(<StatCard label="Total" value={100} change="+10%" changeType="positive" />);
            expect(await axe(container)).toHaveNoViolations();
        });
    });
});
