/**
 * useViewRuntime - executes ViewConfig data sources and applies data bindings.
 * Provides resolved component props, loading state, and retry support.
 */
import { useCallback, useEffect, useState } from 'react';
import { apiClient } from '@shared/api-client';
import type { DataBinding, DataBindingConfig, DataSource, ViewComponent, ViewConfig } from '@shared/types';

// Generated by GitHub Copilot
interface ViewRuntimeState {
    resolvedComponents: ViewComponent[];
    isLoading: boolean;
    error: string | null;
}

export interface ViewRuntimeResult extends ViewRuntimeState {
    refresh: () => void;
}

/**
 * Resolves a dot-path expression against arbitrary nested data.
 */
function resolvePathValue(source: unknown, path: string): unknown {
    const normalizedPath = path
        .replace(/^\$\.?/, '')
        .replace(/\[(\d+)\]/g, '.$1')
        .trim();

    if (!normalizedPath) {
        return source;
    }

    const segments = normalizedPath.split('.').filter(Boolean);
    let current: unknown = source;

    for (const segment of segments) {
        if (current === null || current === undefined) {
            return undefined;
        }

        current = (current as Record<string, unknown>)[segment];
    }

    return current;
}

/**
 * Applies optional transform directives used by data bindings.
 */
function applyTransform(value: unknown, transform?: string): unknown {
    if (!transform) {
        return value;
    }

    switch (transform) {
        case 'toString':
            return value === null || value === undefined ? '' : String(value);
        case 'toLowerCase':
            return typeof value === 'string' ? value.toLowerCase() : value;
        case 'toUpperCase':
            return typeof value === 'string' ? value.toUpperCase() : value;
        case 'number': {
            const converted = Number(value);
            return Number.isNaN(converted) ? value : converted;
        }
        default:
            return value;
    }
}

/**
 * Evaluates one binding definition against runtime source data.
 */
function evaluateBinding(source: unknown, binding: string | DataBindingConfig): unknown {
    const bindingConfig: DataBindingConfig = typeof binding === 'string'
        ? { path: binding }
        : binding;

    const rawValue = resolvePathValue(source, bindingConfig.path);
    const fallbackApplied = rawValue === undefined || rawValue === null
        ? bindingConfig.fallback
        : rawValue;

    return applyTransform(fallbackApplied, bindingConfig.transform);
}

/**
 * Maps data binding rules onto component props according to strategy.
 */
function applyDataBinding(
    baseProps: Record<string, unknown>,
    dataBinding: DataBinding | undefined,
    source: unknown,
): Record<string, unknown> {
    if (!dataBinding) {
        return baseProps;
    }

    const boundProps: Record<string, unknown> = {};

    for (const [propKey, binding] of Object.entries(dataBinding.bindings)) {
        boundProps[propKey] = evaluateBinding(source, binding);
    }

    switch (dataBinding.strategy) {
        case 'replace':
            return boundProps;
        case 'overlay':
            return { ...boundProps, ...baseProps };
        case 'merge':
        default:
            return { ...baseProps, ...boundProps };
    }
}

/**
 * Serializes dataSource.params into querystring values.
 */
function withQueryParams(path: string, params?: Record<string, unknown>): string {
    if (!params || Object.keys(params).length === 0) {
        return path;
    }

    const searchParams = new URLSearchParams();

    for (const [key, value] of Object.entries(params)) {
        if (value === undefined || value === null) {
            continue;
        }

        if (Array.isArray(value)) {
            searchParams.set(key, value.map((entry) => String(entry)).join(','));
            continue;
        }

        searchParams.set(key, String(value));
    }

    const queryString = searchParams.toString();
    if (!queryString) {
        return path;
    }

    return `${path}${path.includes('?') ? '&' : '?'}${queryString}`;
}

/**
 * Executes a single DataSource via shared api-client.
 */
async function executeDataSource(dataSource: DataSource, signal: AbortSignal): Promise<unknown> {
    const method = dataSource.method;
    const endpoint = method === 'GET'
        ? withQueryParams(dataSource.path, dataSource.params)
        : dataSource.path;

    const commonConfig = {
        signal,
        headers: dataSource.headers,
        disableCache: dataSource.disableCache,
    };

    switch (method) {
        case 'POST':
            return apiClient.post(endpoint, dataSource.body ?? {}, commonConfig);
        case 'PUT':
            return apiClient.put(endpoint, dataSource.body ?? {}, commonConfig);
        case 'DELETE':
            return apiClient.delete(endpoint, commonConfig);
        case 'GET':
        default:
            return apiClient.get(endpoint, commonConfig);
    }
}

/**
 * Normalizes data source fields that can be single object or array.
 */
function normalizeDataSources(dataSource?: DataSource | DataSource[]): DataSource[] {
    if (!dataSource) {
        return [];
    }

    return Array.isArray(dataSource) ? dataSource : [dataSource];
}

/**
 * Resolves component props from view-level and component-level data sources.
 */
async function resolveComponents(config: ViewConfig, signal: AbortSignal): Promise<ViewComponent[]> {
    const viewDataSources = normalizeDataSources(config.dataSource);
    const componentDataMap = new Map<string, unknown>();

    let rootData: unknown = undefined;

    if (viewDataSources.length > 0) {
        const rootResults = await Promise.all(viewDataSources.map((dataSource) => executeDataSource(dataSource, signal)));
        rootData = rootResults.length === 1 ? rootResults[0] : rootResults;
    }

    await Promise.all(
        config.components.map(async (component) => {
            const componentSources = normalizeDataSources(component.dataSource);
            if (componentSources.length === 0) {
                return;
            }

            const componentResults = await Promise.all(
                componentSources.map((dataSource) => executeDataSource(dataSource, signal)),
            );
            componentDataMap.set(component.id, componentResults.length === 1 ? componentResults[0] : componentResults);
        }),
    );

    return config.components.map((component) => {
        const baseProps = (component.props ?? {}) as Record<string, unknown>;
        const source = componentDataMap.get(component.id) ?? rootData;
        const binding = component.dataBinding ?? config.dataBinding;

        if (!binding) {
            if (source && typeof source === 'object' && !Array.isArray(source)) {
                return {
                    ...component,
                    props: { ...baseProps, ...(source as Record<string, unknown>) },
                };
            }

            return component;
        }

        return {
            ...component,
            props: applyDataBinding(baseProps, binding, source),
        };
    });
}

/**
 * Hook that executes view runtime and returns data-resolved components.
 */
export function useViewRuntime(config: ViewConfig): ViewRuntimeResult {
    const [refreshToken, setRefreshToken] = useState(0);
    const [state, setState] = useState<ViewRuntimeState>({
        resolvedComponents: config.components,
        isLoading: false,
        error: null,
    });

    const refresh = useCallback(() => {
        setRefreshToken((prev) => prev + 1);
    }, []);

    useEffect(() => {
        const controller = new AbortController();
        let active = true;

        const hasRuntimeWork = Boolean(
            config.dataSource
            || config.dataBinding
            || config.components.some((component) => component.dataSource || component.dataBinding),
        );

        if (!hasRuntimeWork) {
            setState({
                resolvedComponents: config.components,
                isLoading: false,
                error: null,
            });
            return () => controller.abort();
        }

        setState((prev) => ({ ...prev, isLoading: true, error: null }));

        resolveComponents(config, controller.signal)
            .then((resolvedComponents) => {
                if (!active) return;
                setState({ resolvedComponents, isLoading: false, error: null });
            })
            .catch((error: unknown) => {
                if (!active) return;
                const message = error instanceof Error ? error.message : 'Failed to load view runtime data.';
                setState({ resolvedComponents: config.components, isLoading: false, error: message });
            });

        return () => {
            active = false;
            controller.abort();
        };
    }, [config, refreshToken]);

    return {
        ...state,
        refresh,
    };
}
