// Generated by GitHub Copilot
/**
 * ViewRenderer — Renders a ViewConfig JSON definition as React UI.
 * Maps component types to shared ui-components and handles layout.
 * @see README §8 Config-Driven UI System
 * @accessibility All rendered components follow WCAG 2.1 AA via their MUI base.
 */
import React from 'react';
import Grid from '@mui/material/Grid';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import Tabs from '@mui/material/Tabs';
import Tab from '@mui/material/Tab';
import { StatCard, Card, PageHeader } from '@shared/ui-components';
import type {
  ViewConfig,
  ViewComponent,
  LayoutNode,
  GridLayoutNode,
  StackLayoutNode,
  TabLayoutNode,
} from '@shared/types';

/* ─── Component registry ──────────────────────────────────── */

/**
 * Renders a single ViewComponent based on its `type` field.
 * Extend this function to add new component types.
 */
function renderComponent(component: ViewComponent): React.ReactNode {
  const props = component.props ?? {};

  switch (component.type) {
    case 'kpi':
      return (
        <StatCard
          label={component.title ?? ''}
          value={(props.value as string | number) ?? '-'}
          change={props.change as string | undefined}
          changeType={props.changeType as 'positive' | 'negative' | 'neutral' | undefined}
          icon={props.icon as string | undefined}
        />
      );

    case 'text':
      return (
        <Box>
          {component.title && (
            <Typography variant="h6" fontWeight={600} gutterBottom>
              {component.title}
            </Typography>
          )}
          <Typography variant="body1" color="text.secondary">
            {(props.content as string) ?? component.description ?? ''}
          </Typography>
        </Box>
      );

    case 'summary': {
      const summaryItems = props.items && Array.isArray(props.items)
        ? (props.items as Array<Record<string, unknown>>)
        : [];
      return (
        <Card title={component.title}>
          {component.description && (
            <Typography variant="body2" color="text.secondary">
              {component.description}
            </Typography>
          )}
          {summaryItems.length > 0 && (
            <Box sx={{ m: 0 }}>
              {summaryItems.map((item, i) => (
                <Box key={i} sx={{ display: 'flex', justifyContent: 'space-between', py: 0.5 }}>
                  <Typography variant="body2" color="text.secondary">{String(item['label'] ?? '')}</Typography>
                  <Typography variant="body2" fontWeight={500}>{String(item['value'] ?? '')}</Typography>
                </Box>
              ))}
            </Box>
          )}
        </Card>
      );
    }

    default:
      // Unknown component type — render a placeholder in dev
      return (
        <Card title={component.title ?? component.type}>
          <Typography variant="body2" color="text.secondary">
            {component.description ?? `Component type "${component.type}" is not yet rendered.`}
          </Typography>
        </Card>
      );
  }
}

/* ─── Layout renderer ─────────────────────────────────────── */

function renderLayout(layout: LayoutNode, componentMap: Map<string, ViewComponent>): React.ReactNode {
  switch (layout.type) {
    case 'grid': {
      const gridLayout = layout as GridLayoutNode;
      return (
        <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
          {gridLayout.rows.map((row, rowIdx) => (
            <Grid container spacing={2} key={rowIdx}>
              {row.columns.map((col, colIdx) => {
                const size = typeof col.size === 'number' ? col.size : 12;
                return (
                  <Grid key={colIdx} size={size as number}>
                    {col.children?.map((child, ci) => (
                      <Box key={ci} sx={{ mb: 2 }}>
                        {renderLayout(child, componentMap)}
                      </Box>
                    ))}
                  </Grid>
                );
              })}
            </Grid>
          ))}
        </Box>
      );
    }

    case 'stack': {
      const stackLayout = layout as StackLayoutNode;
      return (
        <Box
          sx={{
            display: 'flex',
            flexDirection: stackLayout.direction === 'row' ? 'row' : 'column',
            gap: 2,
            flexWrap: stackLayout.direction === 'row' ? 'wrap' : undefined,
          }}
        >
          {stackLayout.children.map((child, i) => (
            <Box key={i} sx={{ flex: stackLayout.direction === 'row' ? '1 1 0' : undefined }}>
              {renderLayout(child, componentMap)}
            </Box>
          ))}
        </Box>
      );
    }

    case 'component': {
      const comp = componentMap.get(layout.id);
      return comp ? renderComponent(comp) : null;
    }

    case 'tab': {
      const tabLayout = layout as TabLayoutNode;
      return <TabbedLayout config={tabLayout} componentMap={componentMap} />;
    }

    default:
      return null;
  }
}

/* ─── Tabbed layout (needs state) ────────────────────────── */

const TabbedLayout: React.FC<{ config: TabLayoutNode; componentMap: Map<string, ViewComponent> }> = ({
  config,
  componentMap,
}) => {
  const [active, setActive] = React.useState(config.defaultTab ?? 0);

  return (
    <Box>
      <Tabs
        value={active}
        onChange={(_, v) => setActive(v)}
        aria-label="View tabs"
        sx={{ borderBottom: 1, borderColor: 'divider', mb: 2 }}
      >
        {config.tabs.map((tab, i) => (
          <Tab
            key={i}
            label={tab.name}
            disabled={tab.disabled}
            id={`tab-${i}`}
            aria-controls={`tabpanel-${i}`}
          />
        ))}
      </Tabs>
      {config.tabs.map((tab, i) => (
        <Box
          key={i}
          role="tabpanel"
          hidden={active !== i}
          id={`tabpanel-${i}`}
          aria-labelledby={`tab-${i}`}
        >
          {active === i && renderLayout(tab.layout, componentMap)}
        </Box>
      ))}
    </Box>
  );
};

/* ─── Public ViewRenderer ─────────────────────────────────── */

interface ViewRendererProps {
  config: ViewConfig;
}

/**
 * ViewRenderer — renders a complete ViewConfig JSON as React UI.
 *
 * @example
 * ```tsx
 * import viewConfig from './views/configs/incidents.json';
 * <ViewRenderer config={viewConfig as ViewConfig} />
 * ```
 */
export const ViewRenderer: React.FC<ViewRendererProps> = ({ config }) => {
  const componentMap = React.useMemo(
    () => new Map(config.components.map((c) => [c.id, c])),
    [config.components],
  );

  return (
    <Box component="section" aria-label={config.title} sx={{ width: '100%' }}>
      {config.title && (
        <PageHeader
          title={config.title}
          subtitle={config.description}
        />
      )}

      {config.layout
        ? renderLayout(config.layout, componentMap)
        : (
          // No layout specified — render components in a simple responsive grid
          <Box
            sx={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
              gap: 2,
            }}
          >
            {config.components.map((comp) => (
              <Box key={comp.id}>{renderComponent(comp)}</Box>
            ))}
          </Box>
        )}
    </Box>
  );
};
