// Generated by GitHub Copilot
/**
 * Shared webpack config factory for remote micro-apps.
 * Each remote exposes ./Module and shares React as singleton.
 */
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const { container } = require('webpack');
const { ModuleFederationPlugin } = container;

/**
 * @param {{ name: string, port: number, appDir: string }} config
 * @returns {import('webpack').Configuration}
 */
function createRemoteWebpackConfig(config) {
  return {
    context: config.appDir,
    entry: './src/index.ts',
    mode: 'development',
    devServer: {
      port: config.port,
      historyApiFallback: true,
      headers: { 'Access-Control-Allow-Origin': '*' },
    },
    output: {
      publicPath: 'auto',
      path: path.resolve(config.appDir, '../../dist/apps/' + config.name),
      clean: true,
    },
    resolve: {
      extensions: ['.ts', '.tsx', '.js', '.jsx'],
      alias: {
        '@shared/types': path.resolve(config.appDir, '../../libs/shared/types/src/index.ts'),
        '@shared/auth': path.resolve(config.appDir, '../../libs/shared/auth/src/index.ts'),
        '@shared/ui-components': path.resolve(config.appDir, '../../libs/shared/ui-components/src/index.ts'),
        '@shared/api-client': path.resolve(config.appDir, '../../libs/shared/api-client/src/index.ts'),
        '@shared/event-bus': path.resolve(config.appDir, '../../libs/shared/event-bus/src/index.ts'),
      },
    },
    module: {
      rules: [
        { test: /\.tsx?$/, use: { loader: 'ts-loader', options: { configFile: 'tsconfig.app.json' } }, exclude: /node_modules/ },
        { test: /\.css$/, use: ['style-loader', 'css-loader'] },
      ],
    },
    plugins: [
      new ModuleFederationPlugin({
        name: config.name,
        filename: 'remoteEntry.js',
        exposes: { './Module': './src/remote-entry.tsx' },
        shared: {
          react: { singleton: true, requiredVersion: false, eager: false },
          'react-dom': { singleton: true, requiredVersion: false, eager: false },
          'react-router-dom': { singleton: true, requiredVersion: false, eager: false },
          '@shared/types': { singleton: true, requiredVersion: false, eager: false },
          '@shared/auth': { singleton: true, requiredVersion: false, eager: false },
          '@shared/ui-components': { singleton: true, requiredVersion: false, eager: false },
          '@shared/api-client': { singleton: true, requiredVersion: false, eager: false },
          '@shared/event-bus': { singleton: true, requiredVersion: false, eager: false },
        },
      }),
      new HtmlWebpackPlugin({ template: './src/index.html' }),
    ],
  };
}

module.exports = { createRemoteWebpackConfig };
