// Generated by GitHub Copilot
// Pulls @testing-library/jest-dom Vitest type augmentation into this compilation context.
// Required because moduleResolution:node doesn't support package.json sub-path exports,
// so `import '@testing-library/jest-dom/vitest'` silently fails. The reference path directive
// resolves by physical file path, bypassing sub-path export resolution.
/// <reference path="../../../../node_modules/@testing-library/jest-dom/types/vitest.d.ts" />
