
/**
 * AuthProvider — Provides authentication context to the entire application tree.
 * Supports two adapters controlled by the USE_MOCK_AUTH build-time flag:
 *   - MSAL (production): Azure AD via @azure/msal-browser PublicClientApplication
 *   - Mock (development): In-memory user for local dev without Azure AD tenant
 * @security Tokens stored in sessionStorage (cleared on tab close). No PII logged.
 */
import React, { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';
import { PublicClientApplication, AccountInfo, InteractionRequiredAuthError } from '@azure/msal-browser';
import { MsalProvider, useMsal } from '@azure/msal-react';
import { User, UserRole } from '@shared/types';
import { msalConfig, loginRequest, apiRequest } from './msalConfig';

export interface LoginCredentials {
  email: string;
  password: string;
  rememberDevice?: boolean;
}

export interface AuthContextType {
  user: User | null;
  isAuthenticated: boolean;
  isLoading: boolean;
  login: (credentials?: LoginCredentials) => Promise<void>;
  logout: () => void;
  getAccessToken: () => Promise<string | null>;
}


/**
 * Window-based singleton ensures all Module Federation bundles share
 * the same React context object, even when each bundles its own copy
 * of this module.
 */
const AUTH_CONTEXT_KEY = '__PARTNER_PORTAL_AUTH_CONTEXT__';
const AuthContext: React.Context<AuthContextType | null> =
  (window as any)[AUTH_CONTEXT_KEY] ||
  ((window as any)[AUTH_CONTEXT_KEY] = createContext<AuthContextType | null>(null));

// ─── Mock adapter (USE_MOCK_AUTH=true) ────────────────────────────────────────

interface MockAuthUser extends User {
  password: string;
  approved: boolean;
}

// Generated by GitHub Copilot
const ROLE_ALIASES: Record<string, UserRole> = {
  admin: UserRole.Admin,
  complianceofficer: UserRole.ComplianceOfficer,
  'compliance-officer': UserRole.ComplianceOfficer,
  auditor: UserRole.Auditor,
  partner: UserRole.Partner,
  viewer: UserRole.Viewer,
};

const MOCK_TOKEN = 'mock-jwt-token-for-development';
const MOCK_SESSION_USER_KEY = 'partner-portal:mock-auth:session-user';
const MOCK_PERSISTED_USER_KEY = 'partner-portal:mock-auth:persisted-user';
const IS_TEST_ENV = String((process.env as any).NODE_ENV ?? '').trim().toLowerCase() === 'test';

/** Mock users for development fallback - never used in production builds */
const MOCK_DEFAULT_USERS: MockAuthUser[] = [
  {
    id: 'usr-001',
    displayName: 'Jane Doe',
    email: 'jane.doe@partner-portal.com',
    role: UserRole.Admin,
    password: 'Password123!',
    approved: true,
    avatarUrl: undefined,
  },
  {
    id: 'usr-002',
    displayName: 'Ravi Sharma',
    email: 'ravi.sharma@partner-portal.com',
    role: UserRole.ComplianceOfficer,
    password: 'Password123!',
    approved: true,
    avatarUrl: undefined,
  },
  {
    id: 'usr-003',
    displayName: 'Elena Cruz',
    email: 'elena.cruz@partner-portal.com',
    role: UserRole.Auditor,
    password: 'Password123!',
    approved: true,
    avatarUrl: undefined,
  },
  {
    id: 'usr-004',
    displayName: 'Marcus Lee',
    email: 'marcus.lee@partner-portal.com',
    role: UserRole.Partner,
    password: 'Password123!',
    approved: true,
    avatarUrl: undefined,
  },
];

const MOCK_AUTO_LOGIN = !IS_TEST_ENV && typeof (process.env as any).MOCK_AUTH_AUTO_LOGIN !== 'undefined'
  ? ['1', 'true', 'yes', 'y'].includes(String((process.env as any).MOCK_AUTH_AUTO_LOGIN).trim().toLowerCase())
  : false;

const MOCK_PERSIST_BY_DEFAULT = typeof (process.env as any).MOCK_AUTH_PERSIST_BY_DEFAULT !== 'undefined'
  ? ['1', 'true', 'yes', 'y'].includes(String((process.env as any).MOCK_AUTH_PERSIST_BY_DEFAULT).trim().toLowerCase())
  : true;

const MOCK_AUTO_LOGIN_EMAIL = String((process.env as any).MOCK_AUTH_AUTO_LOGIN_EMAIL ?? '')
  .trim()
  .toLowerCase();

/**
 * Converts raw role strings to valid UserRole values with safe fallback.
 */
function normalizeRole(rawRole: unknown): UserRole {
  if (typeof rawRole !== 'string') {
    return UserRole.Viewer;
  }

  const normalized = rawRole.trim().toLowerCase();
  return ROLE_ALIASES[normalized] ?? UserRole.Viewer;
}

/**
 * Parses mock users from environment JSON.
 * @security Enforces strict shape validation and defaults to approved=false unless explicitly set.
 */
function readMockUsersFromEnv(): MockAuthUser[] {
  const raw = String((process.env as any).MOCK_AUTH_USERS ?? '').trim();
  if (!raw) {
    return MOCK_DEFAULT_USERS;
  }

  try {
    const parsed = JSON.parse(raw);
    if (!Array.isArray(parsed)) {
      return MOCK_DEFAULT_USERS;
    }

    const users = parsed
      .filter((entry): entry is Record<string, unknown> => Boolean(entry) && typeof entry === 'object')
      .map((entry, index): MockAuthUser | null => {
        const email = String(entry.email ?? '').trim().toLowerCase();
        const password = String(entry.password ?? '');
        if (!email || !password) {
          return null;
        }

        return {
          id: String(entry.id ?? `usr-mock-${index + 1}`),
          displayName: String(entry.displayName ?? email.split('@')[0] ?? `Mock User ${index + 1}`),
          email,
          password,
          role: normalizeRole(entry.role),
          approved: entry.approved === true,
          avatarUrl: undefined,
        };
      })
      .filter((entry): entry is MockAuthUser => entry !== null);

    return users.length > 0 ? users : MOCK_DEFAULT_USERS;
  } catch {
    return MOCK_DEFAULT_USERS;
  }
}

/**
 * Writes the authenticated mock user into storage and token cache.
 */
function persistMockSession(user: User, rememberDevice: boolean): void {
  const serializedUser = JSON.stringify(user);

  sessionStorage.setItem(MOCK_SESSION_USER_KEY, serializedUser);
  sessionStorage.setItem('auth_token', MOCK_TOKEN);

  if (rememberDevice) {
    localStorage.setItem(MOCK_PERSISTED_USER_KEY, serializedUser);
  } else {
    localStorage.removeItem(MOCK_PERSISTED_USER_KEY);
  }
}

/**
 * Clears all mock auth state from browser storage.
 */
function clearMockSession(): void {
  sessionStorage.removeItem('auth_token');
  sessionStorage.removeItem(MOCK_SESSION_USER_KEY);
  localStorage.removeItem(MOCK_PERSISTED_USER_KEY);
}

/**
 * Restores a mock-authenticated user from session or persistent storage.
 */
function restoreMockSession(): User | null {
  const sessionUserRaw = sessionStorage.getItem(MOCK_SESSION_USER_KEY);
  const persistedUserRaw = localStorage.getItem(MOCK_PERSISTED_USER_KEY);
  const source = sessionUserRaw ?? persistedUserRaw;

  if (!source) {
    return null;
  }

  try {
    const parsed = JSON.parse(source) as User;
    if (!parsed || typeof parsed !== 'object' || !parsed.id || !parsed.email || !parsed.role) {
      clearMockSession();
      return null;
    }

    // Keep token available for API calls on every refresh.
    sessionStorage.setItem('auth_token', MOCK_TOKEN);
    sessionStorage.setItem(MOCK_SESSION_USER_KEY, JSON.stringify(parsed));
    return parsed;
  } catch {
    clearMockSession();
    return null;
  }
}

/**
 * Maps the mock auth user to public User shape.
 */
function toPublicUser(mockUser: MockAuthUser): User {
  return {
    id: mockUser.id,
    displayName: mockUser.displayName,
    email: mockUser.email,
    role: mockUser.role,
    avatarUrl: mockUser.avatarUrl,
  };
}

/**
 * MockAuthProvider - local development only.
 * Uses env-configured credentials, optional approval gating, and refresh persistence.
 */
const MockAuthProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const mockUsers = useMemo(readMockUsersFromEnv, []);
  const [user, setUser] = useState<User | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    // When auto-login is disabled, always start signed-out and show the login form.
    if (!MOCK_AUTO_LOGIN) {
      clearMockSession();
      return;
    }

    const restoredUser = restoreMockSession();
    if (restoredUser) {
      setUser(restoredUser);
      return;
    }

    const autoLoginUser = MOCK_AUTO_LOGIN_EMAIL
      ? mockUsers.find((entry) => entry.approved && entry.email === MOCK_AUTO_LOGIN_EMAIL)
      : mockUsers.find((entry) => entry.approved);

    if (!autoLoginUser) {
      return;
    }

    const mappedUser = toPublicUser(autoLoginUser);
    setUser(mappedUser);
    persistMockSession(mappedUser, true);
  }, [mockUsers]);

  const login = useCallback(async (credentials?: LoginCredentials) => {
    setIsLoading(true);
    try {
      const normalizedEmail = String(credentials?.email ?? '').trim().toLowerCase();
      const providedPassword = String(credentials?.password ?? '');

      // Credentialed sign-in is used by the login form. No-arg login keeps tests backwards compatible.
      const selectedUser = (normalizedEmail || providedPassword)
        ? mockUsers.find((entry) => entry.email === normalizedEmail)
        : (MOCK_AUTO_LOGIN_EMAIL
          ? mockUsers.find((entry) => entry.email === MOCK_AUTO_LOGIN_EMAIL && entry.approved)
          : mockUsers.find((entry) => entry.approved));

      if (!selectedUser) {
        throw new Error('Invalid email or password.');
      }

      if (normalizedEmail || providedPassword) {
        if (!normalizedEmail || !providedPassword) {
          throw new Error('Enter both email and password.');
        }

        if (selectedUser.password !== providedPassword) {
          throw new Error('Invalid email or password.');
        }
      }

      if (!selectedUser.approved) {
        throw new Error('Your account is awaiting admin approval.');
      }

      const authenticatedUser = toPublicUser(selectedUser);
      const shouldPersist = credentials?.rememberDevice ?? MOCK_PERSIST_BY_DEFAULT;

      setUser(authenticatedUser);
      persistMockSession(authenticatedUser, shouldPersist);
    } finally {
      setIsLoading(false);
    }
  }, [mockUsers]);

  const logout = useCallback(() => {
    setUser(null);
    clearMockSession();
  }, []);

  const getAccessToken = useCallback(async (): Promise<string | null> => {
    return sessionStorage.getItem('auth_token');
  }, []);

  return (
    <AuthContext.Provider value={{ user, isAuthenticated: !!user, isLoading, login, logout, getAccessToken }}>
      {children}
    </AuthContext.Provider>
  );
};

// ─── MSAL adapter (USE_MOCK_AUTH=false) ───────────────────────────────────────

/** Singleton MSAL instance shared across all MF bundles via window */
const MSAL_INSTANCE_KEY = '__PARTNER_PORTAL_MSAL_INSTANCE__';
const msalInstance: PublicClientApplication =
  (window as any)[MSAL_INSTANCE_KEY] ||
  ((window as any)[MSAL_INSTANCE_KEY] = new PublicClientApplication(msalConfig));

/**
 * Maps an MSAL AccountInfo to the portal's User domain type.
 * Role is parsed from app roles claim if present, falling back to Viewer.
 */
function mapAccountToUser(account: AccountInfo): User {
  const claims = account.idTokenClaims as Record<string, unknown> | undefined;
  const roles = (claims?.roles as string[] | undefined) ?? [];
  const roleMap: Record<string, UserRole> = {
    Admin: UserRole.Admin,
    ComplianceOfficer: UserRole.ComplianceOfficer,
    Auditor: UserRole.Auditor,
    Partner: UserRole.Partner,
  };
  const role = roles.reduce<UserRole>((acc, r) => roleMap[r] ?? acc, UserRole.Viewer);

  return {
    id: account.localAccountId,
    displayName: account.name ?? account.username,
    email: account.username,
    role,
    avatarUrl: undefined,
  };
}

/**
 * MsalAuthBridge — inner component that reads MSAL state and provides AuthContext.
 * Must be rendered inside MsalProvider.
 */
const MsalAuthBridge: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { instance, accounts, inProgress } = useMsal();
  const [user, setUser] = useState<User | null>(null);

  useEffect(() => {
    if (accounts.length > 0) {
      const mapped = mapAccountToUser(accounts[0]);
      setUser(mapped);
    } else {
      setUser(null);
      sessionStorage.removeItem('auth_token');
    }
  }, [accounts]);

  const login = useCallback(async (_credentials?: LoginCredentials) => {
    await instance.loginRedirect(loginRequest);
  }, [instance]);

  const logout = useCallback(() => {
    sessionStorage.removeItem('auth_token');
    instance.logoutRedirect({ postLogoutRedirectUri: window.location.origin });
  }, [instance]);

  const getAccessToken = useCallback(async (): Promise<string | null> => {
    const account = accounts[0];
    if (!account) return null;
    try {
      const result = await instance.acquireTokenSilent({ ...apiRequest, account });
      sessionStorage.setItem('auth_token', result.accessToken);
      return result.accessToken;
    } catch (err) {
      if (err instanceof InteractionRequiredAuthError) {
        await instance.acquireTokenRedirect({ ...apiRequest, account });
      }
      return null;
    }
  }, [instance, accounts]);

  return (
    <AuthContext.Provider value={{
      user,
      isAuthenticated: !!user && accounts.length > 0,
      isLoading: inProgress !== 'none',
      login,
      logout,
      getAccessToken,
    }}>
      {children}
    </AuthContext.Provider>
  );
};

/**
 * MsalAuthProvider — wraps MsalProvider (required by @azure/msal-react hooks)
 * and the bridge that translates MSAL state into AuthContext.
 */
const MsalAuthProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <MsalProvider instance={msalInstance}>
    <MsalAuthBridge>{children}</MsalAuthBridge>
  </MsalProvider>
);

// ─── Public AuthProvider — switches adapter based on build flag ───────────────

// USE_MOCK_AUTH is injected by webpack DefinePlugin; default to true for safety.
const USE_MOCK = typeof (process.env as any).USE_MOCK_AUTH !== 'undefined'
  ? String((process.env as any).USE_MOCK_AUTH) === 'true'
  : true;

/**
 * AuthProvider — Use this in every app's bootstrap.tsx.
 * Automatically selects Mock or MSAL adapter based on the USE_MOCK_AUTH build-time env var.
 * @accessibility No direct UI — provides context only.
 */
export const AuthProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  if (USE_MOCK) {
    return <MockAuthProvider>{children}</MockAuthProvider>;
  }
  return <MsalAuthProvider>{children}</MsalAuthProvider>;
};

/**
 * Hook to access auth context from any component.
 * @throws Error if used outside AuthProvider.
 */
export const useAuth = (): AuthContextType => {
  const context = useContext(AuthContext);
  if (!context) {
    throw new Error('useAuth must be used within an AuthProvider');
  }
  return context;
};
