// Generated by GitHub Copilot
/**
 * usePermission — Hook for checking user permissions on specific actions/resources.
 * @security Enforces role-based access control at the component level.
 */
import { useAuth } from './AuthProvider';
import { UserRole } from '@shared/types';

interface PermissionMap {
  [resource: string]: {
    [action: string]: UserRole[];
  };
}

// Generated by GitHub Copilot
/** Define which roles can perform which actions on which resources */
const PERMISSION_MATRIX: PermissionMap = {
  risk: {
    view: [UserRole.Admin, UserRole.Auditor, UserRole.ComplianceOfficer, UserRole.Partner, UserRole.Viewer],
    create: [UserRole.Admin, UserRole.ComplianceOfficer],
    edit: [UserRole.Admin, UserRole.ComplianceOfficer],
    delete: [UserRole.Admin],
    approve: [UserRole.Admin, UserRole.ComplianceOfficer],
  },
  compliance: {
    view: [UserRole.Admin, UserRole.Auditor, UserRole.ComplianceOfficer, UserRole.Partner, UserRole.Viewer],
    edit: [UserRole.Admin, UserRole.ComplianceOfficer],
    assess: [UserRole.Admin, UserRole.ComplianceOfficer, UserRole.Auditor],
  },
  audit: {
    view: [UserRole.Admin, UserRole.Auditor, UserRole.ComplianceOfficer, UserRole.Viewer],
    create: [UserRole.Admin, UserRole.Auditor],
    edit: [UserRole.Admin, UserRole.Auditor],
    close: [UserRole.Admin, UserRole.Auditor],
  },
  policy: {
    view: [UserRole.Admin, UserRole.ComplianceOfficer, UserRole.Partner, UserRole.Viewer],
    create: [UserRole.Admin, UserRole.ComplianceOfficer],
    approve: [UserRole.Admin],
    publish: [UserRole.Admin],
  },
  incident: {
    view: [UserRole.Admin, UserRole.ComplianceOfficer, UserRole.Partner, UserRole.Viewer],
    report: [UserRole.Admin, UserRole.ComplianceOfficer, UserRole.Partner],
    investigate: [UserRole.Admin, UserRole.ComplianceOfficer],
    resolve: [UserRole.Admin, UserRole.ComplianceOfficer],
  },
  vendor: {
    view: [UserRole.Admin, UserRole.ComplianceOfficer, UserRole.Viewer],
    create: [UserRole.Admin, UserRole.ComplianceOfficer],
    assess: [UserRole.Admin, UserRole.ComplianceOfficer, UserRole.Auditor],
    edit: [UserRole.Admin, UserRole.ComplianceOfficer],
  },
  partner: {
    view: [UserRole.Admin, UserRole.Partner, UserRole.Viewer],
    onboard: [UserRole.Admin, UserRole.Partner],
    approve: [UserRole.Admin],
    bulkInvite: [UserRole.Admin],
  },
};

/**
 * Check whether the current user has permission for a specific action on a resource.
 * @param action - The action to check (e.g., 'create', 'edit', 'delete')
 * @param resource - The resource to check against (e.g., 'risk', 'audit')
 * @returns boolean indicating permission
 */
export function usePermission(action: string, resource: string): boolean {
  const { user } = useAuth();
  if (!user) return false;

  const resourcePermissions = PERMISSION_MATRIX[resource];
  if (!resourcePermissions) return false;

  const allowedRoles = resourcePermissions[action];
  if (!allowedRoles) return false;

  return allowedRoles.includes(user.role);
}
