// Generated by GitHub Copilot
import { renderHook } from '@testing-library/react';
import { vi, describe, it, expect, beforeEach } from 'vitest';
import { usePermission } from './usePermission';
import { UserRole } from '@shared/types';

const mockUseAuth = vi.fn();
vi.mock('./AuthProvider', () => ({ useAuth: () => mockUseAuth() }));

describe('usePermission', () => {
    beforeEach(() => { vi.clearAllMocks(); });

    describe('unauthenticated user', () => {
        it('returns false when no user is logged in', () => {
            mockUseAuth.mockReturnValue({ user: null });
            const { result } = renderHook(() => usePermission('view', 'risk'));
            expect(result.current).toBe(false);
        });
    });

    describe('Admin role', () => {
        beforeEach(() => {
            mockUseAuth.mockReturnValue({
                user: { id: '1', displayName: 'Admin', role: UserRole.Admin },
            });
        });

        it('can view risk', () => {
            const { result } = renderHook(() => usePermission('view', 'risk'));
            expect(result.current).toBe(true);
        });

        it('can delete risk', () => {
            const { result } = renderHook(() => usePermission('delete', 'risk'));
            expect(result.current).toBe(true);
        });

        it('can approve policy', () => {
            const { result } = renderHook(() => usePermission('approve', 'policy'));
            expect(result.current).toBe(true);
        });
    });

    describe('Viewer role', () => {
        beforeEach(() => {
            mockUseAuth.mockReturnValue({
                user: { id: '2', displayName: 'Viewer', role: UserRole.Viewer },
            });
        });

        it('can view risk', () => {
            const { result } = renderHook(() => usePermission('view', 'risk'));
            expect(result.current).toBe(true);
        });

        it('cannot delete risk', () => {
            const { result } = renderHook(() => usePermission('delete', 'risk'));
            expect(result.current).toBe(false);
        });

        it('cannot create incidents', () => {
            const { result } = renderHook(() => usePermission('report', 'incident'));
            expect(result.current).toBe(false);
        });
    });

    describe('Partner role', () => {
        beforeEach(() => {
            mockUseAuth.mockReturnValue({
                user: { id: '3', displayName: 'Partner', role: UserRole.Partner },
            });
        });

        it('can report incidents', () => {
            const { result } = renderHook(() => usePermission('report', 'incident'));
            expect(result.current).toBe(true);
        });

        it('cannot assess vendor', () => {
            const { result } = renderHook(() => usePermission('assess', 'vendor'));
            expect(result.current).toBe(false);
        });
    });

    describe('unknown resource or action', () => {
        it('returns false for unknown resource', () => {
            mockUseAuth.mockReturnValue({
                user: { id: '1', displayName: 'Admin', role: UserRole.Admin },
            });
            const { result } = renderHook(() => usePermission('view', 'unknown-resource'));
            expect(result.current).toBe(false);
        });

        it('returns false for unknown action on known resource', () => {
            mockUseAuth.mockReturnValue({
                user: { id: '1', displayName: 'Admin', role: UserRole.Admin },
            });
            const { result } = renderHook(() => usePermission('fly', 'risk'));
            expect(result.current).toBe(false);
        });
    });
});
