
/**
 * App — Root layout component for the Shell application.
 * Orchestrates Header, SideNav, and routed micro-app content area.
 * @accessibility Full keyboard navigation, skip links, landmark regions.
 */
import React, { Suspense, useRef } from 'react';
import { Routes, Route, Navigate, useLocation, useNavigate } from 'react-router-dom';
import Box from '@mui/material/Box';
import Skeleton from '@mui/material/Skeleton';
import Header from './components/Header';
import SideNav from './components/SideNav';
import ErrorBoundary from './components/ErrorBoundary';
import EventDebugPanel from './components/EventDebugPanel';
import HomePage from './components/home/HomePage';
import { themeTokens } from '@shared/ui-components';
import { ProtectedRoute } from '@shared/auth';
import { AppEvent, useEventBus } from '@shared/event-bus';
import { UserRole } from '@shared/types';
import { useSidebar } from './providers';


/** Lazy-loaded remote micro-app modules via Module Federation */
const RiskAssessment = React.lazy(() => import('riskAssessment/Module'));
const ComplianceDashboard = React.lazy(() => import('complianceDashboard/Module'));
const AuditManagement = React.lazy(() => import('auditManagement/Module'));
const PolicyManagement = React.lazy(() => import('policyManagement/Module'));
const IncidentReporting = React.lazy(() => import('incidentReporting/Module'));
const VendorRisk = React.lazy(() => import('vendorRisk/Module'));
const PartnerOnboarding = React.lazy(() => import('partnerOnboarding/Module'));
const FALLBACK_TABLE_ROW_COUNT = 10;

// Generated by GitHub Copilot
const ALLOWED_NAV_ROOTS = new Set([
    '/',
    '/home',
    '/risk-assessment',
    '/compliance',
    '/audit',
    '/policy',
    '/incidents',
    '/vendor-risk',
    '/onboarding',
    '/event-debug',
]);

/**
 * Validates and normalizes event-driven navigation paths.
 * @security Allows only known in-portal route roots to prevent open redirects.
 */
function sanitizeNavigationPath(path: string): string | null {
    if (typeof path !== 'string') return null;

    const trimmed = path.trim();
    if (!trimmed.startsWith('/') || trimmed.startsWith('//') || trimmed.includes('://')) {
        return null;
    }

    const pathname = trimmed.split(/[?#]/)[0];
    const root = `/${pathname.split('/').filter(Boolean)[0] ?? ''}`;

    if (!ALLOWED_NAV_ROOTS.has(root)) {
        return null;
    }

    return trimmed;
}

// Generated by GitHub Copilot
/**
 * Skeleton placeholder shown while a lazy micro-app module is loading.
 * @accessibility role="status" + aria-live keeps assistive tech informed without intrusive announcements.
 */
const LoadingFallback = () => (
    <Box role="status" aria-live="polite" aria-label="Loading module" sx={{ p: 2.5, display: 'grid', gap: 2 }}>
        <Box sx={{ display: 'grid', gap: 0.75 }}>
            <Skeleton variant="text" width={320} height={40} />
            <Skeleton variant="text" width={220} height={24} />
        </Box>

        <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'repeat(4, minmax(0, 1fr))' }, gap: 1.5 }}>
            {Array.from({ length: 4 }).map((_, cardIndex) => (
                <Box key={`kpi-skeleton-${cardIndex}`} sx={{ p: 1.5, border: '1px solid', borderColor: 'divider', borderRadius: 1.5 }}>
                    <Skeleton variant="text" width="58%" height={18} />
                    <Skeleton variant="text" width="46%" height={36} />
                    <Skeleton variant="text" width="40%" height={18} />
                </Box>
            ))}
        </Box>

        <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', lg: '1.6fr 1fr' }, gap: 1.5 }}>
            <Skeleton variant="rectangular" height={220} sx={{ borderRadius: 1.5 }} />
            <Skeleton variant="rectangular" height={220} sx={{ borderRadius: 1.5 }} />
        </Box>

        <Box sx={{ border: '1px solid', borderColor: 'divider', borderRadius: 1.5, overflow: 'hidden' }}>
            <Box sx={{ p: 1.5, borderBottom: '1px solid', borderColor: 'divider' }}>
                <Skeleton variant="text" width={190} height={28} />
            </Box>

            <Box
                sx={{
                    px: 1.5,
                    py: 1,
                    display: 'grid',
                    gridTemplateColumns: '1.6fr 1fr 1fr 1fr 0.9fr',
                    gap: 1,
                    borderBottom: '1px solid',
                    borderColor: 'divider',
                }}
            >
                {Array.from({ length: 5 }).map((_, headIndex) => (
                    <Skeleton key={`table-head-${headIndex}`} variant="text" width="85%" height={18} />
                ))}
            </Box>

            <Box sx={{ px: 1.5, pb: 0.5 }}>
                {Array.from({ length: FALLBACK_TABLE_ROW_COUNT }).map((_, rowIndex) => (
                    <Box
                        key={`table-row-${rowIndex}`}
                        sx={{
                            py: 1,
                            display: 'grid',
                            gridTemplateColumns: '1.6fr 1fr 1fr 1fr 0.9fr',
                            gap: 1,
                            borderBottom: rowIndex === FALLBACK_TABLE_ROW_COUNT - 1 ? 'none' : '1px solid',
                            borderColor: 'divider',
                        }}
                    >
                        {Array.from({ length: 5 }).map((_, cellIndex) => (
                            <Skeleton
                                key={`table-row-${rowIndex}-cell-${cellIndex}`}
                                variant="text"
                                width={cellIndex === 0 ? '92%' : '70%'}
                                height={22}
                            />
                        ))}
                    </Box>
                ))}
            </Box>
        </Box>
    </Box>
);

const App: React.FC = () => {
    const { open: sidebarOpen, setOpen: setSidebarOpen } = useSidebar();
    const location = useLocation();
    const navigate = useNavigate();
    const lastNavigationRef = useRef<{ path: string; timestamp: number }>({ path: '', timestamp: 0 });

    useEventBus(AppEvent.NavigationRequested, ({ path }) => {
        const targetPath = sanitizeNavigationPath(path);
        if (!targetPath) {
            return;
        }

        const targetPathname = targetPath.split(/[?#]/)[0];
        if (location.pathname === targetPathname) {
            return;
        }

        const now = Date.now();
        if (
            lastNavigationRef.current.path === targetPath
            && now - lastNavigationRef.current.timestamp < 400
        ) {
            return;
        }

        lastNavigationRef.current = { path: targetPath, timestamp: now };
        navigate(targetPath, { flushSync: true });
    });

    return (
        <Box sx={{ display: 'flex', flexDirection: 'column', minHeight: '100vh', bgcolor: 'background.default' }}>
            <Header />
            <Box sx={{ display: 'flex', flex: 1 }}>
                <SideNav open={sidebarOpen} onOpenChange={setSidebarOpen} />
                <Box
                    component="main"
                    id="main-content"
                    role="main"
                    sx={{
                        flex: 1,
                        marginTop: `${themeTokens.layout.headerHeight}px`,
                        px: { xs: 1, sm: 3, md: 8 },
                        py: { xs: 1, sm: 3, md: 5 },
                        minHeight: `calc(100vh - ${themeTokens.layout.headerHeight}px)`,
                        overflow: 'auto',
                        bgcolor: 'background.default',
                    }}
                >
                    <Routes location={location} key={location.pathname}>
                        <Route
                            path="/"
                            element={
                                <ProtectedRoute>
                                    <HomePage />
                                </ProtectedRoute>
                            }
                        />
                        <Route path="/home" element={<Navigate to="/" replace />} />
                        <Route
                            path="/risk-assessment/*"
                            element={
                                <ProtectedRoute>
                                    <ErrorBoundary moduleName="Risk Assessment">
                                        <Suspense fallback={<LoadingFallback />}>
                                            <RiskAssessment />
                                        </Suspense>
                                    </ErrorBoundary>
                                </ProtectedRoute>
                            }
                        />
                        <Route
                            path="/compliance/*"
                            element={
                                <ProtectedRoute>
                                    <ErrorBoundary moduleName="Compliance Dashboard">
                                        <Suspense fallback={<LoadingFallback />}>
                                            <ComplianceDashboard />
                                        </Suspense>
                                    </ErrorBoundary>
                                </ProtectedRoute>
                            }
                        />
                        <Route
                            path="/audit/*"
                            element={
                                <ProtectedRoute>
                                    <ErrorBoundary moduleName="Audit Management">
                                        <Suspense fallback={<LoadingFallback />}>
                                            <AuditManagement />
                                        </Suspense>
                                    </ErrorBoundary>
                                </ProtectedRoute>
                            }
                        />
                        <Route
                            path="/policy/*"
                            element={
                                <ProtectedRoute>
                                    <ErrorBoundary moduleName="Policy Management">
                                        <Suspense fallback={<LoadingFallback />}>
                                            <PolicyManagement />
                                        </Suspense>
                                    </ErrorBoundary>
                                </ProtectedRoute>
                            }
                        />
                        <Route
                            path="/incidents/*"
                            element={
                                <ProtectedRoute>
                                    <ErrorBoundary moduleName="Incident Reporting">
                                        <Suspense fallback={<LoadingFallback />}>
                                            <IncidentReporting />
                                        </Suspense>
                                    </ErrorBoundary>
                                </ProtectedRoute>
                            }
                        />
                        <Route
                            path="/vendor-risk/*"
                            element={
                                <ProtectedRoute>
                                    <ErrorBoundary moduleName="Vendor Risk Management">
                                        <Suspense fallback={<LoadingFallback />}>
                                            <VendorRisk />
                                        </Suspense>
                                    </ErrorBoundary>
                                </ProtectedRoute>
                            }
                        />
                        <Route
                            path="/onboarding/*"
                            element={
                                <ProtectedRoute>
                                    <ErrorBoundary moduleName="Partner Onboarding">
                                        <Suspense fallback={<LoadingFallback />}>
                                            <PartnerOnboarding />
                                        </Suspense>
                                    </ErrorBoundary>
                                </ProtectedRoute>
                            }
                        />
                        <Route
                            path="/event-debug"
                            element={
                                <ProtectedRoute requiredRoles={[UserRole.Admin, UserRole.Auditor, UserRole.ComplianceOfficer]}>
                                    <EventDebugPanel />
                                </ProtectedRoute>
                            }
                        />
                        <Route
                            path="*"
                            element={
                                <div style={{ textAlign: 'center', padding: '4rem' }}>
                                    <h2>404 — Page Not Found</h2>
                                    <p>The page you requested does not exist.</p>
                                </div>
                            }
                        />
                    </Routes>
                </Box>
            </Box>
        </Box>
    );
};

export default App;
