// Generated by GitHub Copilot
/**
 * App — Root layout component for the Shell application.
 * Orchestrates Header, SideNav, and routed micro-app content area.
 * @accessibility Full keyboard navigation, skip links, landmark regions.
 */
import React, { Suspense, useState } from 'react';
import { Routes, Route, Navigate } from 'react-router-dom';
import Box from '@mui/material/Box';
import Header from './components/Header';
import SideNav from './components/SideNav';
import ErrorBoundary from './components/ErrorBoundary';
import { themeTokens } from '@shared/ui-components';
import { ProtectedRoute } from '@shared/auth';

// Generated by GitHub Copilot
/** Lazy-loaded remote micro-app modules via Module Federation */
const RiskAssessment = React.lazy(() => import('riskAssessment/Module'));
const ComplianceDashboard = React.lazy(() => import('complianceDashboard/Module'));
const AuditManagement = React.lazy(() => import('auditManagement/Module'));
const PolicyManagement = React.lazy(() => import('policyManagement/Module'));
const IncidentReporting = React.lazy(() => import('incidentReporting/Module'));
const VendorRisk = React.lazy(() => import('vendorRisk/Module'));
const PartnerOnboarding = React.lazy(() => import('partnerOnboarding/Module'));

const LoadingFallback = () => (
    <div role="status" aria-live="polite" style={{ padding: '3rem', textAlign: 'center', color: 'var(--color-text-secondary)' }}>
        <p>Loading module...</p>
    </div>
);

const App: React.FC = () => {
    const [sidebarOpen, setSidebarOpen] = useState(true);

    return (
        <Box sx={{ display: 'flex', flexDirection: 'column', minHeight: '100vh', bgcolor: 'background.default' }}>
            <Header />
            <Box sx={{ display: 'flex', flex: 1 }}>
                <SideNav open={sidebarOpen} onOpenChange={setSidebarOpen} />
                <Box
                    component="main"
                    id="main-content"
                    role="main"
                    sx={{
                        flex: 1,
                        marginTop: `${themeTokens.layout.headerHeight}px`,
                        padding: '1.5rem 2rem',
                        minHeight: `calc(100vh - ${themeTokens.layout.headerHeight}px)`,
                        overflow: 'auto',
                        bgcolor: 'background.default',
                    }}
                >
                    <Routes>
                        <Route path="/" element={<Navigate to="/risk-assessment" replace />} />
                        <Route
                            path="/risk-assessment/*"
                            element={
                                <ProtectedRoute>
                                    <ErrorBoundary moduleName="Risk Assessment">
                                        <Suspense fallback={<LoadingFallback />}>
                                            <RiskAssessment />
                                        </Suspense>
                                    </ErrorBoundary>
                                </ProtectedRoute>
                            }
                        />
                        <Route
                            path="/compliance/*"
                            element={
                                <ProtectedRoute>
                                    <ErrorBoundary moduleName="Compliance Dashboard">
                                        <Suspense fallback={<LoadingFallback />}>
                                            <ComplianceDashboard />
                                        </Suspense>
                                    </ErrorBoundary>
                                </ProtectedRoute>
                            }
                        />
                        <Route
                            path="/audit/*"
                            element={
                                <ProtectedRoute>
                                    <ErrorBoundary moduleName="Audit Management">
                                        <Suspense fallback={<LoadingFallback />}>
                                            <AuditManagement />
                                        </Suspense>
                                    </ErrorBoundary>
                                </ProtectedRoute>
                            }
                        />
                        <Route
                            path="/policy/*"
                            element={
                                <ProtectedRoute>
                                    <ErrorBoundary moduleName="Policy Management">
                                        <Suspense fallback={<LoadingFallback />}>
                                            <PolicyManagement />
                                        </Suspense>
                                    </ErrorBoundary>
                                </ProtectedRoute>
                            }
                        />
                        <Route
                            path="/incidents/*"
                            element={
                                <ProtectedRoute>
                                    <ErrorBoundary moduleName="Incident Reporting">
                                        <Suspense fallback={<LoadingFallback />}>
                                            <IncidentReporting />
                                        </Suspense>
                                    </ErrorBoundary>
                                </ProtectedRoute>
                            }
                        />
                        <Route
                            path="/vendor-risk/*"
                            element={
                                <ProtectedRoute>
                                    <ErrorBoundary moduleName="Vendor Risk Management">
                                        <Suspense fallback={<LoadingFallback />}>
                                            <VendorRisk />
                                        </Suspense>
                                    </ErrorBoundary>
                                </ProtectedRoute>
                            }
                        />
                        <Route
                            path="/onboarding/*"
                            element={
                                <ProtectedRoute>
                                    <ErrorBoundary moduleName="Partner Onboarding">
                                        <Suspense fallback={<LoadingFallback />}>
                                            <PartnerOnboarding />
                                        </Suspense>
                                    </ErrorBoundary>
                                </ProtectedRoute>
                            }
                        />
                        <Route
                            path="*"
                            element={
                                <div style={{ textAlign: 'center', padding: '4rem' }}>
                                    <h2>404 — Page Not Found</h2>
                                    <p>The page you requested does not exist.</p>
                                </div>
                            }
                        />
                    </Routes>
                </Box>
            </Box>
        </Box>
    );
};

export default App;
