
/**
 * Bootstrap — Renders the root React application.
 * Separated from index.ts to support Module Federation async loading.
 */
import React from 'react';
import { createRoot } from 'react-dom/client';
import { RouterProvider } from 'react-router-dom';
import { PortalThemeProvider } from '@shared/ui-components';
import { router } from './router';
import { AppProviders } from './providers';

const MIN_PRELOADER_DISPLAY_MS = 900;

const rootElement = document.getElementById('root');
if (!rootElement) throw new Error('Root element not found');

const root = createRoot(rootElement);

// Generated by GitHub Copilot
const preloaderStartedAt = Number(
    (window as Window & { __PARTNER_PORTAL_PRELOADER_STARTED_AT__?: number }).__PARTNER_PORTAL_PRELOADER_STARTED_AT__
    ?? Date.now(),
);

const elapsedMs = Math.max(0, Date.now() - preloaderStartedAt);
const remainingDelayMs = Math.max(0, MIN_PRELOADER_DISPLAY_MS - elapsedMs);

/**
 * Mounts the shell app once the minimum preloader display time has elapsed.
 */
const mountApp = () => {
    root.render(
        <React.StrictMode>
            <PortalThemeProvider>
                <AppProviders>
                    <RouterProvider router={router} />
                </AppProviders>
            </PortalThemeProvider>
        </React.StrictMode>
    );
};

if (remainingDelayMs > 0) {
    window.setTimeout(mountApp, remainingDelayMs);
} else {
    mountApp();
}
