// Generated by GitHub Copilot
import React from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import { AuthProvider } from '@shared/auth';
import RiskAssessmentApp from './remote-entry';

const rootElement = document.getElementById('root');
if (!rootElement) throw new Error('Root element not found');

const root = createRoot(rootElement);
root.render(
    <React.StrictMode>
        <BrowserRouter>
            <AuthProvider>
                <RiskAssessmentApp />
            </AuthProvider>
        </BrowserRouter>
    </React.StrictMode>
);
