
import React from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import { AuthProvider } from '@shared/auth';
import { PortalThemeProvider } from '@shared/ui-components';
import RiskAssessmentApp from './remote-entry';

const rootElement = document.getElementById('root');
if (!rootElement) throw new Error('Root element not found');

const root = createRoot(rootElement);
// Generated by GitHub Copilot
root.render(
    <React.StrictMode>
        <PortalThemeProvider>
            <BrowserRouter>
                <AuthProvider>
                    <RiskAssessmentApp />
                </AuthProvider>
            </BrowserRouter>
        </PortalThemeProvider>
    </React.StrictMode>
);
