// Generated by GitHub Copilot
/**
 * AgenticChatPage - Shell-owned slide drawer with role-aware scope selection.
 * Provides a VS Code-like session list + conversation workspace experience.
 */
import React, { useCallback, useEffect, useMemo, useState } from 'react';
import Box from '@mui/material/Box';
import Checkbox from '@mui/material/Checkbox';
import Collapse from '@mui/material/Collapse';
import CircularProgress from '@mui/material/CircularProgress';
import Divider from '@mui/material/Divider';
import Drawer from '@mui/material/Drawer';
import FormControlLabel from '@mui/material/FormControlLabel';
import IconButton from '@mui/material/IconButton';
import Popover from '@mui/material/Popover';
import TextField from '@mui/material/TextField';
import Tooltip from '@mui/material/Tooltip';
import Typography from '@mui/material/Typography';
import { useTheme } from '@mui/material/styles';
import CloseIcon from '@mui/icons-material/Close';
import RefreshIcon from '@mui/icons-material/Refresh';
import SearchIcon from '@mui/icons-material/Search';
import TuneIcon from '@mui/icons-material/Tune';
import ViewSidebarIcon from '@mui/icons-material/ViewSidebar';
import { Button, Card, themeTokens } from '@shared/ui-components';
import { AppEvent, eventBus } from '@shared/event-bus';
import { getAccessibleModules, useAuth } from '@shared/auth';
import {
  type ChatModelId,
  type ChatScope,
  type ChatThread,
  getChatModelDescription,
  getChatModelLabel,
  getRecommendedChatModelId,
  getChatScopeLabel,
  getSelectableChatModels,
  getSelectableChatScopes,
} from './chatRuntime';
import {
  appendMessage,
  listThreads,
  waitForTaskResult,
} from './chatBackendMock';

type SessionFilter = 'all' | 'running' | 'failed' | 'completed';
const DARK_CHAT_SURFACE_BG = '#121212';
const SESSION_PREVIEW_LIMIT = 2;

export interface AgenticChatPageProps {
  open: boolean;
  onClose: () => void;
}

/**
 * Provides a short local timestamp for session and message metadata.
 */
function formatLocalTime(isoTime: string): string {
  const parsed = new Date(isoTime);
  if (Number.isNaN(parsed.getTime())) {
    return 'Unknown time';
  }

  return parsed.toLocaleString();
}

/**
 * Ensures scope selection always stays within role-visible scopes.
 */
function sanitizeScopeSelection(
  requestedScopes: readonly ChatScope[],
  roleVisibleScopes: readonly ChatScope[]
): ChatScope[] {
  const roleVisibleSet = new Set(roleVisibleScopes);
  const filtered = requestedScopes.filter((scope) => roleVisibleSet.has(scope));

  if (filtered.length > 0 || roleVisibleScopes.length === 0) {
    return filtered;
  }

  // Default to all role-authorized scopes so plugin matching can use full permitted context.
  return [...roleVisibleScopes];
}

/**
 * Upserts one thread into local UI state, keeping recent ordering semantics.
 */
function upsertThreadInState(existing: ChatThread[], incoming: ChatThread): ChatThread[] {
  const withoutIncoming = existing.filter((thread) => thread.id !== incoming.id);
  return [incoming, ...withoutIncoming].sort((left, right) => right.updatedAt.localeCompare(left.updatedAt));
}

/**
 * Derives a simple session status from the most recent status-bearing message.
 */
function getSessionStatus(thread: ChatThread): Exclude<SessionFilter, 'all'> {
  for (let index = thread.messages.length - 1; index >= 0; index -= 1) {
    const status = thread.messages[index]?.status;
    if (status === 'running') {
      return 'running';
    }

    if (status === 'failed') {
      return 'failed';
    }

    if (status === 'completed') {
      return 'completed';
    }
  }

  return 'completed';
}

/**
 * Maps session status values to user-facing labels.
 */
function getSessionStatusLabel(status: Exclude<SessionFilter, 'all'>): string {
  if (status === 'running') {
    return 'Running';
  }

  if (status === 'failed') {
    return 'Failed';
  }

  return 'Ready';
}

/**
 * Maps session status values to semantic color tokens.
 */
function getSessionStatusColor(status: Exclude<SessionFilter, 'all'>): string {
  if (status === 'running') {
    return 'warning.main';
  }

  if (status === 'failed') {
    return 'error.main';
  }

  return 'success.main';
}

const AgenticChatPage: React.FC<AgenticChatPageProps> = ({ open, onClose }) => {
  const theme = useTheme();
  const { user } = useAuth();
  const activeUserId = user?.id ?? 'anonymous';

  const isDarkMode = theme.palette.mode === 'dark';
  const chatSurfaceBg = isDarkMode ? DARK_CHAT_SURFACE_BG : theme.palette.background.paper;
  const chatSurfaceBorder = isDarkMode ? 'rgba(255, 255, 255, 0.14)' : theme.palette.divider;
  const chatTimelineBg = isDarkMode ? DARK_CHAT_SURFACE_BG : theme.palette.background.default;

  const roleVisibleScopes = useMemo(() => {
    if (!user) {
      return [] as ChatScope[];
    }

    return getSelectableChatScopes(getAccessibleModules(user.role));
  }, [user]);

  const selectableModels = useMemo(() => (
    getSelectableChatModels(roleVisibleScopes)
  ), [roleVisibleScopes]);

  const [threads, setThreads] = useState<ChatThread[]>([]);
  const [selectedScopes, setSelectedScopes] = useState<ChatScope[]>([]);
  const [selectedModelId, setSelectedModelId] = useState<ChatModelId>('multi-microapp-model');
  const [focusedThreadId, setFocusedThreadId] = useState<string | null>(null);
  const [messageDraft, setMessageDraft] = useState<string>('');
  const [sessionQuery, setSessionQuery] = useState<string>('');
  const [searchDraft, setSearchDraft] = useState<string>('');
  const [sessionFilter, setSessionFilter] = useState<SessionFilter>('all');
  const [showAllSessionDetails, setShowAllSessionDetails] = useState<boolean>(false);
  const [isHydrating, setIsHydrating] = useState<boolean>(true);
  const [isRefreshing, setIsRefreshing] = useState<boolean>(false);
  const [isSending, setIsSending] = useState<boolean>(false);
  const [isSessionSidebarVisible, setIsSessionSidebarVisible] = useState<boolean>(true);
  const [isSessionSearchControlsVisible, setIsSessionSearchControlsVisible] = useState<boolean>(false);
  const [isSessionFilterControlVisible, setIsSessionFilterControlVisible] = useState<boolean>(false);
  const [contextScopeAnchorEl, setContextScopeAnchorEl] = useState<HTMLElement | null>(null);
  const [modelPickerAnchorEl, setModelPickerAnchorEl] = useState<HTMLElement | null>(null);

  const isContextScopePopoverOpen = Boolean(contextScopeAnchorEl);
  const isModelPickerPopoverOpen = Boolean(modelPickerAnchorEl);

  const chatCardSx = useMemo(() => ({
    bgcolor: chatSurfaceBg,
    border: '1px solid',
    borderColor: chatSurfaceBorder,
    boxShadow: 'none',
  }), [chatSurfaceBg, chatSurfaceBorder]);

  const chatInputSx = useMemo(() => ({
    '& .MuiInputBase-root': {
      bgcolor: chatSurfaceBg,
    },
    '& .MuiOutlinedInput-notchedOutline': {
      borderColor: chatSurfaceBorder,
    },
  }), [chatSurfaceBg, chatSurfaceBorder]);

  const activeThread = useMemo(() => {
    if (!focusedThreadId) {
      return null;
    }

    return threads.find((thread) => thread.id === focusedThreadId) ?? null;
  }, [focusedThreadId, threads]);

  const effectiveScopeSelection = activeThread?.contexts ?? selectedScopes;
  const effectiveModelSelection = useMemo<ChatModelId>(() => {
    const availableIds = new Set(selectableModels.map((model) => model.id));
    const candidate = activeThread?.modelId ?? selectedModelId;

    if (availableIds.has(candidate)) {
      return candidate;
    }

    return getRecommendedChatModelId(
      effectiveScopeSelection.length > 0 ? effectiveScopeSelection : roleVisibleScopes
    );
  }, [activeThread?.modelId, effectiveScopeSelection, roleVisibleScopes, selectableModels, selectedModelId]);

  /**
   * Splits a search query into individual terms and checks that every term
   * appears somewhere in the combined searchable text for a thread.
   * Returns a contextual excerpt from the first message whose content
   * contains any of the terms, for display in the session card.
   */
  const getThreadMatchExcerpt = useCallback((thread: ChatThread, queryTerms: string[]): string | null => {
    if (queryTerms.length === 0) {
      return null;
    }

    for (const message of thread.messages) {
      const lower = message.content.toLowerCase();
      if (queryTerms.some((term) => lower.includes(term))) {
        const matchTerm = queryTerms.find((term) => lower.includes(term)) ?? '';
        const matchIndex = lower.indexOf(matchTerm);
        const start = Math.max(0, matchIndex - 25);
        const snippet = message.content.slice(start, start + 110).trim();
        return `${start > 0 ? '\u2026' : ''}${snippet}${start + 110 < message.content.length ? '\u2026' : ''}`;
      }
    }

    return null;
  }, []);

  const visibleThreads = useMemo(() => {
    const terms = sessionQuery
      .trim()
      .toLowerCase()
      .split(/\s+/)
      .filter((term) => term.length >= 1);

    return threads.filter((thread) => {
      const status = getSessionStatus(thread);
      if (sessionFilter !== 'all' && status !== sessionFilter) {
        return false;
      }

      if (terms.length === 0) {
        return true;
      }

      const titleAndScopes = [
        thread.title,
        thread.contexts.map((scope) => getChatScopeLabel(scope)).join(' '),
      ].join(' ').toLowerCase();

      const allMessageContent = thread.messages
        .map((message) => message.content)
        .join(' ')
        .toLowerCase();

      const combined = `${titleAndScopes} ${allMessageContent}`;

      // Every search term must appear somewhere in the combined text.
      return terms.every((term) => combined.includes(term));
    });
  }, [sessionFilter, sessionQuery, threads]);

  /**
   * Reads persisted sessions from storage and keeps focused session valid.
   */
  const refreshSessions = useCallback(async (emitSuccessNotification = false): Promise<void> => {
    setIsRefreshing(true);

    try {
      const persistedThreads = await listThreads(activeUserId);
      setThreads(persistedThreads);
      setFocusedThreadId((previousThreadId) => {
        if (!previousThreadId) {
          return previousThreadId;
        }

        return persistedThreads.some((thread) => thread.id === previousThreadId)
          ? previousThreadId
          : null;
      });

      if (emitSuccessNotification) {
        eventBus.emit(AppEvent.NotificationReceived, {
          message: `Agentic sessions refreshed (${persistedThreads.length} total).`,
          type: 'info',
        });
      }
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unable to refresh sessions.';
      eventBus.emit(AppEvent.NotificationReceived, {
        message: `Session refresh failed: ${errorMessage}`,
        type: 'error',
      });
    } finally {
      setIsHydrating(false);
      setIsRefreshing(false);
    }
  }, [activeUserId]);

  useEffect(() => {
    let mounted = true;

    void (async () => {
      try {
        const persistedThreads = await listThreads(activeUserId);
        if (mounted) {
          setThreads(persistedThreads);
        }
      } finally {
        if (mounted) {
          setIsHydrating(false);
        }
      }
    })();

    return () => {
      mounted = false;
    };
  }, [activeUserId]);

  useEffect(() => {
    setSelectedScopes((previousSelection) => (
      sanitizeScopeSelection(previousSelection, roleVisibleScopes)
    ));
  }, [roleVisibleScopes]);

  useEffect(() => {
    setSelectedModelId((previousModel) => {
      const availableIds = new Set(selectableModels.map((model) => model.id));
      if (availableIds.has(previousModel)) {
        return previousModel;
      }

      return getRecommendedChatModelId(roleVisibleScopes);
    });
  }, [roleVisibleScopes, selectableModels]);

  useEffect(() => {
    if (!open) {
      return;
    }

    void refreshSessions(false);
  }, [open, refreshSessions]);

  /**
   * Handles send action through backend mock orchestration + worker execution.
   */
  const handleSendMessage = async (event: React.FormEvent<HTMLFormElement>): Promise<void> => {
    event.preventDefault();

    const trimmedPrompt = messageDraft.trim();
    if (!trimmedPrompt || isSending || roleVisibleScopes.length === 0) {
      return;
    }

    const contextsForMessage = sanitizeScopeSelection(effectiveScopeSelection, roleVisibleScopes);
    if (contextsForMessage.length === 0) {
      return;
    }

    setIsSending(true);

    try {
      const response = await appendMessage({
        threadId: activeThread?.id,
        prompt: trimmedPrompt,
        selectedScopes: contextsForMessage,
        selectedModelId: effectiveModelSelection,
        senderId: activeUserId,
      });

      setThreads((previousThreads) => upsertThreadInState(previousThreads, response.thread));
      setFocusedThreadId(response.thread.id);
      setMessageDraft('');

      try {
        const completion = await waitForTaskResult(response.task.id, activeUserId);
        setThreads((previousThreads) => upsertThreadInState(previousThreads, completion.thread));

        eventBus.emit(AppEvent.NotificationReceived, {
          message: 'Agentic chat response is ready.',
          type: 'success',
        });
      } catch (taskError) {
        const refreshedThreads = await listThreads(activeUserId);
        setThreads(refreshedThreads);

        const taskErrorMessage = taskError instanceof Error
          ? taskError.message
          : 'Worker task failed.';

        eventBus.emit(AppEvent.NotificationReceived, {
          message: `Agentic chat worker failed: ${taskErrorMessage}`,
          type: 'error',
        });
      }
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'Unable to submit chat prompt.';
      eventBus.emit(AppEvent.NotificationReceived, {
        message: `Chat orchestration request failed: ${errorMessage}`,
        type: 'error',
      });
    } finally {
      setIsSending(false);
    }
  };

  /**
   * Toggles one scope in the current role-aware selection.
   */
  const handleToggleScope = (scope: ChatScope): void => {
    const nextSelection = effectiveScopeSelection.includes(scope)
      ? effectiveScopeSelection.filter((knownScope) => knownScope !== scope)
      : [...effectiveScopeSelection, scope];

    const sanitized = sanitizeScopeSelection(nextSelection, roleVisibleScopes);

    if (activeThread) {
      setThreads((previousThreads) => previousThreads.map((thread) => (
        thread.id === activeThread.id
          ? {
            ...thread,
            contexts: sanitized,
          }
          : thread
      )));
      return;
    }

    setSelectedScopes(sanitized);
  };

  /**
   * Selects one model profile for current draft session or active thread.
   */
  const handleSelectModel = (modelId: ChatModelId): void => {
    const allowedIds = new Set(selectableModels.map((model) => model.id));
    if (!allowedIds.has(modelId)) {
      return;
    }

    if (activeThread) {
      setThreads((previousThreads) => previousThreads.map((thread) => (
        thread.id === activeThread.id
          ? {
            ...thread,
            modelId,
          }
          : thread
      )));
      return;
    }

    setSelectedModelId(modelId);
  };

  return (
    <Drawer
      anchor="right"
      open={open}
      onClose={onClose}
      ModalProps={{ keepMounted: true }}
      PaperProps={{
        sx: {
          width: { xs: '100%', lg: 920 },
          maxWidth: '100%',
          top: `${themeTokens.layout.headerHeight}px`,
          height: `calc(100vh - ${themeTokens.layout.headerHeight}px)`,
          borderLeft: '1px solid',
          borderColor: chatSurfaceBorder,
          display: 'grid',
          gridTemplateRows: 'auto 1fr',
          bgcolor: chatSurfaceBg,
        },
      }}
    >
      <Box sx={{ px: 2, py: 1.25, display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 1 }}>
        <Box>
          <Typography component="h2" variant="h6" sx={{ fontWeight: 800 }}>
            Agentic Chat
          </Typography>
          <Typography variant="caption" color="text.secondary">
            Session-aware drawer with search, filter, and refresh controls.
          </Typography>
        </Box>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
          <Button
            variant="secondary"
            size="sm"
            onClick={() => {
              setFocusedThreadId(null);
              setMessageDraft('');
            }}
            aria-label="Create a new agentic chat session"
          >
            New Session
          </Button>
          {!isSessionSidebarVisible && (
            <Tooltip title="Show recent sessions">
              <IconButton
                aria-label="Show recent sessions sidebar"
                onClick={() => setIsSessionSidebarVisible(true)}
              >
                <ViewSidebarIcon fontSize="small" />
              </IconButton>
            </Tooltip>
          )}
          <IconButton aria-label="Close agentic chat drawer" onClick={onClose}>
            <CloseIcon fontSize="small" />
          </IconButton>
        </Box>
      </Box>

      <Popover
        open={isContextScopePopoverOpen}
        anchorEl={contextScopeAnchorEl}
        onClose={() => setContextScopeAnchorEl(null)}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'left' }}
        transformOrigin={{ vertical: 'top', horizontal: 'left' }}
      >
        <Box sx={{ px: 1.5, pt: 1.25, pb: 0.75, minWidth: 300, maxWidth: 380 }}>
          <Typography variant="subtitle2" sx={{ fontWeight: 700 }}>
            Context Scope
          </Typography>
          <Typography variant="caption" color="text.secondary" sx={{ display: 'block' }}>
            Active: {effectiveScopeSelection.length > 0
              ? effectiveScopeSelection.map((scope) => getChatScopeLabel(scope)).join(', ')
              : 'none'}
          </Typography>
        </Box>

        <Divider />

        <Box sx={{ px: 1.5, py: 1, display: 'grid', gap: 0.5 }} role="group" aria-label="Select chat context modules">
          {roleVisibleScopes.length === 0 ? (
            <Typography variant="body2" color="text.secondary">
              No role-authorized modules available for chat context.
            </Typography>
          ) : (
            roleVisibleScopes.map((scope) => (
              <FormControlLabel
                key={scope}
                control={(
                  <Checkbox
                    checked={effectiveScopeSelection.includes(scope)}
                    onChange={() => handleToggleScope(scope)}
                    inputProps={{ 'aria-label': `${getChatScopeLabel(scope)} context scope` }}
                  />
                )}
                label={getChatScopeLabel(scope)}
              />
            ))
          )}
        </Box>
      </Popover>

      <Popover
        open={isModelPickerPopoverOpen}
        anchorEl={modelPickerAnchorEl}
        onClose={() => setModelPickerAnchorEl(null)}
        anchorOrigin={{ vertical: 'bottom', horizontal: 'left' }}
        transformOrigin={{ vertical: 'top', horizontal: 'left' }}
      >
        <Box sx={{ px: 1.5, pt: 1.25, pb: 0.75, minWidth: 320, maxWidth: 420 }}>
          <Typography variant="subtitle2" sx={{ fontWeight: 700 }}>
            Model Selection
          </Typography>
          <Typography variant="caption" color="text.secondary" sx={{ display: 'block' }}>
            Active: {getChatModelLabel(effectiveModelSelection)}
          </Typography>
        </Box>

        <Divider />

        <Box sx={{ px: 1.5, py: 1, display: 'grid', gap: 1 }}>
          {selectableModels.length === 0 ? (
            <Typography variant="body2" color="text.secondary">
              No model profiles are currently available.
            </Typography>
          ) : (
            <>
              <TextField
                select
                size="small"
                label="Model"
                value={effectiveModelSelection}
                onChange={(event) => handleSelectModel(event.target.value as ChatModelId)}
                SelectProps={{ native: true }}
                sx={chatInputSx}
                inputProps={{ 'aria-label': 'Select chat model profile' }}
              >
                {selectableModels.map((model) => (
                  <option key={model.id} value={model.id}>
                    {model.label}
                  </option>
                ))}
              </TextField>

              <Typography variant="caption" color="text.secondary" sx={{ display: 'block' }}>
                {getChatModelDescription(effectiveModelSelection)}
              </Typography>
            </>
          )}
        </Box>
      </Popover>

      <Divider />

      <Box
        sx={{
          display: 'grid',
          gridTemplateColumns: isSessionSidebarVisible
            ? { xs: '1fr', lg: '340px minmax(0, 1fr)' }
            : 'minmax(0, 1fr)',
          minHeight: 0,
        }}
      >
        {isSessionSidebarVisible && (
          <Box sx={{ p: 1.5, overflowY: 'auto', borderRight: { lg: '1px solid' }, borderColor: { lg: chatSurfaceBorder } }}>
            <Box>
              <Card title="Recent Sessions" sx={chatCardSx}>
                <Box sx={{ display: 'grid', gap: 1.25 }}>
                  <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 1 }}>
                    <Typography variant="caption" color="text.secondary" sx={{ display: 'block' }}>
                      Showing {visibleThreads.length} of {threads.length} session(s)
                    </Typography>

                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.25 }}>
                      <Tooltip title={isSessionSearchControlsVisible ? 'Hide search controls' : 'Show search controls'}>
                        <IconButton
                          size="small"
                          onClick={() => setIsSessionSearchControlsVisible((previous) => !previous)}
                          aria-label={isSessionSearchControlsVisible ? 'Hide session search controls' : 'Show session search controls'}
                        >
                          <SearchIcon fontSize="small" />
                        </IconButton>
                      </Tooltip>

                      <Tooltip title={isSessionFilterControlVisible ? 'Hide filter controls' : 'Show filter controls'}>
                        <IconButton
                          size="small"
                          onClick={() => setIsSessionFilterControlVisible((previous) => !previous)}
                          aria-label={isSessionFilterControlVisible ? 'Hide session filter controls' : 'Show session filter controls'}
                        >
                          <TuneIcon fontSize="small" />
                        </IconButton>
                      </Tooltip>

                      <Tooltip title="Refresh sessions">
                        <span>
                          <IconButton
                            size="small"
                            onClick={() => {
                              void refreshSessions(true);
                            }}
                            disabled={isRefreshing}
                            aria-label="Refresh agentic chat sessions"
                          >
                            {isRefreshing ? <CircularProgress size={16} aria-label="Refreshing sessions" /> : <RefreshIcon fontSize="small" />}
                          </IconButton>
                        </span>
                      </Tooltip>

                      <Tooltip title="Hide recent sessions">
                        <IconButton
                          size="small"
                          onClick={() => setIsSessionSidebarVisible(false)}
                          aria-label="Hide recent sessions sidebar"
                        >
                          <ViewSidebarIcon fontSize="small" />
                        </IconButton>
                      </Tooltip>
                    </Box>
                  </Box>

                  {sessionQuery && !isSessionSearchControlsVisible && (
                    <Typography variant="caption" color="text.secondary" sx={{ display: 'block' }}>
                      Search applied: "{sessionQuery}"
                    </Typography>
                  )}

                  {sessionFilter !== 'all' && !isSessionFilterControlVisible && (
                    <Typography variant="caption" color="text.secondary" sx={{ display: 'block' }}>
                      Filter applied: {getSessionStatusLabel(sessionFilter as Exclude<SessionFilter, 'all'>)}
                    </Typography>
                  )}

                  <Collapse in={isSessionSearchControlsVisible} unmountOnExit>
                    <Box sx={{ display: 'grid', gap: 1 }}>
                      <TextField
                        size="small"
                        label="Search"
                        placeholder="Search sessions"
                        value={searchDraft}
                        onChange={(event) => setSearchDraft(event.target.value)}
                        onKeyDown={(event) => {
                          if (event.key === 'Enter') {
                            event.preventDefault();
                            setSessionQuery(searchDraft.trim());
                          }
                        }}
                        sx={chatInputSx}
                        inputProps={{ 'aria-label': 'Search agentic chat sessions' }}
                      />

                      <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap' }}>
                        <Button
                          variant="primary"
                          size="sm"
                          onClick={() => setSessionQuery(searchDraft.trim())}
                          aria-label="Apply session search"
                        >
                          Apply
                        </Button>

                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => {
                            setSearchDraft('');
                            setSessionQuery('');
                          }}
                          disabled={!searchDraft && !sessionQuery}
                          aria-label="Clear session search"
                        >
                          Clear Search
                        </Button>
                      </Box>
                    </Box>
                  </Collapse>

                  <Collapse in={isSessionFilterControlVisible} unmountOnExit>
                    <TextField
                      select
                      size="small"
                      label="Filter"
                      value={sessionFilter}
                      onChange={(event) => setSessionFilter(event.target.value as SessionFilter)}
                      SelectProps={{ native: true }}
                      sx={chatInputSx}
                      inputProps={{ 'aria-label': 'Filter agentic chat sessions' }}
                    >
                      <option value="all">All Sessions</option>
                      <option value="running">Running</option>
                      <option value="failed">Failed</option>
                      <option value="completed">Ready</option>
                    </TextField>
                  </Collapse>

                  {visibleThreads.length > SESSION_PREVIEW_LIMIT && (
                    <Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap' }}>
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => setShowAllSessionDetails((previous) => !previous)}
                        aria-label="Toggle full recent session details"
                      >
                        {showAllSessionDetails ? 'Minimize Older Sessions' : 'Expand Older Sessions'}
                      </Button>
                    </Box>
                  )}

                  {isHydrating ? (
                    <Typography variant="body2" color="text.secondary">
                      Loading sessions...
                    </Typography>
                  ) : visibleThreads.length === 0 ? (
                    <Typography variant="body2" color="text.secondary">
                      {threads.length === 0
                        ? 'No sessions yet. Send your first message to start one.'
                        : 'No sessions match your current search or filter.'}
                    </Typography>
                  ) : (
                    <Box component="ul" sx={{ listStyle: 'none', p: 0, m: 0, display: 'grid', gap: 1 }}>
                      {visibleThreads.map((thread, index) => {
                        const selected = activeThread?.id === thread.id;
                        const lastMessage = thread.messages[thread.messages.length - 1];
                        const status = getSessionStatus(thread);
                        const isCondensedSession = !showAllSessionDetails && index >= SESSION_PREVIEW_LIMIT;
                        const activeQuery = sessionQuery.trim();
                        const queryTerms = activeQuery.length > 0
                          ? activeQuery.toLowerCase().split(/\s+/).filter((t) => t.length >= 1)
                          : [];
                        const matchExcerpt = getThreadMatchExcerpt(thread, queryTerms);
                        const previewText = matchExcerpt ?? (lastMessage ? lastMessage.content.slice(0, 80) : null);

                        return (
                          <Box
                            key={thread.id}
                            component="li"
                            sx={{
                              border: '1px solid',
                              borderColor: selected ? 'secondary.main' : chatSurfaceBorder,
                              borderRadius: 1,
                              overflow: 'hidden',
                            }}
                          >
                            <Box
                              component="button"
                              type="button"
                              onClick={() => setFocusedThreadId(thread.id)}
                              aria-label={`Open session ${thread.title}`}
                              sx={{
                                width: '100%',
                                border: 0,
                                textAlign: 'left',
                                p: 1.25,
                                bgcolor: selected ? 'action.selected' : 'background.paper',
                                cursor: 'pointer',
                                '&:hover': { bgcolor: 'action.hover' },
                                '&:focus-visible': {
                                  outline: '2px solid',
                                  outlineColor: 'secondary.main',
                                  outlineOffset: '-2px',
                                },
                              }}
                            >
                              <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 1 }}>
                                <Typography variant="body2" sx={{ fontWeight: 700 }}>
                                  {thread.title}
                                </Typography>
                                <Typography variant="caption" sx={{ color: getSessionStatusColor(status), fontWeight: 700 }}>
                                  {getSessionStatusLabel(status)}
                                </Typography>
                              </Box>

                              {!isCondensedSession && previewText && (
                                <Typography
                                  variant="caption"
                                  color={matchExcerpt ? 'secondary.main' : 'text.secondary'}
                                  sx={{ display: 'block', fontStyle: matchExcerpt ? 'italic' : 'normal' }}
                                >
                                  {previewText}
                                </Typography>
                              )}

                              {!isCondensedSession && (
                                <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 0.25 }}>
                                  Updated {formatLocalTime(thread.updatedAt)}
                                </Typography>
                              )}
                            </Box>
                          </Box>
                        );
                      })}
                    </Box>
                  )}
                </Box>
              </Card>
            </Box>
          </Box>
        )}

        <Box sx={{ p: 1.5, display: 'grid', minHeight: 0, overflow: 'hidden' }}>
          <Card
            sx={{
              ...chatCardSx,
              minHeight: 0,
              height: '100%',
              '& .MuiCardContent-root': {
                minHeight: 0,
                height: '100%',
                display: 'flex',
                flexDirection: 'column',
              },
            }}
          >
            <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 0.75, mb: 1.25 }}>
              <Typography variant="h6" component="h3" fontWeight={600}>
                {activeThread ? activeThread.title : 'New Session'}
              </Typography>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.75 }}>
                <Tooltip
                  title="Context Scope chooses which role-authorized modules are used as chat context. This helps the assistant select relevant plugins and responses."
                  arrow
                >
                  <span>
                    <Button
                      variant="secondary"
                      size="sm"
                      onClick={(event) => setContextScopeAnchorEl(event.currentTarget)}
                      aria-label="Context Scope"
                      aria-haspopup="dialog"
                      aria-expanded={isContextScopePopoverOpen ? 'true' : undefined}
                    >
                      Context Scope
                    </Button>
                  </span>
                </Tooltip>

                <Tooltip
                  title="Model Selection chooses the AI profile: one model per microapp plus a unified multi-microapp model for cross-domain prompts."
                  arrow
                >
                  <span>
                    <Button
                      variant="secondary"
                      size="sm"
                      onClick={(event) => setModelPickerAnchorEl(event.currentTarget)}
                      aria-label="Model Selection"
                      aria-haspopup="dialog"
                      aria-expanded={isModelPickerPopoverOpen ? 'true' : undefined}
                    >
                      Model
                    </Button>
                  </span>
                </Tooltip>
              </Box>
            </Box>
            <Box
              role="log"
              aria-live="polite"
              aria-label="Conversation timeline"
              sx={{
                flex: 1,
                minHeight: 0,
                border: '1px solid',
                borderColor: chatSurfaceBorder,
                borderRadius: 1,
                p: 1,
                overflowY: 'auto',
                display: 'grid',
                gap: 1,
                mb: 1.5,
                bgcolor: chatTimelineBg,
              }}
            >
              {activeThread ? (
                activeThread.messages.map((message) => {
                  const isUserMessage = message.role === 'user';
                  return (
                    <Box
                      key={message.id}
                      sx={{
                        justifySelf: isUserMessage ? 'end' : 'start',
                        maxWidth: '85%',
                        p: 1,
                        borderRadius: 1,
                        border: '1px solid',
                        borderColor: isUserMessage ? 'primary.main' : chatSurfaceBorder,
                        bgcolor: isUserMessage ? 'primary.main' : chatSurfaceBg,
                        color: isUserMessage ? 'primary.contrastText' : 'text.primary',
                      }}
                    >
                      <Typography variant="caption" sx={{ display: 'block', opacity: 0.85 }}>
                        {isUserMessage ? 'You' : message.metadata?.pluginName ?? 'Assistant'}
                      </Typography>
                      <Typography
                        variant="body2"
                        sx={{ whiteSpace: 'pre-wrap', mt: 0.25 }}
                      >
                        {message.content}
                      </Typography>

                      {message.status === 'running' && (
                        <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.75, mt: 0.75 }}>
                          <CircularProgress size={14} aria-label="Plugin running" />
                          <Typography variant="caption">Running</Typography>
                        </Box>
                      )}

                      <Typography variant="caption" sx={{ display: 'block', mt: 0.75, opacity: 0.85 }}>
                        {formatLocalTime(message.createdAt)}
                      </Typography>
                    </Box>
                  );
                })
              ) : (
                <Typography variant="body2" color="text.secondary">
                  Select an existing session or send a message to create a new one.
                </Typography>
              )}
            </Box>

            <Box component="form" onSubmit={handleSendMessage} sx={{ display: 'grid', gap: 1 }}>
              <TextField
                multiline
                minRows={3}
                maxRows={7}
                value={messageDraft}
                onChange={(event) => setMessageDraft(event.target.value)}
                label="Message"
                placeholder="Ask about Salesforce case trends, RCA details, or role-authorized domain context..."
                sx={chatInputSx}
                inputProps={{ 'aria-label': 'Chat message input' }}
              />
              <Box
                sx={{
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'flex-start',
                  gap: 1,
                  flexWrap: 'wrap',
                }}
              >
                <Box sx={{ minWidth: 0, flex: '1 1 280px' }}>
                  <Typography
                    variant="caption"
                    color="text.secondary"
                    sx={{ display: 'block', overflowWrap: 'anywhere' }}
                  >
                    Active scopes: {effectiveScopeSelection.length > 0
                      ? effectiveScopeSelection.map((scope) => getChatScopeLabel(scope)).join(', ')
                      : 'none'}
                  </Typography>
                  <Typography
                    variant="caption"
                    color="text.secondary"
                    sx={{ display: 'block', overflowWrap: 'anywhere' }}
                  >
                    Active model: {getChatModelLabel(effectiveModelSelection)}
                  </Typography>
                </Box>
                <Box sx={{ flexShrink: 0, ml: 'auto' }}>
                  <Button
                    type="submit"
                    loading={isSending}
                    disabled={
                      isHydrating
                      || messageDraft.trim().length === 0
                      || roleVisibleScopes.length === 0
                    }
                    aria-label="Send chat message"
                  >
                    Send
                  </Button>
                </Box>
              </Box>
            </Box>
          </Card>
        </Box>
      </Box>
    </Drawer>
  );
};

export default AgenticChatPage;

