// Generated by GitHub Copilot
/**
 * chatBackendMock - Backend-style chat orchestration and worker simulation for local development.
 * Mimics API + worker behavior using localStorage and deterministic dummy Salesforce/RCA datasets.
 */
import {
    type ChatMessage,
    type ChatScope,
    type ChatThread,
    type ResolvedChatPlugin,
    buildAssistantReply,
    buildThreadTitle,
    createMessageId,
    getChatScopeLabel,
    resolvePluginForMessage,
} from './chatRuntime';

const CHAT_THREADS_STORAGE_KEY = 'partner-portal-agentic-chat-backend-threads-v1';
const CHAT_TASKS_STORAGE_KEY = 'partner-portal-agentic-chat-backend-tasks-v1';
const WORKER_EXECUTION_LATENCY_MS = 1200;

export type ChatWorkerTaskStatus = 'queued' | 'running' | 'completed' | 'failed';

export interface ChatWorkerTask {
    id: string;
    threadId: string;
    ownerId: string;
    pluginId: string;
    pluginName: string;
    status: ChatWorkerTaskStatus;
    prompt: string;
    selectedScopes: ChatScope[];
    createdAt: string;
    startedAt?: string;
    completedAt?: string;
    errorMessage?: string;
}

export interface AppendMessageRequest {
    threadId?: string;
    prompt: string;
    selectedScopes: ChatScope[];
    senderId: string;
}

export interface AppendMessageResponse {
    thread: ChatThread;
    task: ChatWorkerTask;
}

export interface WorkerCompletionResult {
    thread: ChatThread;
    task: ChatWorkerTask;
}

interface PendingTaskResolver {
    resolve: (result: WorkerCompletionResult) => void;
    reject: (error: Error) => void;
}

interface SalesforceCaseSnapshot {
    caseNumber: string;
    accountName: string;
    severity: 'critical' | 'high' | 'medium' | 'low';
    status: 'new' | 'in-progress' | 'escalated' | 'closed';
    owner: string;
    updatedAt: string;
}

interface RcaInsightSnapshot {
    incidentId: string;
    title: string;
    rootCause: string;
    blastRadius: string;
    recommendedAction: string;
    updatedAt: string;
}

const pendingTaskResolvers = new Map<string, PendingTaskResolver>();

const SALESFORCE_CASES: readonly SalesforceCaseSnapshot[] = [
    {
        caseNumber: 'SF-001294',
        accountName: 'Atlas Payments Ltd',
        severity: 'critical',
        status: 'escalated',
        owner: 'Ops Escalation Queue',
        updatedAt: '2026-04-15T08:42:00Z',
    },
    {
        caseNumber: 'SF-001287',
        accountName: 'Northwind Supplies',
        severity: 'high',
        status: 'in-progress',
        owner: 'RCA Pod 2',
        updatedAt: '2026-04-15T08:03:00Z',
    },
    {
        caseNumber: 'SF-001251',
        accountName: 'Contoso Logistics',
        severity: 'medium',
        status: 'new',
        owner: 'Partner Compliance Queue',
        updatedAt: '2026-04-14T17:30:00Z',
    },
    {
        caseNumber: 'SF-001199',
        accountName: 'Fabrikam Distribution',
        severity: 'low',
        status: 'closed',
        owner: 'Vendor Success',
        updatedAt: '2026-04-14T12:15:00Z',
    },
];

const RCA_INSIGHTS: readonly RcaInsightSnapshot[] = [
    {
        incidentId: 'RCA-7812',
        title: 'Partner token refresh loop',
        rootCause: 'Stale OIDC client secret rotation in shared auth bridge.',
        blastRadius: '3 partner onboarding regions and 2 compliance workflows.',
        recommendedAction: 'Rotate secret, invalidate old refresh tokens, and replay failed jobs.',
        updatedAt: '2026-04-15T08:17:00Z',
    },
    {
        incidentId: 'RCA-7798',
        title: 'Vendor questionnaire webhook timeout',
        rootCause: 'Downstream Salesforce callback retry window too short for peak load.',
        blastRadius: 'Vendor risk review queue delayed for 42 records.',
        recommendedAction: 'Increase callback timeout and enable idempotent replay policy.',
        updatedAt: '2026-04-15T07:10:00Z',
    },
    {
        incidentId: 'RCA-7721',
        title: 'Control evidence attachment drift',
        rootCause: 'Inconsistent document mapping between policy and compliance modules.',
        blastRadius: '11 controls missing latest evidence references.',
        recommendedAction: 'Run evidence reconciliation and lock mapping schema version.',
        updatedAt: '2026-04-14T19:40:00Z',
    },
];

/**
 * Returns an ISO timestamp in UTC.
 */
function nowIso(): string {
    return new Date().toISOString();
}

/**
 * Normalizes owner ids so legacy and empty values are handled consistently.
 */
function normalizeOwnerId(ownerId: string | undefined): string {
    const normalized = String(ownerId ?? '').trim();
    return normalized.length > 0 ? normalized : 'anonymous';
}

/**
 * Attempts JSON parsing and falls back safely when malformed.
 */
function safeParseJson<T>(raw: string | null, fallback: T): T {
    if (!raw) {
        return fallback;
    }

    try {
        return JSON.parse(raw) as T;
    } catch {
        return fallback;
    }
}

/**
 * Reads persisted chat threads from storage.
 */
function readThreads(): ChatThread[] {
    const parsed = safeParseJson<unknown[]>(localStorage.getItem(CHAT_THREADS_STORAGE_KEY), []);
    if (!Array.isArray(parsed)) {
        return [];
    }

    return parsed.filter((candidate): candidate is ChatThread => {
        if (!candidate || typeof candidate !== 'object') {
            return false;
        }

        const maybeThread = candidate as Partial<ChatThread>;
        return (
            typeof maybeThread.id === 'string'
            && (typeof maybeThread.ownerId === 'undefined' || typeof maybeThread.ownerId === 'string')
            && typeof maybeThread.title === 'string'
            && Array.isArray(maybeThread.contexts)
            && Array.isArray(maybeThread.messages)
            && typeof maybeThread.createdAt === 'string'
            && typeof maybeThread.updatedAt === 'string'
            && typeof maybeThread.unread === 'boolean'
        );
    });
}

/**
 * Persists chat threads atomically.
 */
function writeThreads(threads: ChatThread[]): void {
    localStorage.setItem(CHAT_THREADS_STORAGE_KEY, JSON.stringify(threads));
}

/**
 * Reads persisted worker tasks.
 */
function readTasks(): ChatWorkerTask[] {
    const parsed = safeParseJson<unknown[]>(localStorage.getItem(CHAT_TASKS_STORAGE_KEY), []);
    if (!Array.isArray(parsed)) {
        return [];
    }

    return parsed.filter((candidate): candidate is ChatWorkerTask => {
        if (!candidate || typeof candidate !== 'object') {
            return false;
        }

        const maybeTask = candidate as Partial<ChatWorkerTask>;
        return (
            typeof maybeTask.id === 'string'
            && typeof maybeTask.threadId === 'string'
            && (typeof maybeTask.ownerId === 'undefined' || typeof maybeTask.ownerId === 'string')
            && typeof maybeTask.pluginId === 'string'
            && typeof maybeTask.pluginName === 'string'
            && typeof maybeTask.status === 'string'
            && typeof maybeTask.prompt === 'string'
            && Array.isArray(maybeTask.selectedScopes)
            && typeof maybeTask.createdAt === 'string'
        );
    });
}

/**
 * Persists worker tasks atomically.
 */
function writeTasks(tasks: ChatWorkerTask[]): void {
    localStorage.setItem(CHAT_TASKS_STORAGE_KEY, JSON.stringify(tasks));
}

/**
 * Upserts one thread record by id.
 */
function upsertThread(thread: ChatThread): void {
    const existing = readThreads();
    const next = existing.some((knownThread) => knownThread.id === thread.id)
        ? existing.map((knownThread) => (knownThread.id === thread.id ? thread : knownThread))
        : [thread, ...existing];

    writeThreads(next);
}

/**
 * Upserts one task record by id.
 */
function upsertTask(task: ChatWorkerTask): void {
    const existing = readTasks();
    const next = existing.some((knownTask) => knownTask.id === task.id)
        ? existing.map((knownTask) => (knownTask.id === task.id ? task : knownTask))
        : [task, ...existing];

    writeTasks(next);
}

/**
 * Creates a lightweight assistant welcome message for a new thread.
 */
function createWelcomeMessage(selectedScopes: readonly ChatScope[]): ChatMessage {
    const scopeSummary = selectedScopes.length > 0
        ? selectedScopes.map((scope) => getChatScopeLabel(scope)).join(', ')
        : 'No scopes selected';

    return {
        id: createMessageId('assistant'),
        role: 'assistant',
        status: 'completed',
        createdAt: nowIso(),
        content: `Orchestrator session started. Active scopes: ${scopeSummary}.`,
    };
}

/**
 * Creates thread if missing; otherwise returns existing thread.
 */
function getOrCreateThread(
    threadId: string | undefined,
    prompt: string,
    selectedScopes: readonly ChatScope[],
    ownerId: string
): ChatThread {
    const knownThreads = readThreads();

    if (threadId) {
        const existing = knownThreads.find((thread) => thread.id === threadId);
        if (existing) {
            if (existing.ownerId && existing.ownerId !== ownerId) {
                // Another user owns this thread id; create a new thread below.
            } else {
                if (!existing.ownerId) {
                    const claimedThread: ChatThread = {
                        ...existing,
                        ownerId,
                    };
                    upsertThread(claimedThread);
                    return claimedThread;
                }

                return existing;
            }
        }
    }

    const createdAt = nowIso();
    const createdThread: ChatThread = {
        id: createMessageId('thread'),
        ownerId,
        title: buildThreadTitle(prompt, selectedScopes),
        contexts: [...selectedScopes],
        createdAt,
        updatedAt: createdAt,
        unread: false,
        messages: [createWelcomeMessage(selectedScopes)],
    };

    upsertThread(createdThread);
    return createdThread;
}

/**
 * Formats Salesforce dummy data section for assistant responses.
 */
function buildSalesforceSection(): string {
    const preview = SALESFORCE_CASES.slice(0, 3).map((record, index) => (
        `${index + 1}. ${record.caseNumber} | ${record.accountName} | ${record.severity.toUpperCase()} | ${record.status} | owner: ${record.owner} | updated: ${record.updatedAt}`
    ));

    return [
        'Live Salesforce snapshots (dummy dataset):',
        ...preview,
    ].join('\n');
}

/**
 * Formats RCA dummy data section for assistant responses.
 */
function buildRcaSection(): string {
    const preview = RCA_INSIGHTS.slice(0, 2).map((record, index) => (
        `${index + 1}. ${record.incidentId} | ${record.title} | root cause: ${record.rootCause} | blast radius: ${record.blastRadius} | action: ${record.recommendedAction}`
    ));

    return [
        'Live RCA insights (dummy dataset):',
        ...preview,
    ].join('\n');
}

/**
 * Produces worker output from plugin intent and connector data.
 */
function buildWorkerResponse(
    plugin: ResolvedChatPlugin,
    prompt: string,
    selectedScopes: readonly ChatScope[]
): string {
    const base = buildAssistantReply(plugin, prompt, selectedScopes);

    if (plugin.id.startsWith('salesforce.')) {
        return `${base}\n\n${buildSalesforceSection()}`;
    }

    if (plugin.id.startsWith('rca.')) {
        return `${base}\n\n${buildRcaSection()}`;
    }

    return `${base}\n\n${buildSalesforceSection()}\n\n${buildRcaSection()}`;
}

/**
 * Completes or fails a worker task and updates thread placeholder message.
 */
function completeWorkerTask(
    task: ChatWorkerTask,
    placeholderMessageId: string
): void {
    const shouldFail = /simulate\s+failure|force\s+failure|worker\s+fail/i.test(task.prompt);
    const plugin = resolvePluginForMessage(task.prompt, task.selectedScopes);

    const knownThreads = readThreads();
    const targetThread = knownThreads.find((thread) => (
        thread.id === task.threadId
        && normalizeOwnerId(thread.ownerId) === normalizeOwnerId(task.ownerId)
    ));

    if (!targetThread) {
        const resolver = pendingTaskResolvers.get(task.id);
        if (resolver) {
            resolver.reject(new Error('Thread not found during worker completion.'));
            pendingTaskResolvers.delete(task.id);
        }
        return;
    }

    const updatedTask: ChatWorkerTask = {
        ...task,
        status: shouldFail ? 'failed' : 'completed',
        completedAt: nowIso(),
        errorMessage: shouldFail ? 'Simulated worker failure for testing resiliency.' : undefined,
    };

    upsertTask(updatedTask);

    const updatedThread: ChatThread = {
        ...targetThread,
        ownerId: normalizeOwnerId(targetThread.ownerId),
        updatedAt: nowIso(),
        messages: targetThread.messages.map((message) => {
            if (message.id !== placeholderMessageId) {
                return message;
            }

            if (shouldFail) {
                return {
                    ...message,
                    status: 'failed',
                    content: 'Worker execution failed. Please retry or adjust the prompt.',
                    metadata: {
                        ...(message.metadata ?? {}),
                    },
                };
            }

            return {
                ...message,
                status: 'completed',
                content: buildWorkerResponse(plugin, task.prompt, task.selectedScopes),
                metadata: {
                    ...(message.metadata ?? {}),
                    pluginId: plugin.id,
                    pluginName: plugin.name,
                },
            };
        }),
    };

    upsertThread(updatedThread);

    const resolver = pendingTaskResolvers.get(task.id);
    if (!resolver) {
        return;
    }

    if (shouldFail) {
        resolver.reject(new Error(updatedTask.errorMessage ?? 'Worker failed.'));
    } else {
        resolver.resolve({ thread: updatedThread, task: updatedTask });
    }

    pendingTaskResolvers.delete(task.id);
}

/**
 * Queues a worker task and asynchronously completes it.
 */
function enqueueWorkerTask(task: ChatWorkerTask, placeholderMessageId: string): void {
    const runningTask: ChatWorkerTask = {
        ...task,
        status: 'running',
        startedAt: nowIso(),
    };

    upsertTask(runningTask);

    window.setTimeout(() => {
        completeWorkerTask(runningTask, placeholderMessageId);
    }, WORKER_EXECUTION_LATENCY_MS);
}

/**
 * Lists all persisted threads sorted by recent activity.
 */
export async function listThreads(ownerId?: string): Promise<ChatThread[]> {
    const threads = readThreads();
    const normalizedOwnerId = ownerId ? normalizeOwnerId(ownerId) : undefined;

    // Include threads owned by the user OR legacy threads that have no ownerId
    // (created before per-user partitioning was introduced).
    const filteredThreads = normalizedOwnerId
        ? threads.filter((thread) => {
            if (!thread.ownerId) {
                return true; // Legacy unowned thread — visible to all authenticated users.
            }
            return normalizeOwnerId(thread.ownerId) === normalizedOwnerId;
        })
        : threads;

    return filteredThreads.sort((left, right) => right.updatedAt.localeCompare(left.updatedAt));
}

/**
 * Appends user and placeholder assistant messages, then enqueues worker execution.
 */
export async function appendMessage(request: AppendMessageRequest): Promise<AppendMessageResponse> {
    const prompt = request.prompt.trim();
    if (!prompt) {
        throw new Error('Prompt is required.');
    }

    if (request.selectedScopes.length === 0) {
        throw new Error('At least one context scope must be selected.');
    }

    const plugin = resolvePluginForMessage(prompt, request.selectedScopes);
    const ownerId = normalizeOwnerId(request.senderId);
    const thread = getOrCreateThread(request.threadId, prompt, request.selectedScopes, ownerId);

    const userMessage: ChatMessage = {
        id: createMessageId('user'),
        role: 'user',
        content: prompt,
        createdAt: nowIso(),
    };

    const assistantPlaceholder: ChatMessage = {
        id: createMessageId('assistant'),
        role: 'assistant',
        content: 'Worker task accepted. Orchestrating plugin execution...',
        createdAt: nowIso(),
        status: 'running',
        metadata: {
            pluginId: plugin.id,
            pluginName: plugin.name,
            selectedScopes: [...request.selectedScopes],
        },
    };

    const updatedThread: ChatThread = {
        ...thread,
        ownerId,
        title: thread.messages.length <= 1 ? buildThreadTitle(prompt, request.selectedScopes) : thread.title,
        contexts: [...request.selectedScopes],
        unread: false,
        updatedAt: nowIso(),
        messages: [...thread.messages, userMessage, assistantPlaceholder],
    };

    upsertThread(updatedThread);

    const task: ChatWorkerTask = {
        id: createMessageId('task'),
        threadId: updatedThread.id,
        ownerId,
        pluginId: plugin.id,
        pluginName: plugin.name,
        status: 'queued',
        prompt,
        selectedScopes: [...request.selectedScopes],
        createdAt: nowIso(),
    };

    upsertTask(task);
    enqueueWorkerTask(task, assistantPlaceholder.id);

    return {
        thread: updatedThread,
        task,
    };
}

/**
 * Waits for a worker task completion or failure and returns updated thread state.
 */
export async function waitForTaskResult(taskId: string, ownerId?: string): Promise<WorkerCompletionResult> {
    const normalizedOwnerId = ownerId ? normalizeOwnerId(ownerId) : undefined;
    const knownTask = readTasks().find((task) => (
        task.id === taskId
        && (!normalizedOwnerId || !task.ownerId || normalizeOwnerId(task.ownerId) === normalizedOwnerId)
    ));

    if (!knownTask) {
        throw new Error('Task not found.');
    }

    if (knownTask.status === 'completed') {
        const thread = readThreads().find((knownThread) => (
            knownThread.id === knownTask.threadId
            && (!normalizedOwnerId || !knownThread.ownerId || normalizeOwnerId(knownThread.ownerId) === normalizedOwnerId)
        ));
        if (!thread) {
            throw new Error('Thread not found for completed task.');
        }

        return { task: knownTask, thread };
    }

    if (knownTask.status === 'failed') {
        throw new Error(knownTask.errorMessage ?? 'Task failed.');
    }

    return new Promise<WorkerCompletionResult>((resolve, reject) => {
        pendingTaskResolvers.set(taskId, { resolve, reject });
    });
}

/**
 * Returns persisted worker tasks for diagnostics and local debugging.
 */
export async function listWorkerTasks(ownerId?: string): Promise<ChatWorkerTask[]> {
    const tasks = readTasks();
    const normalizedOwnerId = ownerId ? normalizeOwnerId(ownerId) : undefined;
    const filteredTasks = normalizedOwnerId
        ? tasks.filter((task) => normalizeOwnerId(task.ownerId) === normalizedOwnerId)
        : tasks;

    return filteredTasks.sort((left, right) => right.createdAt.localeCompare(left.createdAt));
}

/**
 * Clears persisted backend mock state for tests or manual reset workflows.
 */
export function resetChatBackendMockState(): void {
    localStorage.removeItem(CHAT_THREADS_STORAGE_KEY);
    localStorage.removeItem(CHAT_TASKS_STORAGE_KEY);
    pendingTaskResolvers.clear();
}
