// Generated by GitHub Copilot
/**
 * chatBackendMock - Backend-style chat orchestration and worker simulation for local development.
 * Mimics API + worker behavior using localStorage and deterministic dummy Salesforce/RCA datasets.
 */
import {
    type ChatMessage,
    type ChatModelId,
    type ChatScope,
    type ChatThread,
    type PromptSignals,
    type ResolvedChatPlugin,
    buildAssistantReply,
    buildThreadTitle,
    createMessageId,
    extractPromptSignals,
    getChatScopeLabel,
    resolveChatModel,
    resolvePluginForMessage,
} from './chatRuntime';
import { mockData } from '@shared/api-client';

const CHAT_THREADS_STORAGE_KEY = 'partner-portal-agentic-chat-backend-threads-v1';
const CHAT_TASKS_STORAGE_KEY = 'partner-portal-agentic-chat-backend-tasks-v1';
const WORKER_EXECUTION_LATENCY_MS = 1200;

export type ChatWorkerTaskStatus = 'queued' | 'running' | 'completed' | 'failed';

export interface ChatWorkerTask {
    id: string;
    threadId: string;
    ownerId: string;
    pluginId: string;
    pluginName: string;
    selectedModelId: ChatModelId;
    selectedModelName: string;
    status: ChatWorkerTaskStatus;
    prompt: string;
    selectedScopes: ChatScope[];
    createdAt: string;
    startedAt?: string;
    completedAt?: string;
    errorMessage?: string;
}

export interface AppendMessageRequest {
    threadId?: string;
    prompt: string;
    selectedScopes: ChatScope[];
    selectedModelId?: ChatModelId;
    senderId: string;
}

export interface AppendMessageResponse {
    thread: ChatThread;
    task: ChatWorkerTask;
}

export interface WorkerCompletionResult {
    thread: ChatThread;
    task: ChatWorkerTask;
}

interface PendingTaskResolver {
    resolve: (result: WorkerCompletionResult) => void;
    reject: (error: Error) => void;
}

interface SalesforceCaseSnapshot {
    caseNumber: string;
    accountName: string;
    severity: 'critical' | 'high' | 'medium' | 'low';
    status: 'new' | 'in-progress' | 'escalated' | 'closed';
    owner: string;
    updatedAt: string;
    linkedRiskIds: string[];
    linkedRcaIds: string[];
    linkedTraIds: string[];
    linkedImsIds: string[];
}

interface RcaInsightSnapshot {
    incidentId: string;
    title: string;
    domain: string;
    rootCause: string;
    blastRadius: string;
    recommendedAction: string;
    linkedRiskId?: string;
    linkedTraId?: string;
    linkedImsId?: string;
    updatedAt: string;
}

interface TraInsightSnapshot {
    assessmentId: string;
    title: string;
    domain: string;
    riskScore: number;
    riskLevel: 'critical' | 'high' | 'medium' | 'low';
    summary: string;
    mitigation: string;
    linkedRiskId?: string;
    linkedRcaId?: string;
    linkedImsId?: string;
    updatedAt: string;
}

interface ImsRecordSnapshot {
    ticketId: string;
    title: string;
    domain: string;
    severity: 'critical' | 'high' | 'medium' | 'low';
    status: 'open' | 'in-progress' | 'mitigated' | 'resolved';
    owner: string;
    linkedRiskId?: string;
    linkedRcaId?: string;
    linkedTraId?: string;
    updatedAt: string;
}

interface RiskAlertSnapshot {
    riskId: string;
    title: string;
    domain: string;
    score: number;
    severity: 'critical' | 'high' | 'medium' | 'low';
    owner: string;
    status: 'open' | 'in-progress' | 'mitigated' | 'closed';
    dueDate: string;
    linkedRcaId?: string;
    linkedTraId?: string;
    linkedImsId?: string;
}

interface AuditExecutionSnapshot {
    auditId: string;
    title: string;
    scope: string;
    leadAuditor: string;
    linkedRcaIds: string[];
    linkedRiskIds: string[];
}

const pendingTaskResolvers = new Map<string, PendingTaskResolver>();

const SALESFORCE_CASES: readonly SalesforceCaseSnapshot[] = [
    {
        caseNumber: 'SF-001294',
        accountName: 'Atlas Payments Ltd',
        severity: 'critical',
        status: 'escalated',
        owner: 'Ops Escalation Queue',
        updatedAt: '2026-04-15T08:42:00Z',
        linkedRiskIds: ['RSK-004'],
        linkedRcaIds: ['RCA-7812'],
        linkedTraIds: ['TRA-203'],
        linkedImsIds: ['IMS-105'],
    },
    {
        caseNumber: 'SF-001287',
        accountName: 'Northwind Supplies',
        severity: 'high',
        status: 'in-progress',
        owner: 'RCA Pod 2',
        updatedAt: '2026-04-15T08:03:00Z',
        linkedRiskIds: ['RSK-031'],
        linkedRcaIds: ['RCA-7798'],
        linkedTraIds: ['TRA-188'],
        linkedImsIds: ['IMS-092'],
    },
    {
        caseNumber: 'SF-001251',
        accountName: 'Contoso Logistics',
        severity: 'medium',
        status: 'new',
        owner: 'Partner Compliance Queue',
        updatedAt: '2026-04-14T17:30:00Z',
        linkedRiskIds: ['RSK-017'],
        linkedRcaIds: ['RCA-7721'],
        linkedTraIds: ['TRA-176'],
        linkedImsIds: ['IMS-083'],
    },
    {
        caseNumber: 'SF-001199',
        accountName: 'Fabrikam Distribution',
        severity: 'low',
        status: 'closed',
        owner: 'Vendor Success',
        updatedAt: '2026-04-14T12:15:00Z',
        linkedRiskIds: ['RSK-031'],
        linkedRcaIds: ['RCA-7798'],
        linkedTraIds: ['TRA-188'],
        linkedImsIds: ['IMS-092'],
    },
];

const RCA_INSIGHTS: readonly RcaInsightSnapshot[] = [
    {
        incidentId: 'RCA-7812',
        title: 'Partner token refresh loop',
        domain: 'Identity Management',
        rootCause: 'Stale OIDC client secret rotation in shared auth bridge.',
        blastRadius: '3 partner onboarding regions and 2 compliance workflows.',
        recommendedAction: 'Rotate secret, invalidate old refresh tokens, and replay failed jobs.',
        linkedRiskId: 'RSK-004',
        linkedTraId: 'TRA-203',
        linkedImsId: 'IMS-105',
        updatedAt: '2026-04-15T08:17:00Z',
    },
    {
        incidentId: 'RCA-7798',
        title: 'Vendor questionnaire webhook timeout',
        domain: 'Vendor Integration',
        rootCause: 'Downstream Salesforce callback retry window too short for peak load.',
        blastRadius: 'Vendor risk review queue delayed for 42 records.',
        recommendedAction: 'Increase callback timeout and enable idempotent replay policy.',
        linkedRiskId: 'RSK-031',
        linkedTraId: 'TRA-188',
        linkedImsId: 'IMS-092',
        updatedAt: '2026-04-15T07:10:00Z',
    },
    {
        incidentId: 'RCA-7721',
        title: 'Control evidence attachment drift',
        domain: 'Compliance Controls',
        rootCause: 'Inconsistent document mapping between policy and compliance modules.',
        blastRadius: '11 controls missing latest evidence references.',
        recommendedAction: 'Run evidence reconciliation and lock mapping schema version.',
        linkedRiskId: 'RSK-017',
        linkedTraId: 'TRA-176',
        linkedImsId: 'IMS-083',
        updatedAt: '2026-04-14T19:40:00Z',
    },
];

const TRA_INSIGHTS: readonly TraInsightSnapshot[] = [
    {
        assessmentId: 'TRA-203',
        title: 'Identity management password policy exposure',
        domain: 'Identity Management',
        riskScore: 62,
        riskLevel: 'medium',
        summary: 'Partner credential strength enforcement is inconsistent across onboarding gateways.',
        mitigation: 'Enforce unified password policy and block weak-credential exceptions.',
        linkedRiskId: 'RSK-004',
        linkedRcaId: 'RCA-7812',
        linkedImsId: 'IMS-105',
        updatedAt: '2026-04-15T08:50:00Z',
    },
    {
        assessmentId: 'TRA-188',
        title: 'Vendor webhook resiliency risk',
        domain: 'Vendor Integration',
        riskScore: 74,
        riskLevel: 'high',
        summary: 'Retry-window constraints cause delayed case ingestion during peak partner volume.',
        mitigation: 'Introduce adaptive retry policy and queue durability controls.',
        linkedRiskId: 'RSK-031',
        linkedRcaId: 'RCA-7798',
        linkedImsId: 'IMS-092',
        updatedAt: '2026-04-15T07:35:00Z',
    },
    {
        assessmentId: 'TRA-176',
        title: 'Control evidence mapping drift risk',
        domain: 'Compliance Controls',
        riskScore: 58,
        riskLevel: 'medium',
        summary: 'Evidence references can drift when policy schema and control mapping versions diverge.',
        mitigation: 'Add schema pinning and nightly evidence reconciliation jobs.',
        linkedRiskId: 'RSK-017',
        linkedRcaId: 'RCA-7721',
        linkedImsId: 'IMS-083',
        updatedAt: '2026-04-14T20:05:00Z',
    },
];

const IMS_RECORDS: readonly ImsRecordSnapshot[] = [
    {
        ticketId: 'IMS-105',
        title: 'Weak partner password policy path still enabled',
        domain: 'Identity Management',
        severity: 'medium',
        status: 'open',
        owner: 'IAM Team',
        linkedRiskId: 'RSK-004',
        linkedRcaId: 'RCA-7812',
        linkedTraId: 'TRA-203',
        updatedAt: '2026-04-16T06:25:00Z',
    },
    {
        ticketId: 'IMS-092',
        title: 'Vendor webhook timeout backlog',
        domain: 'Vendor Integration',
        severity: 'high',
        status: 'in-progress',
        owner: 'RCA Pod 2',
        linkedRiskId: 'RSK-031',
        linkedRcaId: 'RCA-7798',
        linkedTraId: 'TRA-188',
        updatedAt: '2026-04-15T07:42:00Z',
    },
    {
        ticketId: 'IMS-083',
        title: 'Control evidence references outdated',
        domain: 'Compliance Controls',
        severity: 'medium',
        status: 'mitigated',
        owner: 'Compliance Operations',
        linkedRiskId: 'RSK-017',
        linkedRcaId: 'RCA-7721',
        linkedTraId: 'TRA-176',
        updatedAt: '2026-04-15T11:20:00Z',
    },
];

const RISK_ALERTS: readonly RiskAlertSnapshot[] = [
    {
        riskId: 'RSK-004',
        title: 'Weak password policy for partners',
        domain: 'Identity Management',
        score: 6,
        severity: 'low',
        owner: 'IAM Team',
        status: 'open',
        dueDate: '2026-04-20',
        linkedRcaId: 'RCA-7812',
        linkedTraId: 'TRA-203',
        linkedImsId: 'IMS-105',
    },
    {
        riskId: 'RSK-031',
        title: 'Vendor case callback retry saturation',
        domain: 'Vendor Integration',
        score: 8,
        severity: 'high',
        owner: 'Vendor Risk Team',
        status: 'in-progress',
        dueDate: '2026-04-24',
        linkedRcaId: 'RCA-7798',
        linkedTraId: 'TRA-188',
        linkedImsId: 'IMS-092',
    },
    {
        riskId: 'RSK-017',
        title: 'Control evidence schema drift risk',
        domain: 'Compliance Controls',
        score: 7,
        severity: 'medium',
        owner: 'Compliance Team',
        status: 'open',
        dueDate: '2026-04-22',
        linkedRcaId: 'RCA-7721',
        linkedTraId: 'TRA-176',
        linkedImsId: 'IMS-083',
    },
];

/**
 * Maps audit plan semantics to linked RCA and risk artifacts.
 */
function inferAuditLinks(auditTitle: string, auditScope: string): { linkedRcaIds: string[]; linkedRiskIds: string[] } {
    const normalized = `${auditTitle} ${auditScope}`.toLowerCase();

    if (/partner|vendor|callback|questionnaire/.test(normalized)) {
        return {
            linkedRcaIds: ['RCA-7798'],
            linkedRiskIds: ['RSK-031'],
        };
    }

    if (/soc|control|compliance|evidence|trust service/.test(normalized)) {
        return {
            linkedRcaIds: ['RCA-7721'],
            linkedRiskIds: ['RSK-017'],
        };
    }

    return {
        linkedRcaIds: ['RCA-7812', 'RCA-7721'],
        linkedRiskIds: ['RSK-004', 'RSK-017'],
    };
}

/**
 * Builds audit execution snapshots from the shared audit dataset used across remotes.
 */
function buildAuditExecutionSnapshots(): AuditExecutionSnapshot[] {
    return mockData.audits.map((audit) => {
        const links = inferAuditLinks(audit.title, audit.scope);

        return {
            auditId: audit.id,
            title: audit.title,
            scope: audit.scope,
            leadAuditor: audit.leadAuditor,
            linkedRcaIds: links.linkedRcaIds,
            linkedRiskIds: links.linkedRiskIds,
        };
    });
}

const AUDIT_EXECUTIONS: readonly AuditExecutionSnapshot[] = buildAuditExecutionSnapshots();

/**
 * Returns an ISO timestamp in UTC.
 */
function nowIso(): string {
    return new Date().toISOString();
}

/**
 * Normalizes owner ids so legacy and empty values are handled consistently.
 */
function normalizeOwnerId(ownerId: string | undefined): string {
    const normalized = String(ownerId ?? '').trim();
    return normalized.length > 0 ? normalized : 'anonymous';
}

/**
 * Attempts JSON parsing and falls back safely when malformed.
 */
function safeParseJson<T>(raw: string | null, fallback: T): T {
    if (!raw) {
        return fallback;
    }

    try {
        return JSON.parse(raw) as T;
    } catch {
        return fallback;
    }
}

/**
 * Reads persisted chat threads from storage.
 */
function readThreads(): ChatThread[] {
    const parsed = safeParseJson<unknown[]>(localStorage.getItem(CHAT_THREADS_STORAGE_KEY), []);
    if (!Array.isArray(parsed)) {
        return [];
    }

    return parsed.filter((candidate): candidate is ChatThread => {
        if (!candidate || typeof candidate !== 'object') {
            return false;
        }

        const maybeThread = candidate as Partial<ChatThread>;
        return (
            typeof maybeThread.id === 'string'
            && (typeof maybeThread.ownerId === 'undefined' || typeof maybeThread.ownerId === 'string')
            && typeof maybeThread.title === 'string'
            && Array.isArray(maybeThread.contexts)
            && Array.isArray(maybeThread.messages)
            && typeof maybeThread.createdAt === 'string'
            && typeof maybeThread.updatedAt === 'string'
            && typeof maybeThread.unread === 'boolean'
        );
    });
}

/**
 * Persists chat threads atomically.
 */
function writeThreads(threads: ChatThread[]): void {
    localStorage.setItem(CHAT_THREADS_STORAGE_KEY, JSON.stringify(threads));
}

/**
 * Reads persisted worker tasks.
 */
function readTasks(): ChatWorkerTask[] {
    const parsed = safeParseJson<unknown[]>(localStorage.getItem(CHAT_TASKS_STORAGE_KEY), []);
    if (!Array.isArray(parsed)) {
        return [];
    }

    return parsed.filter((candidate): candidate is ChatWorkerTask => {
        if (!candidate || typeof candidate !== 'object') {
            return false;
        }

        const maybeTask = candidate as Partial<ChatWorkerTask>;
        return (
            typeof maybeTask.id === 'string'
            && typeof maybeTask.threadId === 'string'
            && (typeof maybeTask.ownerId === 'undefined' || typeof maybeTask.ownerId === 'string')
            && typeof maybeTask.pluginId === 'string'
            && typeof maybeTask.pluginName === 'string'
            && typeof maybeTask.selectedModelId === 'string'
            && typeof maybeTask.selectedModelName === 'string'
            && typeof maybeTask.status === 'string'
            && typeof maybeTask.prompt === 'string'
            && Array.isArray(maybeTask.selectedScopes)
            && typeof maybeTask.createdAt === 'string'
        );
    });
}

/**
 * Persists worker tasks atomically.
 */
function writeTasks(tasks: ChatWorkerTask[]): void {
    localStorage.setItem(CHAT_TASKS_STORAGE_KEY, JSON.stringify(tasks));
}

/**
 * Upserts one thread record by id.
 */
function upsertThread(thread: ChatThread): void {
    const existing = readThreads();
    const next = existing.some((knownThread) => knownThread.id === thread.id)
        ? existing.map((knownThread) => (knownThread.id === thread.id ? thread : knownThread))
        : [thread, ...existing];

    writeThreads(next);
}

/**
 * Upserts one task record by id.
 */
function upsertTask(task: ChatWorkerTask): void {
    const existing = readTasks();
    const next = existing.some((knownTask) => knownTask.id === task.id)
        ? existing.map((knownTask) => (knownTask.id === task.id ? task : knownTask))
        : [task, ...existing];

    writeTasks(next);
}

/**
 * Creates a lightweight assistant welcome message for a new thread.
 */
function createWelcomeMessage(selectedScopes: readonly ChatScope[]): ChatMessage {
    const scopeSummary = selectedScopes.length > 0
        ? selectedScopes.map((scope) => getChatScopeLabel(scope)).join(', ')
        : 'No scopes selected';

    return {
        id: createMessageId('assistant'),
        role: 'assistant',
        status: 'completed',
        createdAt: nowIso(),
        content: `Orchestrator session started. Active scopes: ${scopeSummary}.`,
    };
}

/**
 * Creates thread if missing; otherwise returns existing thread.
 */
function getOrCreateThread(
    threadId: string | undefined,
    prompt: string,
    selectedScopes: readonly ChatScope[],
    ownerId: string,
    modelId: ChatModelId
): ChatThread {
    const knownThreads = readThreads();

    if (threadId) {
        const existing = knownThreads.find((thread) => thread.id === threadId);
        if (existing) {
            if (existing.ownerId && existing.ownerId !== ownerId) {
                // Another user owns this thread id; create a new thread below.
            } else {
                if (!existing.ownerId) {
                    const claimedThread: ChatThread = {
                        ...existing,
                        ownerId,
                        modelId: existing.modelId ?? modelId,
                    };
                    upsertThread(claimedThread);
                    return claimedThread;
                }

                return existing;
            }
        }
    }

    const createdAt = nowIso();
    const createdThread: ChatThread = {
        id: createMessageId('thread'),
        ownerId,
        title: buildThreadTitle(prompt, selectedScopes),
        contexts: [...selectedScopes],
        modelId,
        createdAt,
        updatedAt: createdAt,
        unread: false,
        messages: [createWelcomeMessage(selectedScopes)],
    };

    upsertThread(createdThread);
    return createdThread;
}

/**
 * Sanitizes and bounds prompts before any orchestration logic runs.
 */
function sanitizePrompt(rawPrompt: string): string {
    const withoutControlChars = rawPrompt.replace(/[\u0000-\u001f\u007f]/g, ' ');
    const collapsedWhitespace = withoutControlChars.replace(/\s+/g, ' ').trim();
    return collapsedWhitespace.slice(0, 2000);
}

const PROMPT_SEARCH_STOP_WORDS = new Set([
    'a',
    'an',
    'and',
    'any',
    'can',
    'for',
    'from',
    'give',
    'list',
    'me',
    'please',
    'provide',
    'show',
    'the',
    'their',
    'there',
    'these',
    'those',
    'with',
]);

const RCA_GENERIC_PROMPT_TOKENS = new Set([
    'rca',
    'root',
    'cause',
    'analysis',
    'incident',
    'timeline',
    'postmortem',
    'audit',
    'auit',
]);

/**
 * Splits prompt text into stable search tokens for fallback matching.
 */
function getPromptSearchTokens(normalizedPrompt: string): string[] {
    return normalizedPrompt
        .toLowerCase()
        .replace(/[^a-z0-9\s-]/g, ' ')
        .split(/\s+/)
        .filter((token) => token.length >= 3 && !PROMPT_SEARCH_STOP_WORDS.has(token));
}

/**
 * Matches a record against prompt search tokens.
 */
function matchesPromptTokens(fields: readonly string[], promptTokens: readonly string[]): boolean {
    if (promptTokens.length === 0) {
        return false;
    }

    const haystack = fields.join(' ').toLowerCase();
    return promptTokens.some((token) => haystack.includes(token));
}

/**
 * Aggregates linked artifact ids from matched Salesforce records.
 */
function collectSalesforceLinkedIds(records: readonly SalesforceCaseSnapshot[]): {
    riskIds: Set<string>;
    rcaIds: Set<string>;
    traIds: Set<string>;
    imsIds: Set<string>;
} {
    return {
        riskIds: new Set(records.flatMap((record) => record.linkedRiskIds)),
        rcaIds: new Set(records.flatMap((record) => record.linkedRcaIds)),
        traIds: new Set(records.flatMap((record) => record.linkedTraIds)),
        imsIds: new Set(records.flatMap((record) => record.linkedImsIds)),
    };
}

/**
 * Resolves best matching risk alerts from ids first, then keyword fallback.
 */
function resolveRiskAlerts(promptSignals: PromptSignals): RiskAlertSnapshot[] {
    const { extractedIds } = promptSignals;
    const promptTokens = getPromptSearchTokens(promptSignals.normalizedPrompt);

    const exactByRiskId = RISK_ALERTS.filter((risk) => extractedIds.riskIds.includes(risk.riskId));
    if (exactByRiskId.length > 0) {
        return exactByRiskId;
    }

    const linkedByArtifacts = RISK_ALERTS.filter((risk) => (
        (risk.linkedRcaId && extractedIds.rcaIds.includes(risk.linkedRcaId))
        || (risk.linkedTraId && extractedIds.traIds.includes(risk.linkedTraId))
        || (risk.linkedImsId && extractedIds.imsIds.includes(risk.linkedImsId))
    ));

    if (linkedByArtifacts.length > 0) {
        return linkedByArtifacts;
    }

    return RISK_ALERTS.filter((risk) => matchesPromptTokens(
        [risk.riskId, risk.title, risk.domain, risk.owner, risk.status],
        promptTokens,
    ));
}

/**
 * Resolves audit executions by explicit audit id, lead auditor name, or keyword fallback.
 */
function resolveAuditExecutions(promptSignals: PromptSignals): AuditExecutionSnapshot[] {
    const normalizedPrompt = promptSignals.normalizedPrompt.toLowerCase();
    const promptTokens = getPromptSearchTokens(promptSignals.normalizedPrompt);
    const explicitAuditIds = Array.from(new Set(
        (promptSignals.normalizedPrompt.match(/\bAUD-\d{3,}\b/gi) ?? []).map((match) => match.toUpperCase()),
    ));

    const exactByAuditId = AUDIT_EXECUTIONS.filter((audit) => explicitAuditIds.includes(audit.auditId));
    if (exactByAuditId.length > 0) {
        return exactByAuditId;
    }

    const exactByLeadAuditor = AUDIT_EXECUTIONS.filter((audit) => {
        const auditorName = audit.leadAuditor.toLowerCase();
        if (normalizedPrompt.includes(auditorName)) {
            return true;
        }

        const meaningfulNameTokens = auditorName
            .split(/[^a-z0-9]+/)
            .filter((token) => token.length >= 3 && token !== 'external');

        return meaningfulNameTokens.length > 0
            && meaningfulNameTokens.every((token) => normalizedPrompt.includes(token));
    });

    if (exactByLeadAuditor.length > 0) {
        return exactByLeadAuditor;
    }

    return AUDIT_EXECUTIONS.filter((audit) => matchesPromptTokens(
        [audit.auditId, audit.title, audit.scope, audit.leadAuditor],
        promptTokens,
    ));
}

/**
 * Resolves RCA artifacts from extracted ids, linked ids, and prompt keywords.
 */
function resolveRcaInsights(
    promptSignals: PromptSignals,
    matchedRisks: readonly RiskAlertSnapshot[],
    matchedAudits: readonly AuditExecutionSnapshot[],
    matchedSalesforce: readonly SalesforceCaseSnapshot[],
): RcaInsightSnapshot[] {
    const { extractedIds } = promptSignals;
    const promptTokens = getPromptSearchTokens(promptSignals.normalizedPrompt).filter(
        (token) => !RCA_GENERIC_PROMPT_TOKENS.has(token),
    );
    const riskIds = new Set(matchedRisks.map((risk) => risk.riskId));
    const auditLinkedRcaIds = new Set(matchedAudits.flatMap((audit) => audit.linkedRcaIds));
    const auditLinkedRiskIds = new Set(matchedAudits.flatMap((audit) => audit.linkedRiskIds));
    const salesforceLinkedIds = collectSalesforceLinkedIds(matchedSalesforce);

    const exactByRcaId = RCA_INSIGHTS.filter((rca) => extractedIds.rcaIds.includes(rca.incidentId));
    if (exactByRcaId.length > 0) {
        return exactByRcaId;
    }

    const linked = RCA_INSIGHTS.filter((rca) => (
        (rca.linkedRiskId && (riskIds.has(rca.linkedRiskId) || extractedIds.riskIds.includes(rca.linkedRiskId)))
        || (rca.linkedTraId && extractedIds.traIds.includes(rca.linkedTraId))
        || (rca.linkedImsId && extractedIds.imsIds.includes(rca.linkedImsId))
    ));

    if (linked.length > 0) {
        return linked;
    }

    const linkedBySalesforceContext = RCA_INSIGHTS.filter((rca) => (
        salesforceLinkedIds.rcaIds.has(rca.incidentId)
        || (rca.linkedRiskId ? salesforceLinkedIds.riskIds.has(rca.linkedRiskId) : false)
        || (rca.linkedTraId ? salesforceLinkedIds.traIds.has(rca.linkedTraId) : false)
        || (rca.linkedImsId ? salesforceLinkedIds.imsIds.has(rca.linkedImsId) : false)
    ));

    if (linkedBySalesforceContext.length > 0) {
        return linkedBySalesforceContext;
    }

    const linkedByAuditContext = RCA_INSIGHTS.filter((rca) => (
        auditLinkedRcaIds.has(rca.incidentId)
        || (rca.linkedRiskId ? auditLinkedRiskIds.has(rca.linkedRiskId) : false)
    ));

    if (linkedByAuditContext.length > 0) {
        return linkedByAuditContext;
    }

    if (promptTokens.length === 0) {
        return [];
    }

    return RCA_INSIGHTS.filter((rca) => matchesPromptTokens(
        [rca.incidentId, rca.title, rca.domain, rca.rootCause, rca.blastRadius],
        promptTokens,
    ));
}

/**
 * Resolves TRA artifacts from extracted ids, linked ids, and prompt keywords.
 */
function resolveTraInsights(
    promptSignals: PromptSignals,
    matchedRisks: readonly RiskAlertSnapshot[],
    matchedSalesforce: readonly SalesforceCaseSnapshot[],
): TraInsightSnapshot[] {
    const { extractedIds } = promptSignals;
    const promptTokens = getPromptSearchTokens(promptSignals.normalizedPrompt);
    const riskIds = new Set(matchedRisks.map((risk) => risk.riskId));
    const salesforceLinkedIds = collectSalesforceLinkedIds(matchedSalesforce);

    const exactByTraId = TRA_INSIGHTS.filter((tra) => extractedIds.traIds.includes(tra.assessmentId));
    if (exactByTraId.length > 0) {
        return exactByTraId;
    }

    const linked = TRA_INSIGHTS.filter((tra) => (
        (tra.linkedRiskId && (riskIds.has(tra.linkedRiskId) || extractedIds.riskIds.includes(tra.linkedRiskId)))
        || (tra.linkedRcaId && extractedIds.rcaIds.includes(tra.linkedRcaId))
        || (tra.linkedImsId && extractedIds.imsIds.includes(tra.linkedImsId))
    ));

    if (linked.length > 0) {
        return linked;
    }

    const linkedBySalesforceContext = TRA_INSIGHTS.filter((tra) => (
        salesforceLinkedIds.traIds.has(tra.assessmentId)
        || (tra.linkedRiskId ? salesforceLinkedIds.riskIds.has(tra.linkedRiskId) : false)
        || (tra.linkedRcaId ? salesforceLinkedIds.rcaIds.has(tra.linkedRcaId) : false)
        || (tra.linkedImsId ? salesforceLinkedIds.imsIds.has(tra.linkedImsId) : false)
    ));

    if (linkedBySalesforceContext.length > 0) {
        return linkedBySalesforceContext;
    }

    return TRA_INSIGHTS.filter((tra) => matchesPromptTokens(
        [tra.assessmentId, tra.title, tra.domain, tra.summary, tra.mitigation],
        promptTokens,
    ));
}

/**
 * Resolves IMS artifacts from extracted ids, linked ids, and prompt keywords.
 */
function resolveImsRecords(
    promptSignals: PromptSignals,
    matchedRisks: readonly RiskAlertSnapshot[],
    matchedSalesforce: readonly SalesforceCaseSnapshot[],
): ImsRecordSnapshot[] {
    const { extractedIds } = promptSignals;
    const promptTokens = getPromptSearchTokens(promptSignals.normalizedPrompt);
    const riskIds = new Set(matchedRisks.map((risk) => risk.riskId));
    const salesforceLinkedIds = collectSalesforceLinkedIds(matchedSalesforce);

    const exactByImsId = IMS_RECORDS.filter((ims) => extractedIds.imsIds.includes(ims.ticketId));
    if (exactByImsId.length > 0) {
        return exactByImsId;
    }

    const linked = IMS_RECORDS.filter((ims) => (
        (ims.linkedRiskId && (riskIds.has(ims.linkedRiskId) || extractedIds.riskIds.includes(ims.linkedRiskId)))
        || (ims.linkedRcaId && extractedIds.rcaIds.includes(ims.linkedRcaId))
        || (ims.linkedTraId && extractedIds.traIds.includes(ims.linkedTraId))
    ));

    if (linked.length > 0) {
        return linked;
    }

    const linkedBySalesforceContext = IMS_RECORDS.filter((ims) => (
        salesforceLinkedIds.imsIds.has(ims.ticketId)
        || (ims.linkedRiskId ? salesforceLinkedIds.riskIds.has(ims.linkedRiskId) : false)
        || (ims.linkedRcaId ? salesforceLinkedIds.rcaIds.has(ims.linkedRcaId) : false)
        || (ims.linkedTraId ? salesforceLinkedIds.traIds.has(ims.linkedTraId) : false)
    ));

    if (linkedBySalesforceContext.length > 0) {
        return linkedBySalesforceContext;
    }

    return IMS_RECORDS.filter((ims) => matchesPromptTokens(
        [ims.ticketId, ims.title, ims.domain, ims.owner, ims.status],
        promptTokens,
    ));
}

/**
 * Resolves Salesforce case snapshots from case ids and keyword fallback.
 */
function resolveSalesforceCases(promptSignals: PromptSignals): SalesforceCaseSnapshot[] {
    const { extractedIds } = promptSignals;
    const promptTokens = getPromptSearchTokens(promptSignals.normalizedPrompt);
    const hasSalesforceContextHint = /\b(salesforce|crm|case|record|logs?)\b/i.test(promptSignals.normalizedPrompt);

    const exactCases = SALESFORCE_CASES.filter((record) => extractedIds.salesforceCaseIds.includes(record.caseNumber));
    if (exactCases.length > 0) {
        return exactCases;
    }

    const keywordMatches = hasSalesforceContextHint
        ? SALESFORCE_CASES.filter((record) => matchesPromptTokens(
            [record.caseNumber, record.accountName, record.owner, record.status],
            promptTokens,
        ))
        : [];

    if (keywordMatches.length > 0) {
        return keywordMatches;
    }

    return hasSalesforceContextHint ? SALESFORCE_CASES.slice(0, 3) : [];
}

/**
 * Formats record context used to derive artifact applicability.
 */
function buildRelevantRecordsSection(records: readonly SalesforceCaseSnapshot[]): string {
    if (records.length === 0) {
        return 'Relevant logs/records: no matching Salesforce records found for this prompt.';
    }

    return [
        'Relevant logs/records:',
        buildSalesforceSection(records),
    ].join('\n');
}

/**
 * Formats matched risk alerts for assistant responses.
 */
function buildRiskAlertSection(matchedRisks: readonly RiskAlertSnapshot[]): string {
    if (matchedRisks.length === 0) {
        return 'Risk alerts: no matching risk alerts found.';
    }

    return [
        'Risk alerts:',
        ...matchedRisks.slice(0, 5).map((risk, index) => (
            `${index + 1}. ${risk.riskId} | ${risk.title} | ${risk.domain} | score: ${risk.score} | severity: ${risk.severity} | owner: ${risk.owner} | status: ${risk.status} | due: ${risk.dueDate}`
        )),
    ].join('\n');
}

/**
 * Formats matched audit context for assistant responses.
 */
function buildAuditContextSection(records: readonly AuditExecutionSnapshot[]): string {
    if (records.length === 0) {
        return 'Matched audit context: no matching audit runs found.';
    }

    const displayLimit = 10;
    const displayRecords = records.slice(0, displayLimit);

    return [
        'Matched audit context:',
        ...displayRecords.map((record, index) => (
            `${index + 1}. ${record.auditId} | ${record.title} | lead auditor: ${record.leadAuditor} | scope: ${record.scope}`
        )),
        ...(records.length > displayRecords.length
            ? [`...and ${records.length - displayRecords.length} more matched audits.`]
            : []),
    ].join('\n');
}

/**
 * Formats audit-to-RCA linkage so each retrieved audit item has explicit RCA references.
 */
function buildAuditRcaLinkageSection(records: readonly AuditExecutionSnapshot[]): string {
    if (records.length === 0) {
        return 'Audit RCA linkage: no matching audit runs found.';
    }

    const displayLimit = 10;
    const displayRecords = records.slice(0, displayLimit);

    return [
        'Audit RCA linkage:',
        ...displayRecords.map((record, index) => {
            const rcaList = record.linkedRcaIds.length > 0 ? record.linkedRcaIds.join(', ') : 'none';
            return `${index + 1}. ${record.auditId} | lead auditor: ${record.leadAuditor} | RCA: ${rcaList}`;
        }),
        ...(records.length > displayRecords.length
            ? [`...and ${records.length - displayRecords.length} more matched audits.`]
            : []),
    ].join('\n');
}

/**
 * Formats Salesforce dummy data section for assistant responses.
 */
function buildSalesforceSection(records: readonly SalesforceCaseSnapshot[]): string {
    return [
        'Live Salesforce snapshots (dummy dataset):',
        ...records.slice(0, 5).map((record, index) => (
            `${index + 1}. ${record.caseNumber} | ${record.accountName} | ${record.severity.toUpperCase()} | ${record.status} | owner: ${record.owner} | updated: ${record.updatedAt}`
        )),
    ].join('\n');
}

/**
 * Formats RCA artifacts for assistant responses.
 */
function buildRcaSection(records: readonly RcaInsightSnapshot[]): string {
    if (records.length === 0) {
        return 'RCA findings: no matching RCA records found.';
    }

    return [
        'RCA findings:',
        ...records.slice(0, 5).map((record, index) => (
            `${index + 1}. ${record.incidentId} | ${record.title} | domain: ${record.domain} | root cause: ${record.rootCause} | blast radius: ${record.blastRadius} | action: ${record.recommendedAction}`
        )),
    ].join('\n');
}

/**
 * Formats TRA artifacts for assistant responses.
 */
function buildTraSection(records: readonly TraInsightSnapshot[]): string {
    if (records.length === 0) {
        return 'TRA findings: no matching TRA records found.';
    }

    return [
        'TRA findings:',
        ...records.slice(0, 5).map((record, index) => (
            `${index + 1}. ${record.assessmentId} | ${record.title} | domain: ${record.domain} | risk score: ${record.riskScore} (${record.riskLevel}) | summary: ${record.summary} | mitigation: ${record.mitigation}`
        )),
    ].join('\n');
}

/**
 * Formats IMS artifacts for assistant responses.
 */
function buildImsSection(records: readonly ImsRecordSnapshot[]): string {
    if (records.length === 0) {
        return 'IMS findings: no matching IMS records found.';
    }

    return [
        'IMS findings:',
        ...records.slice(0, 5).map((record, index) => (
            `${index + 1}. ${record.ticketId} | ${record.title} | domain: ${record.domain} | severity: ${record.severity} | status: ${record.status} | owner: ${record.owner} | updated: ${record.updatedAt}`
        )),
    ].join('\n');
}

/**
 * Produces worker output from plugin intent and connector data.
 */
function buildWorkerResponse(
    plugin: ResolvedChatPlugin,
    prompt: string,
    selectedScopes: readonly ChatScope[],
    selectedModelId: ChatModelId
): string {
    const promptSignals = extractPromptSignals(prompt);
    const resolvedModel = resolveChatModel(selectedModelId, selectedScopes, prompt);

    const matchedRisks = resolveRiskAlerts(promptSignals);
    const matchedAudits = resolveAuditExecutions(promptSignals);
    const matchedSalesforce = resolveSalesforceCases(promptSignals);
    const matchedRca = resolveRcaInsights(promptSignals, matchedRisks, matchedAudits, matchedSalesforce);
    const matchedTra = resolveTraInsights(promptSignals, matchedRisks, matchedSalesforce);
    const matchedIms = resolveImsRecords(promptSignals, matchedRisks, matchedSalesforce);

    const shouldIncludeRca = (
        promptSignals.requestedArtifacts.includes('rca')
        || plugin.id.startsWith('rca.')
        || promptSignals.extractedIds.rcaIds.length > 0
    ) && matchedRca.length > 0;
    const shouldIncludeTra = (
        promptSignals.requestedArtifacts.includes('tra')
        || promptSignals.extractedIds.traIds.length > 0
        || promptSignals.extractedIds.riskIds.length > 0
    ) && matchedTra.length > 0;
    const shouldIncludeIms = (
        promptSignals.requestedArtifacts.includes('ims')
        || promptSignals.extractedIds.imsIds.length > 0
        || promptSignals.extractedIds.salesforceCaseIds.length > 0
        || /\brisk alert|alert\b/i.test(promptSignals.normalizedPrompt)
    ) && matchedIms.length > 0;
    const shouldIncludeRisk = promptSignals.extractedIds.riskIds.length > 0
        || /\brisk alert|risk|identity management\b/i.test(promptSignals.normalizedPrompt);
    const shouldIncludeAudit = matchedAudits.length > 0;
    const shouldIncludeRelevantRecords = matchedSalesforce.length > 0 || /\b(salesforce|crm|case|record|logs?)\b/i.test(promptSignals.normalizedPrompt);

    const sections: string[] = [
        buildAssistantReply(plugin, prompt, selectedScopes, {
            model: resolvedModel,
            promptSignals,
        }),
    ];

    if (shouldIncludeRisk) {
        sections.push(buildRiskAlertSection(matchedRisks));
    }

    if (shouldIncludeRelevantRecords) {
        sections.push(buildRelevantRecordsSection(matchedSalesforce));
    }

    if (shouldIncludeAudit) {
        sections.push(buildAuditContextSection(matchedAudits));

        if (shouldIncludeRca) {
            sections.push(buildAuditRcaLinkageSection(matchedAudits));
        }
    }

    if (shouldIncludeRca) {
        sections.push(buildRcaSection(matchedRca));
    }

    if (shouldIncludeTra) {
        sections.push(buildTraSection(matchedTra));
    }

    if (shouldIncludeIms) {
        sections.push(buildImsSection(matchedIms));
    }

    const hasApplicableArtifactSection = shouldIncludeRca || shouldIncludeTra || shouldIncludeIms;

    if (sections.length === 1) {
        sections.push('Relevant logs/records: no matching records found for this prompt.');
    }

    if (!hasApplicableArtifactSection && promptSignals.requestedArtifacts.length > 0) {
        sections.push(
            `Applicable artifacts not found for selected records: ${promptSignals.requestedArtifacts
                .map((artifact) => artifact.toUpperCase())
                .join(', ')}.`
        );
    }

    return sections.join('\n\n');
}

/**
 * Completes or fails a worker task and updates thread placeholder message.
 */
function completeWorkerTask(
    task: ChatWorkerTask,
    placeholderMessageId: string
): void {
    const shouldFail = /simulate\s+failure|force\s+failure|worker\s+fail/i.test(task.prompt);
    const plugin = resolvePluginForMessage(task.prompt, task.selectedScopes);

    const knownThreads = readThreads();
    const targetThread = knownThreads.find((thread) => (
        thread.id === task.threadId
        && normalizeOwnerId(thread.ownerId) === normalizeOwnerId(task.ownerId)
    ));

    if (!targetThread) {
        const resolver = pendingTaskResolvers.get(task.id);
        if (resolver) {
            resolver.reject(new Error('Thread not found during worker completion.'));
            pendingTaskResolvers.delete(task.id);
        }
        return;
    }

    const updatedTask: ChatWorkerTask = {
        ...task,
        status: shouldFail ? 'failed' : 'completed',
        completedAt: nowIso(),
        errorMessage: shouldFail ? 'Simulated worker failure for testing resiliency.' : undefined,
    };

    upsertTask(updatedTask);

    const updatedThread: ChatThread = {
        ...targetThread,
        ownerId: normalizeOwnerId(targetThread.ownerId),
        modelId: task.selectedModelId,
        updatedAt: nowIso(),
        messages: targetThread.messages.map((message) => {
            if (message.id !== placeholderMessageId) {
                return message;
            }

            if (shouldFail) {
                return {
                    ...message,
                    status: 'failed',
                    content: 'Worker execution failed. Please retry or adjust the prompt.',
                    metadata: {
                        ...(message.metadata ?? {}),
                    },
                };
            }

            return {
                ...message,
                status: 'completed',
                content: buildWorkerResponse(plugin, task.prompt, task.selectedScopes, task.selectedModelId),
                metadata: {
                    ...(message.metadata ?? {}),
                    pluginId: plugin.id,
                    pluginName: plugin.name,
                    modelId: task.selectedModelId,
                    modelName: task.selectedModelName,
                },
            };
        }),
    };

    upsertThread(updatedThread);

    const resolver = pendingTaskResolvers.get(task.id);
    if (!resolver) {
        return;
    }

    if (shouldFail) {
        resolver.reject(new Error(updatedTask.errorMessage ?? 'Worker failed.'));
    } else {
        resolver.resolve({ thread: updatedThread, task: updatedTask });
    }

    pendingTaskResolvers.delete(task.id);
}

/**
 * Queues a worker task and asynchronously completes it.
 */
function enqueueWorkerTask(task: ChatWorkerTask, placeholderMessageId: string): void {
    const runningTask: ChatWorkerTask = {
        ...task,
        status: 'running',
        startedAt: nowIso(),
    };

    upsertTask(runningTask);

    window.setTimeout(() => {
        completeWorkerTask(runningTask, placeholderMessageId);
    }, WORKER_EXECUTION_LATENCY_MS);
}

/**
 * Lists all persisted threads sorted by recent activity.
 */
export async function listThreads(ownerId?: string): Promise<ChatThread[]> {
    const threads = readThreads();
    const normalizedOwnerId = ownerId ? normalizeOwnerId(ownerId) : undefined;

    // Include threads owned by the user OR legacy threads that have no ownerId
    // (created before per-user partitioning was introduced).
    const filteredThreads = normalizedOwnerId
        ? threads.filter((thread) => {
            if (!thread.ownerId) {
                return true; // Legacy unowned thread — visible to all authenticated users.
            }
            return normalizeOwnerId(thread.ownerId) === normalizedOwnerId;
        })
        : threads;

    return filteredThreads.sort((left, right) => right.updatedAt.localeCompare(left.updatedAt));
}

/**
 * Appends user and placeholder assistant messages, then enqueues worker execution.
 */
export async function appendMessage(request: AppendMessageRequest): Promise<AppendMessageResponse> {
    const prompt = sanitizePrompt(request.prompt);
    if (!prompt) {
        throw new Error('Prompt is required.');
    }

    if (request.selectedScopes.length === 0) {
        throw new Error('At least one context scope must be selected.');
    }

    const plugin = resolvePluginForMessage(prompt, request.selectedScopes);
    const selectedModel = resolveChatModel(request.selectedModelId, request.selectedScopes, prompt);
    const ownerId = normalizeOwnerId(request.senderId);
    const thread = getOrCreateThread(request.threadId, prompt, request.selectedScopes, ownerId, selectedModel.id);

    const userMessage: ChatMessage = {
        id: createMessageId('user'),
        role: 'user',
        content: prompt,
        createdAt: nowIso(),
    };

    const assistantPlaceholder: ChatMessage = {
        id: createMessageId('assistant'),
        role: 'assistant',
        content: 'Worker task accepted. Orchestrating plugin execution...',
        createdAt: nowIso(),
        status: 'running',
        metadata: {
            pluginId: plugin.id,
            pluginName: plugin.name,
            modelId: selectedModel.id,
            modelName: selectedModel.label,
            selectedScopes: [...request.selectedScopes],
        },
    };

    const updatedThread: ChatThread = {
        ...thread,
        ownerId,
        title: thread.messages.length <= 1 ? buildThreadTitle(prompt, request.selectedScopes) : thread.title,
        contexts: [...request.selectedScopes],
        modelId: selectedModel.id,
        unread: false,
        updatedAt: nowIso(),
        messages: [...thread.messages, userMessage, assistantPlaceholder],
    };

    upsertThread(updatedThread);

    const task: ChatWorkerTask = {
        id: createMessageId('task'),
        threadId: updatedThread.id,
        ownerId,
        pluginId: plugin.id,
        pluginName: plugin.name,
        selectedModelId: selectedModel.id,
        selectedModelName: selectedModel.label,
        status: 'queued',
        prompt,
        selectedScopes: [...request.selectedScopes],
        createdAt: nowIso(),
    };

    upsertTask(task);
    enqueueWorkerTask(task, assistantPlaceholder.id);

    return {
        thread: updatedThread,
        task,
    };
}

/**
 * Waits for a worker task completion or failure and returns updated thread state.
 */
export async function waitForTaskResult(taskId: string, ownerId?: string): Promise<WorkerCompletionResult> {
    const normalizedOwnerId = ownerId ? normalizeOwnerId(ownerId) : undefined;
    const knownTask = readTasks().find((task) => (
        task.id === taskId
        && (!normalizedOwnerId || !task.ownerId || normalizeOwnerId(task.ownerId) === normalizedOwnerId)
    ));

    if (!knownTask) {
        throw new Error('Task not found.');
    }

    if (knownTask.status === 'completed') {
        const thread = readThreads().find((knownThread) => (
            knownThread.id === knownTask.threadId
            && (!normalizedOwnerId || !knownThread.ownerId || normalizeOwnerId(knownThread.ownerId) === normalizedOwnerId)
        ));
        if (!thread) {
            throw new Error('Thread not found for completed task.');
        }

        return { task: knownTask, thread };
    }

    if (knownTask.status === 'failed') {
        throw new Error(knownTask.errorMessage ?? 'Task failed.');
    }

    return new Promise<WorkerCompletionResult>((resolve, reject) => {
        pendingTaskResolvers.set(taskId, { resolve, reject });
    });
}

/**
 * Returns persisted worker tasks for diagnostics and local debugging.
 */
export async function listWorkerTasks(ownerId?: string): Promise<ChatWorkerTask[]> {
    const tasks = readTasks();
    const normalizedOwnerId = ownerId ? normalizeOwnerId(ownerId) : undefined;
    const filteredTasks = normalizedOwnerId
        ? tasks.filter((task) => normalizeOwnerId(task.ownerId) === normalizedOwnerId)
        : tasks;

    return filteredTasks.sort((left, right) => right.createdAt.localeCompare(left.createdAt));
}

/**
 * Clears persisted backend mock state for tests or manual reset workflows.
 */
export function resetChatBackendMockState(): void {
    localStorage.removeItem(CHAT_THREADS_STORAGE_KEY);
    localStorage.removeItem(CHAT_TASKS_STORAGE_KEY);
    pendingTaskResolvers.clear();
}
