#!/usr/bin/env bash
# Generated by GitHub Copilot
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

echo "[pre-commit] Running lint checks..."
node ./tools/scripts/run-nx.js run-many --target=lint --all --parallel=3

echo "[pre-commit] Running type checks..."
npx tsc -p tsconfig.base.json --noEmit

echo "[pre-commit] All checks passed."
