// Generated by GitHub Copilot
import React from 'react';
import { act, render } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { AppEvent, type AppEventPayload, eventBus, useEventBus } from './index';

/**
 * Builds a valid payload for the RISK_UPDATED event with optional overrides.
 */
function buildRiskUpdatedPayload(
  overrides: Partial<AppEventPayload[AppEvent.RiskUpdated]> = {}
): AppEventPayload[AppEvent.RiskUpdated] {
  return {
    riskId: 'RISK-001',
    riskLevel: 'medium',
    meta: {
      sourceApp: 'risk-assessment',
      correlationId: '8d6b920f-b8e3-4388-b0a3-8f4e8f6a6753',
      emittedAt: new Date().toISOString(),
    },
    ...overrides,
  };
}

interface EventSubscriptionHarnessProps {
  onEvent: (payload: AppEventPayload[AppEvent.RiskUpdated]) => void;
}

/**
 * Test harness that subscribes to a single event using the shared hook.
 */
function EventSubscriptionHarness({ onEvent }: EventSubscriptionHarnessProps): React.JSX.Element {
  useEventBus(AppEvent.RiskUpdated, onEvent);
  return React.createElement('div', null, 'event subscription harness');
}

describe('@shared/event-bus contract behavior', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    eventBus.clear();
  });

  afterEach(() => {
    eventBus.clear();
  });

  it('delivers typed payloads for RISK_UPDATED listeners', () => {
    const listener = vi.fn<(payload: AppEventPayload[AppEvent.RiskUpdated]) => void>();
    eventBus.on(AppEvent.RiskUpdated, listener);

    const payload = buildRiskUpdatedPayload();
    eventBus.emit(AppEvent.RiskUpdated, payload);

    expect(listener).toHaveBeenCalledTimes(1);
    expect(listener).toHaveBeenCalledWith(payload);
  });

  it('suppresses duplicate payload emissions inside the dedupe window', () => {
    const listener = vi.fn<(payload: AppEventPayload[AppEvent.RiskUpdated]) => void>();
    eventBus.on(AppEvent.RiskUpdated, listener);

    const payload = buildRiskUpdatedPayload();
    eventBus.emit(AppEvent.RiskUpdated, payload);
    eventBus.emit(AppEvent.RiskUpdated, payload);

    expect(listener).toHaveBeenCalledTimes(1);
  });

  it('does not suppress distinct payload emissions', () => {
    const listener = vi.fn<(payload: AppEventPayload[AppEvent.RiskUpdated]) => void>();
    eventBus.on(AppEvent.RiskUpdated, listener);

    eventBus.emit(AppEvent.RiskUpdated, buildRiskUpdatedPayload({ riskId: 'RISK-001' }));
    eventBus.emit(AppEvent.RiskUpdated, buildRiskUpdatedPayload({ riskId: 'RISK-002' }));

    expect(listener).toHaveBeenCalledTimes(2);
  });

  it('clears only the requested event listeners when clear(event) is used', () => {
    const riskListener = vi.fn<(payload: AppEventPayload[AppEvent.RiskUpdated]) => void>();
    const complianceListener = vi.fn<
      (payload: AppEventPayload[AppEvent.ComplianceStatusChanged]) => void
    >();

    eventBus.on(AppEvent.RiskUpdated, riskListener);
    eventBus.on(AppEvent.ComplianceStatusChanged, complianceListener);

    eventBus.clear(AppEvent.RiskUpdated);

    eventBus.emit(AppEvent.RiskUpdated, buildRiskUpdatedPayload());
    eventBus.emit(AppEvent.ComplianceStatusChanged, {
      controlId: 'CTRL-9',
      newStatus: 'compliant',
    });

    expect(riskListener).not.toHaveBeenCalled();
    expect(complianceListener).toHaveBeenCalledTimes(1);
  });

  it('useEventBus unsubscribes listener on component unmount', () => {
    const listener = vi.fn<(payload: AppEventPayload[AppEvent.RiskUpdated]) => void>();
    const view = render(React.createElement(EventSubscriptionHarness, { onEvent: listener }));

    view.unmount();

    act(() => {
      eventBus.emit(AppEvent.RiskUpdated, buildRiskUpdatedPayload());
    });

    expect(listener).not.toHaveBeenCalled();
  });

  it('useEventBus forwards events to the latest handler reference', () => {
    const firstHandler = vi.fn<(payload: AppEventPayload[AppEvent.RiskUpdated]) => void>();
    const secondHandler = vi.fn<(payload: AppEventPayload[AppEvent.RiskUpdated]) => void>();

    const view = render(React.createElement(EventSubscriptionHarness, { onEvent: firstHandler }));
    view.rerender(React.createElement(EventSubscriptionHarness, { onEvent: secondHandler }));

    act(() => {
      eventBus.emit(AppEvent.RiskUpdated, buildRiskUpdatedPayload());
    });

    expect(firstHandler).not.toHaveBeenCalled();
    expect(secondHandler).toHaveBeenCalledTimes(1);
  });
});
