import React, { useMemo, useState } from 'react';
import Alert from '@mui/material/Alert';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import Checkbox from '@mui/material/Checkbox';
import CircularProgress from '@mui/material/CircularProgress';
import Divider from '@mui/material/Divider';
import FormControlLabel from '@mui/material/FormControlLabel';
import IconButton from '@mui/material/IconButton';
import InputAdornment from '@mui/material/InputAdornment';
import Link from '@mui/material/Link';
import Paper from '@mui/material/Paper';
import TextField from '@mui/material/TextField';
import Typography from '@mui/material/Typography';
import EmailOutlinedIcon from '@mui/icons-material/EmailOutlined';
import LockOutlinedIcon from '@mui/icons-material/LockOutlined';
import SecurityOutlinedIcon from '@mui/icons-material/SecurityOutlined';
import TrendingUpOutlinedIcon from '@mui/icons-material/TrendingUpOutlined';
import VisibilityOffOutlinedIcon from '@mui/icons-material/VisibilityOffOutlined';
import VisibilityOutlinedIcon from '@mui/icons-material/VisibilityOutlined';
import { type LoginCredentials } from '@shared/auth';
import { customBrand } from '@shared/ui-components';

interface LoginScreenProps {
    onLogin: (credentials: LoginCredentials) => Promise<void>;
    isLoading: boolean;
    errorMessage?: string | null;
}

interface LoginFormState {
    email: string;
    password: string;
    rememberDevice: boolean;
}

interface LoginValidationErrors {
    email?: string;
    password?: string;
}

// Generated by GitHub Copilot
const INITIAL_FORM_STATE: LoginFormState = {
    email: '',
    password: '',
    rememberDevice: true,
};

// Generated by GitHub Copilot
const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

// Generated by GitHub Copilot
const BRAND_COLORS = {
    purplePrimary: customBrand.corePurple1,
    purpleDeep: customBrand.corePurple3,
    purpleSecondary: customBrand.corePurple2,
    bluePrimary: customBrand.enterpriseBlue5,
    blueDeep: customBrand.enterpriseBlue7,
    textStrong: '#111827',
    textMuted: '#475467',
    surface: '#fcfcfe',
    backgroundBase: '#eef2f9',
} as const;

/**
 * Archaic Search brand mark used in auth header.
 */
const ArchaicSearchMark: React.FC<{ color?: string; size?: number }> = ({ color = '#ffffff', size = 24 }) => (
    <Box
        component="svg"
        aria-hidden="true"
        width={size}
        height={size}
        viewBox="0 0 24 24"
        sx={{ display: 'block', flexShrink: 0 }}
    >
        <circle cx="10" cy="10" r="5.5" fill="none" stroke={color} strokeWidth="2" />
        <path d="M14 14L20 20" stroke={color} strokeWidth="2" strokeLinecap="round" />
        <path d="M10 3.5L11.2 6L13.8 7.2L11.2 8.4L10 11L8.8 8.4L6.2 7.2L8.8 6L10 3.5Z" fill={color} />
    </Box>
);

/**
 * Validates login fields before triggering the secure auth flow.
 * @security Prevents empty or malformed values from entering auth handlers.
 */
function getValidationErrors(formState: LoginFormState): LoginValidationErrors {
    const errors: LoginValidationErrors = {};

    if (!formState.email.trim()) {
        errors.email = 'Work email is required.';
    } else if (!EMAIL_PATTERN.test(formState.email.trim())) {
        errors.email = 'Enter a valid email address.';
    }

    if (!formState.password.trim()) {
        errors.password = 'Password is required.';
    }

    return errors;
}

/**
 * LoginScreen renders the sign-in experience for unauthenticated users.
 * @accessibility Uses semantic form controls, visible labels, helper text, and keyboard-friendly focus order.
 */
const LoginScreen: React.FC<LoginScreenProps> = ({ onLogin, isLoading, errorMessage }) => {
    const [formState, setFormState] = useState<LoginFormState>(INITIAL_FORM_STATE);
    const [showPassword, setShowPassword] = useState(false);
    const [isSubmitted, setIsSubmitted] = useState(false);

    const validationErrors = useMemo(() => getValidationErrors(formState), [formState]);
    const shouldShowError = (field: keyof LoginValidationErrors): boolean => (
        isSubmitted && Boolean(validationErrors[field])
    );

    /**
     * Updates text fields while trimming only edge whitespace from email.
     */
    const handleFieldChange = (field: 'email' | 'password') => (
        event: React.ChangeEvent<HTMLInputElement>
    ) => {
        const value = event.target.value;
        setFormState((previousState) => ({
            ...previousState,
            [field]: field === 'email' ? value.trimStart() : value,
        }));
    };

    /**
     * Submits login and defers credential verification to the auth provider.
     */
    const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
        event.preventDefault();
        setIsSubmitted(true);

        if (validationErrors.email || validationErrors.password || isLoading) {
            return;
        }

        await onLogin({
            email: formState.email.trim().toLowerCase(),
            password: formState.password,
            rememberDevice: formState.rememberDevice,
        });
    };

    return (
        <Box
            component="main"
            role="main"
            aria-label="Sign in"
            sx={{
                minHeight: '100vh',
                display: 'grid',
                placeItems: 'center',
                px: { xs: 2, sm: 4 },
                py: { xs: 3, sm: 5 },
                position: 'relative',
                overflow: 'hidden',
                bgcolor: '#ffffff',
                '@keyframes loginCardEnter': {
                    from: {
                        opacity: 0,
                        transform: 'translateY(20px) scale(0.99)',
                    },
                    to: {
                        opacity: 1,
                        transform: 'translateY(0) scale(1)',
                    },
                },
                '@keyframes panelFadeIn': {
                    from: {
                        opacity: 0,
                        transform: 'translateX(-18px)',
                    },
                    to: {
                        opacity: 1,
                        transform: 'translateX(0)',
                    },
                },
            }}
        >
            <Paper
                elevation={0}
                sx={{
                    width: '100%',
                    maxWidth: 1020,
                    borderRadius: 3,
                    border: `1px solid ${BRAND_COLORS.blueDeep}2b`,
                    boxShadow: '0 28px 60px rgba(16, 24, 40, 0.15)',
                    overflow: 'hidden',
                    display: 'grid',
                    gridTemplateColumns: { xs: '1fr', lg: '1.05fr 1fr' },
                    animation: 'loginCardEnter 520ms cubic-bezier(0.17, 0.84, 0.44, 1) forwards',
                }}
            >
                <Box
                    sx={{
                        display: { xs: 'none', lg: 'grid' },
                        p: { xs: 3, sm: 4.5 },
                        color: BRAND_COLORS.textStrong,
                        gap: 2,
                        alignContent: 'space-between',
                        backgroundColor: '#ffffff',
                        borderRight: { xs: 'none', md: `1px solid ${BRAND_COLORS.textStrong}1f` },
                        borderBottom: { xs: `1px solid ${BRAND_COLORS.textStrong}1f`, md: 'none' },
                        animation: 'panelFadeIn 520ms 80ms ease-out both',
                    }}
                >
                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 1.25 }}>
                        <ArchaicSearchMark size={28} color={BRAND_COLORS.purplePrimary} />
                        <Typography
                            component="span"
                            sx={{
                                fontWeight: 700,
                                fontSize: '1rem',
                                letterSpacing: '0.02em',
                                fontFamily: 'Graphik, "Segoe UI", sans-serif',
                                color: BRAND_COLORS.textStrong,
                            }}
                        >
                            archaic search
                        </Typography>
                    </Box>

                    <Box sx={{ display: 'grid', gap: 1 }}>
                        <Typography
                            variant="overline"
                            sx={{
                                letterSpacing: '0.18em',
                                color: BRAND_COLORS.textMuted,
                                fontFamily: '"Space Grotesk", Graphik, "Segoe UI", sans-serif',
                            }}
                        >
                            Archaic Search Partner Portal
                        </Typography>
                        <Typography
                            variant="h4"
                            component="h1"
                            sx={{
                                fontWeight: 700,
                                lineHeight: 1.2,
                                fontFamily: '"Space Grotesk", Graphik, "Segoe UI", sans-serif',
                                color: BRAND_COLORS.textStrong,
                            }}
                        >
                            One Archaic Search workspace for partner risk, compliance, and trust.
                        </Typography>
                        <Typography variant="body1" sx={{ color: BRAND_COLORS.textMuted }}>
                            Drive audit, onboarding, incident, and policy workflows with a consistent enterprise operating model.
                        </Typography>
                    </Box>

                    <Box component="ul" sx={{ m: 0, p: 0, listStyle: 'none', display: 'grid', gap: 1.5 }}>
                        <Box component="li" sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                            <SecurityOutlinedIcon fontSize="small" aria-hidden="true" sx={{ color: BRAND_COLORS.purpleSecondary }} />
                            <Typography variant="body2" sx={{ color: BRAND_COLORS.textStrong }}>
                                Identity-based access controls with centralized audit trails
                            </Typography>
                        </Box>
                        <Box component="li" sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                            <TrendingUpOutlinedIcon fontSize="small" aria-hidden="true" sx={{ color: BRAND_COLORS.purpleSecondary }} />
                            <Typography variant="body2" sx={{ color: BRAND_COLORS.textStrong }}>
                                Real-time KPI visibility across every risk domain
                            </Typography>
                        </Box>
                    </Box>
                </Box>

                <Box
                    sx={{
                        p: { xs: 3, sm: 4.5 },
                        bgcolor: BRAND_COLORS.surface,
                        '& .MuiFormLabel-root': {
                            color: `${BRAND_COLORS.textStrong}b8`,
                        },
                        '& .MuiFormLabel-root.Mui-focused': {
                            color: BRAND_COLORS.purplePrimary,
                        },
                        '& .MuiInputBase-input': {
                            color: BRAND_COLORS.textStrong,
                            '&:-webkit-autofill, &:-webkit-autofill:hover, &:-webkit-autofill:focus': {
                                WebkitTextFillColor: BRAND_COLORS.textStrong,
                                WebkitBoxShadow: '0 0 0 1000px #ffffff inset',
                                caretColor: BRAND_COLORS.textStrong,
                                borderRadius: 8,
                                transition: 'background-color 9999s ease-in-out 0s',
                            },
                        },
                        '& .MuiFormHelperText-root': {
                            color: BRAND_COLORS.textMuted,
                        },
                        '& .MuiOutlinedInput-root': {
                            backgroundColor: '#ffffff',
                            borderRadius: 2,
                            '& fieldset': {
                                borderColor: `${BRAND_COLORS.textStrong}33`,
                            },
                            '&:hover fieldset': {
                                borderColor: `${BRAND_COLORS.bluePrimary}99`,
                            },
                            '&.Mui-focused fieldset': {
                                borderColor: BRAND_COLORS.purplePrimary,
                                borderWidth: 2,
                            },
                        },
                    }}
                >
                    <Typography
                        variant="h5"
                        component="h2"
                        sx={{
                            mb: 1,
                            fontWeight: 700,
                            color: BRAND_COLORS.textStrong,
                            fontFamily: '"Space Grotesk", Graphik, "Segoe UI", sans-serif',
                        }}
                    >
                        Sign in
                    </Typography>
                    <Typography variant="body2" sx={{ mb: 3, color: BRAND_COLORS.textMuted }}>
                        Use your Archaic Search enterprise credentials to access the partner operations workspace.
                    </Typography>

                    {errorMessage && (
                        <Alert severity="error" sx={{ mb: 2 }} role="alert" aria-live="assertive">
                            {errorMessage}
                        </Alert>
                    )}

                    <Box component="form" noValidate onSubmit={handleSubmit} sx={{ display: 'grid', gap: 2 }}>
                        <TextField
                            id="login-email"
                            label="Work email"
                            name="email"
                            type="email"
                            autoComplete="email"
                            required
                            fullWidth
                            value={formState.email}
                            onChange={handleFieldChange('email')}
                            error={shouldShowError('email')}
                            helperText={shouldShowError('email') ? validationErrors.email : ' '}
                            InputProps={{
                                startAdornment: (
                                    <InputAdornment position="start">
                                        <EmailOutlinedIcon fontSize="small" aria-hidden="true" />
                                    </InputAdornment>
                                ),
                            }}
                        />

                        <TextField
                            id="login-password"
                            label="Password"
                            name="password"
                            type={showPassword ? 'text' : 'password'}
                            autoComplete="current-password"
                            required
                            fullWidth
                            value={formState.password}
                            onChange={handleFieldChange('password')}
                            error={shouldShowError('password')}
                            helperText={shouldShowError('password') ? validationErrors.password : ' '}
                            InputProps={{
                                startAdornment: (
                                    <InputAdornment position="start">
                                        <LockOutlinedIcon fontSize="small" aria-hidden="true" />
                                    </InputAdornment>
                                ),
                                endAdornment: (
                                    <InputAdornment position="end">
                                        <IconButton
                                            type="button"
                                            aria-label={showPassword ? 'Hide password' : 'Show password'}
                                            onClick={() => setShowPassword((previous) => !previous)}
                                            edge="end"
                                        >
                                            {showPassword ? (
                                                <VisibilityOffOutlinedIcon fontSize="small" />
                                            ) : (
                                                <VisibilityOutlinedIcon fontSize="small" />
                                            )}
                                        </IconButton>
                                    </InputAdornment>
                                ),
                            }}
                        />

                        <Box
                            sx={{
                                mt: -0.5,
                                mb: 1,
                                display: 'flex',
                                flexDirection: { xs: 'column', sm: 'row' },
                                justifyContent: 'space-between',
                                alignItems: { xs: 'flex-start', sm: 'center' },
                                gap: 0.5,
                            }}
                        >
                            <FormControlLabel
                                control={(
                                    <Checkbox
                                        checked={formState.rememberDevice}
                                        sx={{
                                            color: `${BRAND_COLORS.textStrong}99`,
                                            '&.Mui-checked': {
                                                color: BRAND_COLORS.purplePrimary,
                                            },
                                        }}
                                        onChange={(event) => {
                                            setFormState((previousState) => ({
                                                ...previousState,
                                                rememberDevice: event.target.checked,
                                            }));
                                        }}
                                        name="remember-device"
                                    />
                                )}
                                label="Remember this device"
                                sx={{ color: BRAND_COLORS.textMuted }}
                            />
                            <Link
                                href="#"
                                underline="hover"
                                onClick={(event) => event.preventDefault()}
                                aria-label="Get help signing in"
                                sx={{ color: BRAND_COLORS.bluePrimary, fontWeight: 500 }}
                            >
                                Need help signing in?
                            </Link>
                        </Box>

                        <Button
                            type="submit"
                            variant="contained"
                            size="large"
                            disabled={isLoading}
                            sx={{
                                py: 1.2,
                                fontWeight: 700,
                                letterSpacing: '0.01em',
                                backgroundImage: `linear-gradient(96deg, ${BRAND_COLORS.purplePrimary} 0%, ${BRAND_COLORS.purpleSecondary} 52%, ${BRAND_COLORS.bluePrimary} 100%)`,
                                '&:hover': {
                                    backgroundImage: `linear-gradient(96deg, ${BRAND_COLORS.purpleSecondary} 0%, ${BRAND_COLORS.purpleDeep} 50%, ${BRAND_COLORS.blueDeep} 100%)`,
                                },
                            }}
                        >
                            {isLoading ? (
                                <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                                    <CircularProgress size={18} color="inherit" />
                                    <span>Signing in...</span>
                                </Box>
                            ) : (
                                'Continue with Archaic Search ID'
                            )}
                        </Button>
                    </Box>

                    <Divider sx={{ my: 3 }} />

                    <Typography variant="caption" sx={{ color: BRAND_COLORS.textMuted }}>
                        Archaic Search internal use only. This workspace protects partner data and records privileged actions for compliance reviews.
                    </Typography>
                </Box>
            </Paper>
        </Box>
    );
};

export default LoginScreen;
