// Generated by GitHub Copilot
import React from 'react';
import Box from '@mui/material/Box';
import Paper from '@mui/material/Paper';
import Typography from '@mui/material/Typography';

/**
 * Large summary panel describing the application purpose and value.
 */
const AboutPortalSection: React.FC = () => (
    <Paper
        component="section"
        aria-labelledby="about-portal-title"
        elevation={0}
        sx={{
            p: { xs: 2.25, sm: 3.25 },
            border: '1px solid',
            borderColor: 'divider',
            borderRadius: 2,
            background: 'linear-gradient(135deg, rgba(9, 61, 120, 0.1) 0%, rgba(20, 107, 79, 0.1) 100%)',
        }}
    >
        <Typography id="about-portal-title" component="h2" variant="h5" sx={{ fontWeight: 800 }}>
            About Us
        </Typography>
        <Typography variant="body1" sx={{ mt: 1.25, maxWidth: '90ch' }}>
            This Partner Portal brings together risk and compliance micro applications in one place.
            We are building a secure, role-aware workspace that helps teams onboard partners, monitor risk,
            manage policy and audit workflows, and respond to incidents quickly.
        </Typography>
        <Box component="p" sx={{ m: 0, mt: 1.25, color: 'text.secondary', fontSize: '0.95rem' }}>
            Use the micro-app cards below to jump directly to the capability you need.
        </Box>
    </Paper>
);

export default AboutPortalSection;
