// Generated by GitHub Copilot
import React from 'react';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import AboutPortalSection from './AboutPortalSection';
import AuditManagementCard from './cards/AuditManagementCard';
import ComplianceDashboardCard from './cards/ComplianceDashboardCard';
import IncidentReportingCard from './cards/IncidentReportingCard';
import PartnerOnboardingCard from './cards/PartnerOnboardingCard';
import PolicyManagementCard from './cards/PolicyManagementCard';
import RiskAssessmentCard from './cards/RiskAssessmentCard';
import VendorRiskCard from './cards/VendorRiskCard';

/**
 * Shell landing page with portal context and navigation entry points for all micro apps.
 */
const HomePage: React.FC = () => (
    <Box component="section" aria-labelledby="home-page-title" sx={{ display: 'grid', gap: 2.5 }}>
        <Typography id="home-page-title" component="h1" variant="h4" sx={{ fontWeight: 800 }}>
            Partner Portal Home
        </Typography>

        <AboutPortalSection />

        <Box component="section" aria-labelledby="microapps-section-title">
            <Typography id="microapps-section-title" component="h2" variant="h5" sx={{ fontWeight: 700, mb: 1.5 }}>
                What We Provide - Micro Apps
            </Typography>

            <Box
                sx={{
                    display: 'grid',
                    gridTemplateColumns: {
                        xs: '1fr',
                        sm: 'repeat(2, minmax(0, 1fr))',
                        lg: 'repeat(3, minmax(0, 1fr))',
                    },
                    gap: 1.5,
                }}
            >
                <RiskAssessmentCard />
                <ComplianceDashboardCard />
                <AuditManagementCard />
                <PolicyManagementCard />
                <IncidentReportingCard />
                <VendorRiskCard />
                <PartnerOnboardingCard />
            </Box>
        </Box>
    </Box>
);

export default HomePage;
