// Generated by GitHub Copilot
import React from 'react';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import Paper from '@mui/material/Paper';
import Typography from '@mui/material/Typography';
import { Link as RouterLink } from 'react-router-dom';

export interface MicroAppCardProps {
    title: string;
    description: string;
    path: string;
}

/**
 * Reusable micro-app card with a clear CTA for safe in-portal navigation.
 * @security Uses internal react-router links only; no untrusted URL injection.
 */
const MicroAppCard: React.FC<MicroAppCardProps> = ({ title, description, path }) => (
    <Paper
        component="article"
        elevation={0}
        sx={{
            p: 2,
            border: '1px solid',
            borderColor: 'divider',
            borderRadius: 2,
            display: 'grid',
            gap: 1.25,
            minHeight: 180,
            bgcolor: 'background.paper',
        }}
    >
        <Box>
            <Typography component="h3" variant="h6" sx={{ fontSize: '1.02rem', fontWeight: 700 }}>
                {title}
            </Typography>
            <Typography variant="body2" color="text.secondary" sx={{ mt: 0.75 }}>
                {description}
            </Typography>
        </Box>

        <Box sx={{ mt: 'auto' }}>
            <Button
                component={RouterLink}
                to={path}
                variant="contained"
                size="small"
                aria-label={`Open ${title}`}
            >
                Open Micro App
            </Button>
        </Box>
    </Paper>
);

export default MicroAppCard;
