// Generated by GitHub Copilot
const { createRemoteWebpackConfig } = require('../../tools/webpack/remoteConfig');
module.exports = createRemoteWebpackConfig({ name: 'incidentReporting', port: 4205, appDir: __dirname });
